package com.example.ui

/**
 * Complete English Harmony catalog.
 *
 * The entries preserve the German display source as the lookup key. User-entered
 * names, messages and answers intentionally remain unchanged at runtime.
 */
internal val EXACT_ENGLISH_CONTENT: Map<String, String> = mapOf(
    ", listOf(" to ", listOf(",
    "1-5 Jahre" to "1-5 years",
    "1000 - 1500 im Monat" to "1000 - 1500 a month",
    "1000 bis 3000" to "1000 to 3000",
    "1500 - 2000 im Monat" to "1500 - 2000 a month",
    "3000 bis 5000" to "3000 to 5000",
    "5-10 Jahre" to "5-10 years",
    "50-100€/Monat" to "50-100€/month",
    "Ab 100€" to "From 100€",
    "Ab 500€" to "From 500€",
    "Ab 50€" to "From 50€",
    "Ab und zu" to "From time to time",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "Above what amount do we discuss before making a purchase?",
    "Abbrechen" to "Cancel",
    "Abenteuer" to "Adventure",
    "Alle" to "All",
    "Alle Pakete" to "All packs",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "Lose all your friends except your best friend",
    "Alle intimen Momente selbst initiieren" to "Initiate all intimate moments yourself",
    "Alles davon" to "All of the above",
    "Alles, was noch kommt" to "Everything yet to come",
    "Alltagsroutine" to "Everyday routine",
    "Alltägliche Berührungen" to "Everyday physical touch",
    "Altbau mit Charme" to "Historic charm apartment",
    "Am Strand" to "At the beach",
    "Am liebsten alles zusammen" to "Preferably everything together",
    "Am selben Tag mit Freunden/Familie" to "On the same day with friends/family",
    "Amsterdam" to "Amsterdam",
    "Amsterdam, Niederlande" to "Amsterdam, Netherlands",
    "An das Gefühl" to "Remembering the feeling",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "In a public place with many spectators",
    "An einen Geruch" to "Remembering a scent",
    "An einen Song" to "Remembering a song",
    "An etwas, das ich gesagt habe" to "Something I said",
    "Analyse starten" to "Start analysis",
    "Ananas auf der Pizza schmeckt köstlich." to "Pineapple on pizza tastes delicious.",
    "Antwort mit einem Foto" to "Answer with a photo",
    "Antwortähnlichkeit" to "Answer similarity",
    "Auf eine Bootsparty gehen" to "Go to a boat party",
    "Aufmerksamkeit" to "Attention",
    "Aufräumen und Projekte angehen" to "Tidying up and tackling projects",
    "Aufwärmen" to "Warm-up",
    "Aus dem Urlaub" to "From the vacation",
    "Ausgefallener Name" to "Unusual name",
    "Ausschlafen und faulenzen" to "Sleeping in and lounging around",
    "Ausschlafen und nichts tun" to "Ausschlafen und nichts tun",
    "Aussehen" to "Looks",
    "Auto" to "Car",
    "Außenkamin" to "Außenkamin",
    "BEANTWORTE" to "ANSWER",
    "Bali" to "Bali",
    "Bali, Indonesien" to "Bali, Indonesia",
    "Banane" to "Banane",
    "Beantwortet" to "Answered",
    "Beantwortete Fragen" to "Questions answered",
    "Bearbeiten" to "Edit",
    "Bei Insider-Witzen" to "Bei Insider-Witzen",
    "Bei Memes" to "Bei Memes",
    "Bei einer spontanen Berührung" to "Bei einer spontanen Berührung",
    "Beide" to "Both",
    "Beide gleich" to "Beide gleich",
    "Beide zusammen" to "Beide zusammen",
    "Beide, aber wir tun so als ob nicht" to "Beide, aber wir tun so als ob nicht",
    "Beides" to "Beides",
    "Beim Einschlafen nebeneinander" to "Beim Einschlafen nebeneinander",
    "Beim Reden" to "Beim Reden",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Berühmte Touristenorte sind immer eine Enttäuschung.",
    "Beschreibe unser Sexleben mit einem Emoji." to "Beschreibe unser Sexleben mit einem Emoji.",
    "Besser kommunizieren" to "Communicate better",
    "Bessere Lage" to "Bessere Lage",
    "Bestellen" to "Bestellen",
    "Besuchte Länder" to "Countries visited",
    "Besuchte Städte" to "Cities visited",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Do you prefer an extravagant proposal or something subtle?",
    "Beziehung" to "Relationship",
    "Bibliothek" to "Bibliothek",
    "Bin manchmal unsicher" to "I'm sometimes unsure",
    "Blumenwiese" to "Blumenwiese",
    "Bunte Blumenwiese" to "Bunte Blumenwiese",
    "Burger" to "Burger",
    "Cookie Dough" to "Cookie Dough",
    "Dachgarten mit Lounge" to "Dachgarten mit Lounge",
    "Dachterrasse" to "Dachterrasse",
    "Das Wetter an dem Tag" to "Das Wetter an dem Tag",
    "Das erste Selfie" to "Das erste Selfie",
    "Das meiste weiß ich" to "I know most of it",
    "Das oder das?" to "This or That?",
    "Dass Zusagen gehalten werden" to "Dass Zusagen gehalten werden",
    "Dass alles meinen Stil hat" to "Dass alles meinen Stil hat",
    "Dass ich alles erzählen kann" to "Dass ich alles erzählen kann",
    "Dass ich mich nicht sorgen muss" to "Dass ich mich nicht sorgen muss",
    "Dass wir ungestört sind" to "Dass wir ungestört sind",
    "Dein Name" to "Your name",
    "Deine Antwort..." to "Your answer...",
    "Deine Antworten sind gespeichert. Sobald Partner das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Your answers are saved. Once your partner finishes the pack, you will see both answers together.",
    "Deine Beziehung abenteuerlich und spontan machen" to "Deine Beziehung abenteuerlich und spontan machen",
    "Deine Beziehung stabil und sicher machen" to "Deine Beziehung stabil und sicher machen",
    "Deine eigene Antwort" to "Your own answer",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen",
    "Deinen besten Freund verlieren" to "Deinen besten Freund verlieren",
    "Denke an dich" to "Thinking of you",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Denselben Film zweimal zu schauen, ist Zeitverschwendung.",
    "Der Blick nach draußen" to "Der Blick nach draußen",
    "Der Garten" to "Der Garten",
    "Der Ort" to "Der Ort",
    "Der Ring und die Geste" to "The ring and the gesture",
    "Der perfekte Heiratsantrag" to "The perfect proposal",
    "Derjenige sein, der umarmt wird" to "Being the one who is hugged",
    "Deutsch" to "German",
    "Diamant" to "Diamant",
    "Diamanten im Band" to "Diamanten im Band",
    "Die Distanz" to "Die Distanz",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Spend the holidays with your partner's family",
    "Die Gemütlichkeit und Ruhe" to "Die Gemütlichkeit und Ruhe",
    "Die Menschen, die darin wohnen" to "Die Menschen, die darin wohnen",
    "Die Umgebung und Atmosphäre" to "The setting and atmosphere",
    "Die Worte und Emotionen" to "The words and emotions",
    "Diejenige sein, die umarmt" to "Being the one who hugs",
    "Direkt ansprechen" to "Discussing immediately",
    "Diskussion" to "Discussion",
    "Diskutiere vor dem Kinderkriegen" to "Discuss before having children",
    "Diskutiert eure Antworten" to "Discuss your answers",
    "Doch, schon mal" to "Doch, schon mal",
    "Draußen mit der Natur als Kulisse" to "Draußen mit der Natur als Kulisse",
    "Drei-Stein-Ring" to "Drei-Stein-Ring",
    "Du bist dran" to "Your turn",
    "Du fehlst mir" to "I miss you",
    "Dubai" to "Dubai",
    "Dubai, VAE" to "Dubai, VAE",
    "Durch Berührung" to "Through touch",
    "Durch Worte" to "Through words",
    "Durch Zeit zu zweit" to "Through quality time",
    "Durch kleine Gesten" to "Through small gestures",
    "Durchgeplant" to "Fully planned",
    "ERGEBNISSE" to "RESULTS",
    "Egal, Hauptsache gesund" to "Doesn't matter, as long as it's healthy",
    "Eher knapp" to "Rather tight",
    "Eher nicht" to "Eher nicht",
    "Eher schwer" to "Eher schwer",
    "Eher schwierig" to "Rather difficult",
    "Eher zu" to "Eher zu",
    "Eifersucht ist ein Zeichen von Liebe." to "Eifersucht ist ein Zeichen von Liebe.",
    "Eigenes Gemüsebeet" to "Home vegetable garden",
    "Ein Abenteuer in einer neuen Stadt" to "Ein Abenteuer in einer neuen Stadt",
    "Ein Anker" to "Ein Anker",
    "Ein Balkon oder Garten" to "Ein Balkon oder Garten",
    "Ein Filmabend" to "Ein Filmabend",
    "Ein Herz" to "Ein Herz",
    "Ein Herz an der Tür" to "Ein Herz an der Tür",
    "Ein Jahr lang eine Fernbeziehung führen" to "Ein Jahr lang eine Fernbeziehung führen",
    "Ein Live-Musik-Konzert besuchen" to "Ein Live-Musik-Konzert besuchen",
    "Ein Museum besuchen" to "Ein Museum besuchen",
    "Ein Spieleabend" to "Ein Spieleabend",
    "Ein Spieleabend mit Freunden" to "Ein Spieleabend mit Freunden",
    "Ein Urlaubsfoto" to "Ein Urlaubsfoto",
    "Ein aktives Abenteuer" to "Ein aktives Abenteuer",
    "Ein entspannender Spa-Tag" to "Ein entspannender Spa-Tag",
    "Ein ganz normaler Alltagstag" to "Ein ganz normaler Alltagstag",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "Ein gemütlicher Abend im Haus während eines Gewitters",
    "Ein gemütliches Date drinnen" to "Ein gemütliches Date drinnen",
    "Ein lustiges Bild" to "A funny picture",
    "Ein paar Handyfotos reichen" to "Ein paar Handyfotos reichen",
    "Ein paar Stunden" to "A few hours",
    "Ein paar kulturelle Anklänge sind okay" to "A few cultural touches are okay",
    "Ein romantischer Abend" to "Ein romantischer Abend",
    "Ein romantisches Abendessen bei Kerzenlicht" to "Ein romantisches Abendessen bei Kerzenlicht",
    "Ein romantisches Bild" to "A romantic picture",
    "Ein romantisches Picknick an einem schönen Ort" to "Ein romantisches Picknick an einem schönen Ort",
    "Ein schwerer Moment, den wir geschafft haben" to "Ein schwerer Moment, den wir geschafft haben",
    "Ein tolles Date im Freien unter dem Mondlicht" to "Ein tolles Date im Freien unter dem Mondlicht",
    "Ein zufälliger Schnappschuss" to "Ein zufälliger Schnappschuss",
    "Einander kennenlernen" to "Getting to know each other",
    "Eine Autoreise" to "Eine Autoreise",
    "Eine Brücke" to "Eine Brücke",
    "Eine Date-Nacht unter den Sternen" to "Eine Date-Nacht unter den Sternen",
    "Eine Million Dollar gewinnen" to "Eine Million Dollar gewinnen",
    "Eine Million Dollar verdienen" to "Eine Million Dollar verdienen",
    "Eine Nacht in einem Club" to "Eine Nacht in einem Club",
    "Eine Schokoladenverkostung" to "Eine Schokoladenverkostung",
    "Eine Wanderung mit Panoramablick machen" to "Eine Wanderung mit Panoramablick machen",
    "Eine Weinverkostung" to "Eine Weinverkostung",
    "Eine gemeinsame Reise" to "Eine gemeinsame Reise",
    "Eine gemütliche Nacht zu Hause" to "Eine gemütliche Nacht zu Hause",
    "Eine neue Sprache zu lernen ist einfach." to "Eine neue Sprache zu lernen ist einfach.",
    "Einen Film anschauen" to "Einen Film anschauen",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Einen Monat lang überhaupt nicht miteinander reden",
    "Einen Tanzkurs besuchen" to "Einen Tanzkurs besuchen",
    "Einen Vergnügungspark erkunden" to "Einen Vergnügungspark erkunden",
    "Einen Wellness-Tag" to "Einen Wellness-Tag",
    "Einen sehr emotionalen Partner haben" to "Einen sehr emotionalen Partner haben",
    "Einen sehr logischen Partner haben" to "Einen sehr logischen Partner haben",
    "Einer zahlt alles" to "One pays everything",
    "Einfach mehr Alltag" to "Einfach mehr Alltag",
    "Einfach nebeneinander sein" to "Einfach nebeneinander sein",
    "Einfach und intim" to "Einfach und intim",
    "Einige Dinge für dich behalten" to "Einige Dinge für dich behalten",
    "Einmal" to "Einmal",
    "Eins, das nur wir kennen" to "Eins, das nur wir kennen",
    "Englisch" to "English",
    "Entspannte Hängematte" to "Entspannte Hängematte",
    "Entspannung" to "Relaxation",
    "Entwickler Studio Öffnen" to "Open Developer Studio",
    "Entwickler-Modus" to "Developer mode",
    "Erdbeere" to "Erdbeere",
    "Erfolgreich" to "Successful",
    "Erst bei sehr großen Summen" to "Only for very large amounts",
    "Erst nur enge Freunde/Familie" to "Erst nur enge Freunde/Familie",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten.",
    "Etwa eine Woche später, erst mal nur wir" to "About a week later, just us at first",
    "Etwas Neues ausprobieren" to "Trying something new",
    "Etwas ganz anderes" to "Etwas ganz anderes",
    "Etwas, eine kleine Note wäre schön" to "Somewhat, a small touch would be nice",
    "Familie" to "Family",
    "Familie/Freunde" to "Family/Friends",
    "Familienmensch" to "Family person",
    "Farbedelstein" to "Farbedelstein",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "Fernsehwerbung ist manchmal interessant anzusehen.",
    "Fertig" to "Done",
    "Feste Date-Nights" to "Fixed date nights",
    "Feuerstelle" to "Feuerstelle",
    "Filigran & schlicht" to "Filigran & schlicht",
    "Frage hinzufügen" to "Add question",
    "Fragen & Spiele" to "Questions & Games",
    "Freizeitpark" to "Freizeitpark",
    "Freunde treffen" to "Meeting friends",
    "Freundschaften mit Ex-Partnern sind okay." to "Freundschaften mit Ex-Partnern sind okay.",
    "Früh aufstehen" to "Früh aufstehen",
    "Fußbodenheizung" to "Fußbodenheizung",
    "Führen wir getrennte oder gemeinsame Konten?" to "Führen wir getrennte oder gemeinsame Konten?",
    "Für dich empfohlen" to "Recommended for you",
    "Für die Zukunft" to "For the future",
    "Für immer" to "Forever",
    "Fürsorglichkeit" to "Caring",
    "Galerie" to "Gallery",
    "Gar nicht, der Moment gehört uns" to "Gar nicht, der Moment gehört uns",
    "Gar nichts tun" to "Gar nichts tun",
    "Geduld" to "Patience",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Geh früh am Morgen, um den Sonnenaufgang zu sehen",
    "Geht so" to "Geht so",
    "Geister existieren wirklich." to "Geister existieren wirklich.",
    "Gelassenheit" to "Serenity",
    "Gelbgold" to "Gelbgold",
    "Geld & Finanzen" to "Money & Finances",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Travel the world together, explore new cultures and cuisines",
    "Gemeinsam ein Lego bauen" to "Gemeinsam ein Lego bauen",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Gemeinsam in der Küche ein neues Rezept ausprobieren",
    "Gemeinsame Konten" to "Joint accounts",
    "Gemeinsame Nächte" to "Gemeinsame Nächte",
    "Gemeinsame Tage" to "Days together",
    "Gemischt" to "Gemischt",
    "Gemüsebeet" to "Gemüsebeet",
    "Gemütliche Feuerstelle" to "Gemütliche Feuerstelle",
    "Getrennte Konten" to "Separate accounts",
    "Getrennte Urlaube tun einer Beziehung gut." to "Getrennte Urlaube tun einer Beziehung gut.",
    "Gewächshaus" to "Gewächshaus",
    "Glasfassade" to "Glasfassade",
    "Gleichgültigkeit" to "Gleichgültigkeit",
    "Glücklich und frei" to "Happy and free",
    "Gourmet Eis-Sorten" to "Gourmet Eis-Sorten",
    "Gravur innen" to "Gravur innen",
    "Grillplatz" to "Grillplatz",
    "Groß & üppig" to "Groß & üppig",
    "Große Familie" to "Big family",
    "Große Feier" to "Große Feier",
    "Große Fenster" to "Große Fenster",
    "Große Fensterfront" to "Große Fensterfront",
    "Großer Außenpool" to "Großer Außenpool",
    "Großer Garten" to "Großer Garten",
    "Großer Stein" to "Großer Stein",
    "Größere Küche" to "Größere Küche",
    "Gutes Essen" to "Good food",
    "Habe ich" to "I have",
    "Habe ich noch nie" to "Never have I ever",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Did you discover surprising differences? Talk about why you prefer certain options!",
    "Haus am See" to "House by the lake",
    "Haus/Wohnung" to "House/Apartment",
    "Hazelnut" to "Hazelnut",
    "Heimkino" to "Heimkino",
    "Herzhaft" to "Herzhaft",
    "Hilfe im Alltag" to "Help in everyday life",
    "Himbeere" to "Himbeere",
    "Hinzufügen" to "Add",
    "Hobbys" to "Hobbies",
    "Hot Tub" to "Hot Tub",
    "Humor" to "Humor",
    "Hund" to "Dog",
    "Hängematte" to "Hängematte",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Would you like a written letter as part of the proposal?",
    "Ich" to "Ich",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch.",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Ich bin noch nie in einem Kino eingeschlafen.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner.",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen.",
    "Ich habe noch nie" to "Never have I ever",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen.",
    "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet." to "Ich habe noch nie auf meinen Brief aus Hogwarts gewartet.",
    "Ich habe noch nie bei einem Disney-Film geweint." to "Ich habe noch nie bei einem Disney-Film geweint.",
    "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe." to "Ich habe noch nie die Schuld auf den Controller geschoben, wenn ich verloren habe.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Ich habe noch nie ein Auto in einem fremden Land gefahren.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Ich habe noch nie ein Elektroauto gefahren.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist.",
    "Ich habe noch nie einen Nachtzug genommen." to "Ich habe noch nie einen Nachtzug genommen.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt.",
    "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt." to "Ich habe noch nie von einer Fahrt in der Jurassic Park Wasserbahn geträumt.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint.",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Ich habe noch nie … eine Nachricht 10x umformuliert.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Ich habe noch nie … heimlich das Handy meines Partners angeschaut.",
    "Ich habe noch nie!" to "Ich habe noch nie!",
    "Ich habe!" to "Ich habe!",
    "Ich lache viel mit meinem Partner." to "Ich lache viel mit meinem Partner.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Ich lerne gerne die Hobbys und Interessen meines Partners kennen.",
    "Ich liebe es" to "I love it",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen.",
    "Ich plane gerne Dates mit meinem Partner." to "Ich plane gerne Dates mit meinem Partner.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin.",
    "Ich schreibe meinem Partner jeden Tag." to "Ich schreibe meinem Partner jeden Tag.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Ich teile gerne Memes und Witze mit meinem Partner.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Ich teile gerne alle Details meines Tages mit meinem Partner.",
    "Ich würde es nie tun" to "Ich würde es nie tun",
    "Ich übe noch" to "Ich übe noch",
    "Ideen generieren" to "Generate ideas",
    "Im Haushalt helfen" to "Help in the household",
    "In Stille nebeneinander" to "In Stille nebeneinander",
    "In den Bergen" to "In den Bergen",
    "In eine Bar gehen" to "In eine Bar gehen",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "In eine Strandbar gehen, um den Sonnenuntergang zu sehen",
    "In einem feinen Restaurant essen gehen" to "In einem feinen Restaurant essen gehen",
    "In einen Coffeeshop gehen" to "In einen Coffeeshop gehen",
    "In einer Beziehung sollte man alles voneinander wissen." to "In einer Beziehung sollte man alles voneinander wissen.",
    "Infinity-Pool" to "Infinity pool",
    "Innenpool" to "Innenpool",
    "Intelligenz" to "Intelligence",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Having intimate moments only when initiated by your partner",
    "Island" to "Island",
    "Ist okay für mich" to "It's okay for me",
    "Ist schon perfekt" to "It's already perfect",
    "Ja, Traditionen einbinden" to "Yes, include traditions",
    "Ja, absolut" to "Yes, absolutely",
    "Ja, etwas zum Lesen und Aufbewahren" to "Yes, something to read and keep",
    "Ja, genug" to "Yes, enough",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Yes, in an exciting city or landmark",
    "Ja, in- und auswendig" to "Yes, inside out",
    "Ja, komplett überraschend" to "Ja, komplett überraschend",
    "Ja, perfekt" to "Yes, perfect",
    "Ja, sie gehören zur Familie!" to "Yes, they are part of the family!",
    "Ja, sofort teilen" to "Ja, sofort teilen",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Yes, we will ensure family time is prioritized.",
    "Jacuzzi" to "Jacuzzi",
    "Jeder zahlt 50%" to "Each pays 50%",
    "Junge" to "Boy",
    "KI-Beziehungscoach" to "AI relationship coach",
    "KI-Date-Ideen" to "AI date ideas",
    "Kamin" to "Kamin",
    "Karriere & Erfolg" to "Career & Success",
    "Kategorien" to "Categories",
    "Katze" to "Cat",
    "Keine Musik" to "No music",
    "Keine Party nötig, privat halten" to "No party needed, keep it private",
    "Keine Privatsphäre" to "No privacy",
    "Keiner" to "Keiner",
    "Keiner von uns" to "Keiner von uns",
    "Kennst du die Essensvorlieben deines Partners?" to "Kennst du die Essensvorlieben deines Partners?",
    "Kino" to "Kino",
    "Kirchlich" to "Kirchlich",
    "Klassisch Solitär" to "Klassisch Solitär",
    "Klassisch gebunden" to "Klassisch gebunden",
    "Klein & zart" to "Klein & zart",
    "Kleine Geschenke" to "Small gifts",
    "Kleine Runde" to "Kleine Runde",
    "Kochen und Freunde einladen" to "Kochen und Freunde einladen",
    "Kochkurs" to "Kochkurs",
    "Kommt auf den Tag an" to "Kommt auf den Tag an",
    "Kommt drauf an" to "Kommt drauf an",
    "Kommt mit" to "Comes with us",
    "Konzert" to "Konzert",
    "Kräftige Farben" to "Kräftige Farben",
    "Kräuterbeet" to "Kräuterbeet",
    "Kultur & Sehenswürdigkeiten" to "Culture & Sights",
    "Kuscheln" to "Cuddling",
    "Kuss senden" to "Send a kiss",
    "Körperliche Annäherung" to "Physical approach",
    "Körperliche Nähe" to "Körperliche Nähe",
    "Küche" to "Küche",
    "Land" to "Countryside",
    "Landhaus" to "Landhaus",
    "Landhausstil" to "Landhausstil",
    "Lange wach bleiben" to "Lange wach bleiben",
    "Lappland" to "Lappland",
    "Lappland, Finnland" to "Lappland, Finnland",
    "Las Vegas" to "Las Vegas",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein",
    "Lehne ab" to "Lehne ab",
    "Leidenschaft" to "Passion",
    "Liebe sie, macht mehr Spaß" to "Liebe sie, macht mehr Spaß",
    "Lieber durchgeplant oder spontan?" to "Rather fully planned or spontaneous?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Lieber ein ruhiger Abend zu zweit oder unter Leuten?",
    "Lieber nicht" to "Prefer not to",
    "Lieber vorher grob absprechen" to "Lieber vorher grob absprechen",
    "London" to "London",
    "London, England" to "London, England",
    "Lügen" to "Lügen",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Would you prefer a public or private proposal?",
    "Malediven" to "Malediven",
    "Man sollte nie streitend einschlafen." to "Man sollte nie streitend einschlafen.",
    "Mango Sorbet" to "Mango Sorbet",
    "Markant & breit" to "Markant & breit",
    "Mediterraner Innenhof" to "Mediterraner Innenhof",
    "Mehr Unterstützung" to "More support",
    "Mehr gemeinsame Zeit" to "More time together",
    "Mehr zuhören" to "Listen more",
    "Mehrgenerationenhaus" to "Mehrgenerationenhaus",
    "Mein Arbeitsplatz" to "Mein Arbeitsplatz",
    "Mein Partner" to "Mein Partner",
    "Mich überraschen" to "Surprise me",
    "Minimalistisches Interieur" to "Minimalistisches Interieur",
    "Missverständnisse" to "Missverständnisse",
    "Mit Familie und engen Freunden" to "Mit Familie und engen Freunden",
    "Mit Kompromissen" to "With compromises",
    "Mittelweg mit besonderen Details" to "Mittelweg mit besonderen Details",
    "Modern geometrisch" to "Modern geometrisch",
    "Moderne Grillstation" to "Moderne Grillstation",
    "Moderner Name" to "Modern name",
    "Moderner Solitär" to "Moderner Solitär",
    "Moissanit" to "Moissanit",
    "Momente" to "Moments",
    "Monaco" to "Monaco",
    "Moralische Werte" to "Moral values",
    "Museum" to "Museum",
    "Musik" to "Musik",
    "Mädchen" to "Girl",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Are you sure you want to leave? Your progress will be saved.",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Would you like pets to be present during the proposal?",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "We might need to make budget cutbacks",
    "Müssen es planen" to "We have to plan it",
    "Müssen sparen" to "We have to save",
    "Name Partnerin" to "Partner's name",
    "Namen und Startdatum eurer Beziehung." to "Your names and relationship start date.",
    "Natursteinfassade" to "Natursteinfassade",
    "Naturteich" to "Natural pond",
    "Nein, einfach halten" to "No, keep it simple",
    "Nein, erstmal privat halten" to "Nein, erstmal privat halten",
    "Nein, lieber vor Ort" to "No, prefer local",
    "Nein, modern halten" to "No, keep it modern",
    "Nein, nur wir" to "No, just us",
    "Nein, zu ablenkend" to "Nein, zu ablenkend",
    "Neubau mit Smart Home" to "Modern smart home building",
    "Neubau mit Technik" to "Neubau mit Technik",
    "Neues Hobby" to "New hobby",
    "Neues Spiel" to "New game",
    "New York" to "New York",
    "New York, USA" to "New York, USA",
    "Nicht mein Fall" to "Not my thing",
    "Nicht nötig, lieber klassisch bleiben" to "Not necessary, prefer to keep it classic",
    "Nichts — es passt so" to "Nichts — es passt so",
    "Niemand" to "Nobody",
    "Niemand ohne Plan" to "Niemand ohne Plan",
    "Nizza" to "Nizza",
    "Nur bei wichtigen Themen" to "Nur bei wichtigen Themen",
    "Nur wir beide" to "Nur wir beide",
    "Obstgarten" to "Obstgarten",
    "Oder" to "Or",
    "Offene Küche" to "Offene Küche",
    "Offene Wohnküche" to "Offene Wohnküche",
    "Ohne Stein" to "Ohne Stein",
    "Open End" to "Open end",
    "Outdoor-Küche" to "Outdoor-Küche",
    "Outdoor-Sofa" to "Outdoor-Sofa",
    "Outdoor-Whirlpool" to "Outdoor-Whirlpool",
    "Ovaler Diamant" to "Ovaler Diamant",
    "Paar" to "Pair",
    "Paar-Statistiken" to "Couple statistics",
    "Paris" to "Paris",
    "Paris, Frankreich" to "Paris, France",
    "Partner" to "Partner",
    "Partner-Simulator" to "Partner simulator",
    "Partnerin" to "Partner",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Does a pet fit into our daily routine at all?",
    "Pasta" to "Pasta",
    "Pastell" to "Pastell",
    "Penthouse mit Ausblick" to "Penthouse mit Ausblick",
    "Pergola mit Lounge" to "Pergola mit Lounge",
    "Pfingstrosen" to "Pfingstrosen",
    "Pinguin" to "Pinguin",
    "Pistazie" to "Pistazie",
    "Pizza" to "Pizza",
    "Pizzaofen" to "Pizzaofen",
    "Platin" to "Platin",
    "Pool" to "Pool",
    "Pop" to "Pop",
    "Prasselnder Kamin" to "Prasselnder Kamin",
    "Privater Innenhof" to "Privater Innenhof",
    "Profil" to "Profile",
    "Prozentual nach Einkommen" to "Proportional to income",
    "Quiz verlassen?" to "Leave quiz?",
    "Rausgehen in die Natur" to "Rausgehen in die Natur",
    "Reden vor ..." to "Talk before ...",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Schedule regular date nights or quality time together",
    "Reisen" to "Travel",
    "Reiseziele" to "Travel destinations",
    "Respektlosigkeit" to "Respektlosigkeit",
    "Restaurant" to "Restaurant",
    "RnB / Soul" to "RnB / Soul",
    "Rock" to "Rock",
    "Rom" to "Rome",
    "Rom, Italien" to "Rome, Italy",
    "Romantik" to "Romance",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich.",
    "Romantische Stimmung" to "Romantic mood",
    "Roségold" to "Roségold",
    "Ruhig zu zweit" to "Ruhig zu zweit",
    "Runder Diamant" to "Runder Diamant",
    "Salted Caramel" to "Salted Caramel",
    "Santorini" to "Santorini",
    "Santorini, Griechenland" to "Santorini, Griechenland",
    "Saphir" to "Saphir",
    "Saunahaus" to "Saunahaus",
    "Schickes Restaurant oder Hotel" to "Schickes Restaurant oder Hotel",
    "Schlafzimmer" to "Schlafzimmer",
    "Schließen" to "Close",
    "Schmal & zart" to "Schmal & zart",
    "Schokolade" to "Schokolade",
    "Schreib frei, was dir wirklich dazu einfällt." to "Write what truly comes to mind.",
    "Schreibe deine eigene Antwort" to "Write your own answer",
    "Sehr gerne" to "Very much",
    "Sehr leicht" to "Sehr leicht",
    "Sehr wichtig — Fotos und Video" to "Sehr wichtig — Fotos und Video",
    "Sehr wichtig, es sollte persönlich sein" to "Very important, it should be personal",
    "Selbst kochen" to "Selbst kochen",
    "Separate Küche" to "Separate Küche",
    "Serie schauen" to "Serie schauen",
    "Serienmarathon auf dem Sofa" to "Serienmarathon auf dem Sofa",
    "Sex & Liebe" to "Sex & Love",
    "Seychellen" to "Seychellen",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Are we able to cover all costs for a child/children? 💰",
    "Soll der Antrag eine Überraschung sein?" to "Should the proposal be a surprise?",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "Should the proposal include cultural or traditional elements?",
    "Sommerhochzeit" to "Sommerhochzeit",
    "Sonnige Dachterrasse" to "Sonnige Dachterrasse",
    "Sowohl als auch" to "Both",
    "Spazieren" to "Spazieren",
    "Spaß & Abenteuer" to "Fun & Adventure",
    "Speichern" to "Save",
    "Spiel bearbeiten" to "Edit game",
    "Spielbereich für Kinder" to "Spielbereich für Kinder",
    "Spiele spielen und Spaß haben" to "Spiele spielen und Spaß haben",
    "Spontan" to "Spontaneous",
    "Sportplatz" to "Sportplatz",
    "Sprache" to "Language",
    "Stadt" to "City",
    "Stadt oder Land — was ist uns wichtiger?" to "City or countryside — which is more important to us?",
    "Stadtvilla" to "Stadtvilla",
    "Standesamt & Party" to "Standesamt & Party",
    "Statement-Ring" to "Statement-Ring",
    "Stilvolles Outdoor-Sofa" to "Stilvolles Outdoor-Sofa",
    "Stimme voll zu" to "Stimme voll zu",
    "Stimmt" to "Agree",
    "Stimmt nicht" to "Disagree",
    "Stimmt, noch nie" to "Stimmt, noch nie",
    "Stracciatella" to "Stracciatella",
    "Strandtag" to "Strandtag",
    "Streit über Haushalt" to "Arguments about household",
    "Ständig" to "Ständig",
    "Sushi" to "Sushi",
    "Süß" to "Süß",
    "Teile alle deine Hobbys mit deinem Partner" to "Teile alle deine Hobbys mit deinem Partner",
    "Teils teils" to "Somewhat agree",
    "Testen" to "Test",
    "Tiefe Gespräche" to "Deep conversations",
    "Tiefgründige Gespräche führen" to "Tiefgründige Gespräche führen",
    "Tierpension" to "Pet boarding",
    "Tiny House" to "Tiny House",
    "Titel" to "Title",
    "Tokyo, Japan" to "Tokyo, Japan",
    "Traditioneller Name" to "Traditional name",
    "Tägliche Aktivität" to "Daily activity",
    "Uns auseinanderzuleben" to "Uns auseinanderzuleben",
    "Unser erstes Treffen" to "Unser erstes Treffen",
    "Unsere Gesichter" to "Unsere Gesichter",
    "Unsere nächste Reise" to "Unsere nächste Reise",
    "Unter 1000" to "Under 1000",
    "Unter 1000 im Monat" to "Under 1000 a month",
    "Unter 50€/Monat" to "Under 50€/month",
    "Unter Leuten" to "Unter Leuten",
    "Untreue" to "Untreue",
    "Urlaub" to "Vacation",
    "Vanille" to "Vanille",
    "Venedig" to "Venedig",
    "Venedig, Italien" to "Venedig, Italien",
    "Verbindung" to "Connection",
    "Verbringe die Feiertage mit deiner Familie" to "Spend the holidays with your family",
    "Vertrautheit" to "Vertrautheit",
    "Viel getrennt" to "A lot apart",
    "Vielleicht ein oder zwei" to "Vielleicht ein oder zwei",
    "Vielleicht, aber mündlich reicht" to "Maybe, but verbal is enough",
    "Vielleicht, wenn es machbar ist" to "Maybe, if it works out",
    "Vielleicht, wenn es passt" to "Maybe, if it fits",
    "Vintage Art déco" to "Vintage Art déco",
    "Vintage verspielt" to "Vintage verspielt",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Von deinem Partner in neue Hobbys eingeführt werden",
    "Vor dem Kauf eines Hauses besprechen" to "Discuss before buying a house",
    "Vor der Anschaffung eines Haustiers besprechen" to "Discuss before getting a pet",
    "Vor der gemeinsamen Reise besprechen" to "Discuss before travelling together",
    "Vor nichts" to "Vor nichts",
    "Vorlieben für den Antrag" to "Proposal preferences",
    "Vorort" to "Suburb",
    "Walnuss" to "Walnuss",
    "Wandern" to "Wandern",
    "Wann fühlst du dich mir am nächsten?" to "Wann fühlst du dich mir am nächsten?",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Wann fühlst du dich mir körperlich am nächsten?",
    "Was bedeutet Vertrauen für dich konkret?" to "Was bedeutet Vertrauen für dich konkret?",
    "Was entspannt dich mehr?" to "Was entspannt dich mehr?",
    "Was fehlt dir über die Distanz am meisten?" to "Was fehlt dir über die Distanz am meisten?",
    "Was gefällt dir an deinem Zuhause am besten?" to "What do you like most about your home?",
    "Was hast du von deinem Partner gelernt?" to "Was hast du von deinem Partner gelernt?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "What do you think of props (e.g. signs, balloons, etc.)?",
    "Was ist das Wichtigste beim Antrag?" to "What is the most important thing about the proposal?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Was ist dein Lieblingsfoto von uns? 📸",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Was ist deine größte Angst vor dem Zusammenleben?",
    "Was ist für dich ein absoluter Dealbreaker?" to "Was ist für dich ein absoluter Dealbreaker?",
    "Was ist für jeden von uns das absolute Highlight?" to "What is the absolute highlight for each of us?",
    "Was ist passiert?" to "What happened?",
    "Was macht einen Moment für dich romantisch?" to "Was macht einen Moment für dich romantisch?",
    "Was magst du an deinem Partner am liebsten?" to "Was magst du an deinem Partner am liebsten?",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Was magst du lieber: früh aufstehen oder lange wach bleiben?",
    "Was magst du lieber?" to "Which do you prefer?",
    "Was möchtest du, dass dein Partner öfter tut?" to "Was möchtest du, dass dein Partner öfter tut?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "What happens to the pet when we travel?",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "What do you hope our child becomes when they grow up?",
    "Was war dein schönster Moment mit mir bisher?" to "Was war dein schönster Moment mit mir bisher?",
    "Was wir gegessen haben" to "Was wir gegessen haben",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Was würdest du an einem gemeinsamen Tag am liebsten machen?",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "What would you change immediately if money were no object?",
    "Weiter" to "Next",
    "Weiter spielen" to "Keep playing",
    "Weiß ich noch nicht" to "I don't know yet",
    "Weiße Rosen" to "Weiße Rosen",
    "Weißgold" to "Weißgold",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "What kind of setting would you wish for a proposal?",
    "Welcher Moment war für dich der Anfang von „uns\\" to "Welcher Moment war für dich der Anfang von „uns\\",
    "Welcher Raum sagt am meisten über dich aus?" to "Which room says the most about you?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "What budget do we plan for food and vet costs?",
    "Welches Lied macht dich an? 🥵" to "Welches Lied macht dich an? 🥵",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Welches gemeinsame Foto ist dein Lieblingsfoto?",
    "Wellnessbad" to "Wellnessbad",
    "Wenn es schwierig ist" to "Wenn es schwierig ist",
    "Wenn ich müde bin" to "Wenn ich müde bin",
    "Wenn wir uns lange umarmen" to "Wenn wir uns lange umarmen",
    "Wenn wir zusammen lachen" to "Wenn wir zusammen lachen",
    "Wer findet die besten Restaurants?" to "Wer findet die besten Restaurants?",
    "Wer gibt mehr Herzlichkeit?" to "Wer gibt mehr Herzlichkeit?",
    "Wer hat den besseren Musikgeschmack?" to "Wer hat den besseren Musikgeschmack?",
    "Wer hängt mehr an seinen Eltern?" to "Wer hängt mehr an seinen Eltern?",
    "Wer ist besser organisiert?" to "Wer ist besser organisiert?",
    "Wer ist der Beste bei der Filmauswahl?" to "Wer ist der Beste bei der Filmauswahl?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Wer ist der Beste bei der Planung romantischer Dates?",
    "Wer ist der beste Tänzer?" to "Wer ist der beste Tänzer?",
    "Wer ist romantischer?" to "Wer ist romantischer?",
    "Wer kocht besser?" to "Wer kocht besser?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Who handles renovations and maintenance?",
    "Wer vergisst eher einen Jahrestag?" to "Wer vergisst eher einen Jahrestag?",
    "Wer würde eher auf einer Party als Erster einschlafen?" to "Wer würde eher auf einer Party als Erster einschlafen?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Wer würde eher bei einem Streit als Erstes einlenken?",
    "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?" to "Wer würde eher eine Flasche öffnen, ohne einen Flaschenöffner zu benutzen?",
    "Wer würde eher spontan eine Reise buchen?" to "Wer würde eher spontan eine Reise buchen?",
    "Wer würde eher zu spät kommen?" to "Wer würde eher zu spät kommen?",
    "Wer würde eher?" to "Who's more likely?",
    "Wer übernimmt die tägliche Versorgung?" to "Who will handle daily care?",
    "Werde so akzeptiert, wie du bist" to "Werde so akzeptiert, wie du bist",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Will we have enough time for the child/children? ⌛",
    "Whirlpool" to "Whirlpool",
    "White Chocolate" to "White Chocolate",
    "Widgets" to "Widgets",
    "Wie fühlst du dich am meisten geliebt?" to "Wie fühlst du dich am meisten geliebt?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Wie gehen wir mit unterschiedlichen Einkommen um?",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Wie kann dein Partner am besten Sex mit dir initiieren?",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Wie kann dein Partner ein noch besserer Partner für dich sein?",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "How long after the proposal would you like to celebrate with others?",
    "Wie lange wollen wir dort mindestens bleiben?" to "How long do we plan to stay there at minimum?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Wie leicht fällt es dir, über Wünsche zu sprechen?",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "How do you want our future to look?",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "What does your perfect Sunday at home look like?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Wie stehst du zu schmutzigem Gerede beim Sex?",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "How much mortgage can we realistically afford?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "How much time do we want to spend apart?",
    "Wie viel wollen wir insgesamt ausgeben?" to "How much do we want to spend in total?",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "How will we find time for our relationship when the baby arrives?",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "How important is it to you that the moment is captured?",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?",
    "Wie würdest du sie/ihn nennen?" to "What would you name him/her?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?",
    "Wildblumen" to "Wildblumen",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Do you want a girl or a boy? 👶",
    "Wintergarten" to "Wintergarten",
    "Winterhochzeit" to "Winterhochzeit",
    "Wir entscheiden es gemeinsam" to "Wir entscheiden es gemeinsam",
    "Wir treffen uns in der Mitte" to "Wir treffen uns in der Mitte",
    "Wird stressig" to "It will be stressful",
    "Wobei lachst du am meisten?" to "Wobei lachst du am meisten?",
    "Wofür sparen wir gemeinsam?" to "Wofür sparen wir gemeinsam?",
    "Wohnzimmer" to "Wohnzimmer",
    "Woran erinnerst du dich am lebhaftesten?" to "Woran erinnerst du dich am lebhaftesten?",
    "Worauf freust du dich bei uns am meisten?" to "Worauf freust du dich bei uns am meisten?",
    "Worte/Komplimente" to "Words/Compliments",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "Wovor hast du in unserer Beziehung am meisten Angst?",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Would you prefer a proposal on vacation (combined with travel)?",
    "Zeichne mich als Tier — welches wäre ich?" to "Zeichne mich als Tier — welches wäre ich?",
    "Zeichne unser Gefühl zueinander als Symbol." to "Zeichne unser Gefühl zueinander als Symbol.",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?",
    "Zeichnen" to "Draw",
    "Zeit, wenn das Baby schläft" to "Time when the baby sleeps",
    "Zelten gehen" to "Zelten gehen",
    "Zitrone" to "Zitrone",
    "Zu Hause, gemütlich und privat" to "Zu Hause, gemütlich und privat",
    "Zu einem Picknick gehen" to "Zu einem Picknick gehen",
    "Zu einem ausgefallenen Abendessen gehen" to "Zu einem ausgefallenen Abendessen gehen",
    "Zu zweit reisen" to "Travel as a couple",
    "Zuhause & Alltag" to "Home & everyday life",
    "Zuhören" to "Listen",
    "Zurück" to "Back",
    "Zusammen seit" to "Together since",
    "Zusammenziehen" to "Zusammenziehen",
    "Zustimmen oder Ablehnen" to "Agree or Disagree",
    "Zwei Kreise, die sich überschneiden" to "Zwei Kreise, die sich überschneiden",
    "Zwei Stühle davor" to "Zwei Stühle davor",
    "Zärtlich sein" to "Be affectionate",
    "aufwaermen" to "aufwaermen",
    "custom_gourmet_eissorten" to "custom_gourmet_eissorten",
    "dasoderdas" to "This or That",
    "disney" to "disney",
    "entertainment" to "entertainment",
    "familie" to "Family",
    "games" to "games",
    "harrypotter" to "harrypotter",
    "hochzeit" to "Wedding",
    "ichhabenochnie" to "ichhabenochnie",
    "kinder" to "Children",
    "oder" to "or",
    "parks" to "parks",
    "party" to "party",
    "reden" to "Discussion",
    "reisen" to "Travel",
    "tot" to "tot",
    "universal" to "universal",
    "unterhaltung" to "Entertainment",
    "wer" to "wer",
    "werwuerde" to "werwuerde",
    "zuhause" to "zuhause",
    "{partner}" to "{partner}",
    "{user}" to "{user}",
    "Öfter als ich zugebe" to "Öfter als ich zugebe",
    "Über 100€/Monat" to "Over 100€/month",
    "Über 2000 im Monat" to "Over 2000 a month",
    "Über mich selbst" to "Über mich selbst",
    "Übernehmen" to "Save",
    "Überraschend" to "Surprising",
    "Überraschung" to "Überraschung",
    "Überspringen" to "Skip",
    "Übertrieben und großartig" to "Übertrieben und großartig",
    "☀️" to "☀️",
    "✎ Tippe, um zu antworten" to "✎ Tap to answer",
    "❤️" to "❤️")