package com.example.ui

/** Exact, reviewed English copy for every built-in and generated Harmony content item. */
internal val EXACT_ENGLISH_CONTENT: Map<String, String> = mapOf(
    "Tiere" to "Animals",
    // Categories, topics and shared labels
    "Wer würde eher?" to "Who's more likely?",
    "Zeichnen" to "Drawing",
    "Das oder das?" to "This or That?",
    "Das oder das" to "This or That",
    "Zustimmen oder Ablehnen" to "Agree or Disagree",
    "Ich habe noch nie" to "Never Have I Ever",
    "Was magst du lieber?" to "Which Do You Prefer?",
    "Antwort mit einem Foto" to "Answer with a Photo",
    "Tiefe Gespräche" to "Deep Conversations",
    "Reden vor ..." to "Talk Before...",
    "Aufwärmen" to "Warm-up",
    "Beziehung" to "Relationship",
    "Sex & Liebe" to "Sex & Love",
    "Moralische Werte" to "Moral Values",
    "Geld & Finanzen" to "Money & Finances",
    "Einander kennenlernen" to "Getting to Know Each Other",
    "Reisen" to "Travel",
    "Familie" to "Family",
    "Hobbys" to "Hobbies",
    "unterhaltung" to "Entertainment",
    "dasoderdas" to "This or That",
    "hochzeit" to "Wedding",
    "kinder" to "Children",
    "reden" to "Discussion",
    "reisen" to "Travel",
    "familie" to "Family",

    // Home & everyday life
    "Zuhause & Alltag" to "Home & Everyday Life",
    "Was gefällt dir an deinem Zuhause am besten?" to "What do you like most about your home?",
    "Die Gemütlichkeit und Ruhe" to "The comfort and peace",
    "Dass alles meinen Stil hat" to "That everything reflects my style",
    "Die Menschen, die darin wohnen" to "The people who live there",
    "Der Blick nach draußen" to "The view outside",
    "Welcher Raum sagt am meisten über dich aus?" to "Which room says the most about you?",
    "Küche" to "Kitchen",
    "Schlafzimmer" to "Bedroom",
    "Wohnzimmer" to "Living room",
    "Mein Arbeitsplatz" to "My workspace",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "What would you change immediately if money were no object?",
    "Größere Küche" to "A larger kitchen",
    "Ein Balkon oder Garten" to "A balcony or garden",
    "Bessere Lage" to "A better location",
    "Nichts — es passt so" to "Nothing — it's perfect as it is",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "What does your perfect Sunday at home look like?",
    "Ausschlafen und nichts tun" to "Sleeping in and doing nothing",
    "Kochen und Freunde einladen" to "Cooking and inviting friends over",
    "Serienmarathon auf dem Sofa" to "A TV marathon on the sofa",
    "Aufräumen und Projekte angehen" to "Tidying up and tackling projects",

    // Proposal
    "Der perfekte Heiratsantrag" to "The Perfect Proposal",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "What setting would you want for a proposal?",
    "Zu Hause, gemütlich und privat" to "At home, cozy and private",
    "Draußen mit der Natur als Kulisse" to "Outdoors with nature as the backdrop",
    "Schickes Restaurant oder Hotel" to "An elegant restaurant or hotel",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Would you prefer a public or private proposal?",
    "Nur wir beide" to "Just the two of us",
    "Mit Familie und engen Freunden" to "With family and close friends",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "In a public place with lots of people watching",
    "Soll der Antrag eine Überraschung sein?" to "Should the proposal be a surprise?",
    "Ja, komplett überraschend" to "Yes, a complete surprise",
    "Lieber vorher grob absprechen" to "I'd rather discuss the basics beforehand",
    "Wir entscheiden es gemeinsam" to "We'll decide together",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "How important is it to you that the moment is captured?",
    "Sehr wichtig — Fotos und Video" to "Very important — photos and video",
    "Ein paar Handyfotos reichen" to "A few phone photos are enough",
    "Gar nicht, der Moment gehört uns" to "Not at all — the moment is ours",
    "Vorlieben für den Antrag" to "Proposal Preferences",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Would you prefer an extravagant proposal or something understated?",
    "Übertrieben und großartig" to "Over-the-top and spectacular",
    "Mittelweg mit besonderen Details" to "A balanced approach with special details",
    "Einfach und intim" to "Simple and intimate",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "What do you think about props, such as signs or balloons?",
    "Liebe sie, macht mehr Spaß" to "I love them — they make it more fun",
    "Vielleicht ein oder zwei" to "Maybe one or two",
    "Nein, zu ablenkend" to "No, they're too distracting",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Would you want the moment shared on social media right away?",
    "Ja, sofort teilen" to "Yes, share it right away",
    "Nein, erstmal privat halten" to "No, keep it private at first",
    "Erst nur enge Freunde/Familie" to "Close friends and family first",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "How important is it that the proposal reflects your hobbies or interests?",
    "Sehr wichtig, es sollte persönlich sein" to "Very important — it should feel personal",
    "Etwas, eine kleine Note wäre schön" to "Somewhat — a small personal touch would be lovely",
    "Nicht nötig, lieber klassisch bleiben" to "Not necessary — I'd prefer to keep it classic",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Would you prefer a proposal while on vacation?",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Yes, in an exciting city or at a landmark",
    "Vielleicht, wenn es machbar ist" to "Maybe, if it's practical",
    "Nein, lieber vor Ort" to "No, I'd rather stay local",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "How soon after the proposal would you want to celebrate with others?",
    "Am selben Tag mit Freunden/Familie" to "The same day with friends and family",
    "Etwa eine Woche später, erst mal nur wir" to "About a week later — just us at first",
    "Keine Party nötig, privat halten" to "No party needed — keep it private",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Would you like a handwritten letter as part of the proposal?",
    "Ja, etwas zum Lesen und Aufbewahren" to "Yes, something to read and keep",
    "Vielleicht, aber mündlich reicht" to "Maybe, but spoken words are enough",
    "Nein, einfach halten" to "No, keep it simple",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "Should the proposal include cultural or traditional elements?",
    "Ja, Traditionen einbinden" to "Yes, include traditions",
    "Ein paar kulturelle Anklänge sind okay" to "A few cultural touches would be nice",
    "Nein, modern halten" to "No, keep it modern",
    "Was ist das Wichtigste beim Antrag?" to "What matters most in a proposal?",
    "Die Umgebung und Atmosphäre" to "The setting and atmosphere",
    "Die Worte und Emotionen" to "The words and emotions",
    "Der Ring und die Geste" to "The ring and the gesture",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Would you want pets to be part of the proposal?",
    "Ja, sie gehören zur Familie!" to "Yes, they're part of the family!",
    "Vielleicht, wenn es passt" to "Maybe, if it feels right",
    "Nein, nur wir" to "No, just us",

    // Discussion packs
    "Diskutiere vor dem Kinderkriegen" to "Discuss Before Having Children",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Can we afford all the costs of one or more children? 💰",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "We may need to make some savings",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Will we have enough time for our child or children? ⏳",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Yes, we'll make sure family time comes first.",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "How will we make time for our relationship once the baby arrives?",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Plan regular dates or quality time together",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "What would you like our future to look like?",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Travel the world together and explore new cultures and cuisines",
    "Wie würdest du sie/ihn nennen?" to "What would you name them?",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Would you prefer a girl or a boy? 👶",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "What do we hope our child will become as an adult?",
    "Vor der Anschaffung eines Haustiers besprechen" to "Discuss Before Getting a Pet",
    "Wer übernimmt die tägliche Versorgung?" to "Who will handle the daily care?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "What happens to the pet when we travel?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "What budget should we plan for food and veterinary care?",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Does a pet truly fit our lifestyle?",
    "Vor der gemeinsamen Reise besprechen" to "Discuss Before Traveling Together",
    "Wie viel wollen wir insgesamt ausgeben?" to "How much do we want to spend in total?",
    "Lieber durchgeplant oder spontan?" to "Carefully planned or spontaneous?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "How much time do we want to spend apart?",
    "Was ist für jeden von uns das absolute Highlight?" to "What is the absolute highlight for each of us?",
    "Vor dem Kauf eines Hauses besprechen" to "Discuss Before Buying a Home",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "How much of a mortgage can we realistically afford?",
    "Stadt oder Land — was ist uns wichtiger?" to "City or countryside — which matters more to us?",
    "Wie lange wollen wir dort mindestens bleiben?" to "How long do we want to stay there at minimum?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Who will handle renovations and maintenance?",

    // This or That packs
    "Reiseziele" to "Travel Destinations",
    "Paris, Frankreich" to "Paris, France", "Rom, Italien" to "Rome, Italy",
    "Bali, Indonesien" to "Bali, Indonesia", "Santorini, Griechenland" to "Santorini, Greece",
    "London, England" to "London, England", "New York, USA" to "New York, USA",
    "Malediven" to "Maldives", "Seychellen" to "Seychelles",
    "Tokyo, Japan" to "Tokyo, Japan", "Dubai, VAE" to "Dubai, UAE",
    "Venedig, Italien" to "Venice, Italy", "Amsterdam, Niederlande" to "Amsterdam, Netherlands",
    "Lappland, Finnland" to "Lapland, Finland", "Island" to "Iceland",
    "Unser Traumhaus" to "Our Dream Home",
    "Altbau mit Charme" to "Charming Period Home", "Neubau mit Smart Home" to "New Smart Home",
    "Offene Wohnküche" to "Open-plan Kitchen", "Separate Küche" to "Separate Kitchen",
    "Prasselnder Kamin" to "Crackling Fireplace", "Fußbodenheizung" to "Underfloor Heating",
    "Großer Garten" to "Large Garden", "Sonnige Dachterrasse" to "Sunny Roof Terrace",
    "Stadtvilla" to "City Villa", "Landhaus" to "Country House",
    "Glasfassade" to "Glass Façade", "Natursteinfassade" to "Natural-stone Façade",
    "Penthouse mit Ausblick" to "Penthouse with a View", "Haus am See" to "Lakeside Home",
    "Minimalistisches Interieur" to "Minimalist Interior", "Landhausstil" to "Country Style",
    "Bibliothek" to "Library", "Heimkino" to "Home Cinema",
    "Innenpool" to "Indoor Pool", "Wellnessbad" to "Spa Bathroom",
    "Große Fensterfront" to "Floor-to-ceiling Windows", "Privater Innenhof" to "Private Courtyard",
    "Tiny House" to "Tiny House", "Mehrgenerationenhaus" to "Multigenerational Home",
    "Traumhaus Außenbereich" to "Dream Home: Outdoor Space",
    "Großer Außenpool" to "Large Outdoor Pool", "Outdoor-Whirlpool" to "Outdoor Hot Tub",
    "Moderne Grillstation" to "Modern Barbecue Station", "Gemütliche Feuerstelle" to "Cozy Fire Pit",
    "Eigenes Gemüsebeet" to "Private Vegetable Garden", "Bunte Blumenwiese" to "Colorful Wildflower Meadow",
    "Entspannte Hängematte" to "Relaxing Hammock", "Stilvolles Outdoor-Sofa" to "Stylish Outdoor Sofa",
    "Infinity-Pool" to "Infinity Pool", "Naturteich" to "Natural Pond",
    "Outdoor-Küche" to "Outdoor Kitchen", "Pizzaofen" to "Pizza Oven",
    "Pergola mit Lounge" to "Pergola with Lounge", "Wintergarten" to "Conservatory",
    "Kräuterbeet" to "Herb Garden", "Obstgarten" to "Orchard",
    "Dachgarten mit Lounge" to "Roof Garden with Lounge", "Mediterraner Innenhof" to "Mediterranean Courtyard",
    "Feuerstelle" to "Fire Pit", "Außenkamin" to "Outdoor Fireplace",
    "Spielbereich für Kinder" to "Children's Play Area", "Sportplatz" to "Sports Court",
    "Gewächshaus" to "Greenhouse", "Saunahaus" to "Sauna House",
    "Aktivitäten" to "Activities",
    "Wandern" to "Hiking", "Strandtag" to "Beach Day", "Konzert" to "Concert", "Kino" to "Cinema",
    "Kochkurs" to "Cooking Class", "Restaurant" to "Restaurant", "Museum" to "Museum", "Freizeitpark" to "Theme Park",
    "Essensvorlieben" to "Food Preferences",
    "Pizza" to "Pizza", "Pasta" to "Pasta", "Sushi" to "Sushi", "Burger" to "Burger",
    "Süß" to "Sweet", "Herzhaft" to "Savory", "Selbst kochen" to "Cook at Home", "Bestellen" to "Order In",
    "Verlobungsringe" to "Engagement Rings",
    "Klassisch Solitär" to "Classic Solitaire", "Vintage verspielt" to "Playful Vintage",
    "Gelbgold" to "Yellow Gold", "Weißgold" to "White Gold",
    "Großer Stein" to "Large Stone", "Filigran & schlicht" to "Delicate & Simple",
    "Diamant" to "Diamond", "Farbedelstein" to "Colored Gemstone",
    "Platin" to "Platinum", "Roségold" to "Rose Gold",
    "Drei-Stein-Ring" to "Three-stone Ring", "Moderner Solitär" to "Modern Solitaire",
    "Ovaler Diamant" to "Oval Diamond", "Runder Diamant" to "Round Diamond",
    "Schmal & zart" to "Slim & Delicate", "Markant & breit" to "Bold & Wide",
    "Moissanit" to "Moissanite", "Saphir" to "Sapphire",
    "Vintage Art déco" to "Vintage Art Deco", "Modern geometrisch" to "Modern Geometric",
    "Gravur innen" to "Inside Engraving", "Diamanten im Band" to "Diamonds in the Band",
    "Ohne Stein" to "No Stone", "Statement-Ring" to "Statement Ring",
    "Hochzeitssträuße" to "Wedding Bouquets",
    "Weiße Rosen" to "White Roses", "Pfingstrosen" to "Peonies", "Wildblumen" to "Wildflowers",
    "Klassisch gebunden" to "Classic Hand-tied", "Groß & üppig" to "Large & Lush",
    "Klein & zart" to "Small & Delicate", "Pastell" to "Pastels", "Kräftige Farben" to "Bold Colors",
    "Traumhochzeit" to "Dream Wedding", "Große Feier" to "Large Celebration", "Kleine Runde" to "Intimate Gathering",
    "Am Strand" to "On the Beach", "In den Bergen" to "In the Mountains", "Kirchlich" to "Church Ceremony",
    "Standesamt & Party" to "Civil Ceremony & Party", "Sommerhochzeit" to "Summer Wedding", "Winterhochzeit" to "Winter Wedding",

    // Warm-up and relationship quizzes
    "Fragen für jede Gelegenheit" to "Questions for Any Occasion",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Which do you prefer: getting up early or staying up late?",
    "Früh aufstehen" to "Getting up early", "Lange wach bleiben" to "Staying up late", "Kommt auf den Tag an" to "It depends on the day",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Would you rather have a quiet evening together or be around other people?",
    "Ruhig zu zweit" to "A quiet evening together", "Unter Leuten" to "Around other people", "Gemischt" to "A mix of both",
    "Was entspannt dich mehr?" to "What helps you relax most?", "Musik" to "Music", "Spazieren" to "Going for a walk",
    "Serie schauen" to "Watching a series", "Gar nichts tun" to "Doing absolutely nothing",
    "Wobei lachst du am meisten?" to "What makes you laugh the most?", "Bei Insider-Witzen" to "Inside jokes",
    "Bei Memes" to "Memes", "Wenn ich müde bin" to "When I'm tired", "Über mich selbst" to "Myself",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Snapshots from Our Love Story",
    "Welcher Moment war für dich der Anfang von „uns\"?" to "Which moment felt like the beginning of us?",
    "Unser erstes Gespräch" to "Our first conversation", "Das erste Treffen" to "Our first date",
    "Der erste Kuss" to "Our first kiss", "Als es einfach klar war" to "When it simply felt clear",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Which photo of us is your favorite?",
    "Das erste Selfie" to "Our first selfie", "Ein Urlaubsfoto" to "A vacation photo",
    "Ein zufälliger Schnappschuss" to "A candid snapshot", "Eins, das nur wir kennen" to "One only we know",
    "Woran erinnerst du dich am lebhaftesten?" to "What do you remember most vividly?",
    "An einen Geruch" to "A scent", "An einen Song" to "A song", "An etwas, das ich gesagt habe" to "Something I said", "An das Gefühl" to "The feeling",
    "Aufwärmen: Einander kennenlernen" to "Warm-up: Getting to Know Each Other",
    "Was war dein schönster Moment mit mir bisher?" to "What has been your favorite moment with me so far?",
    "Unser erstes Treffen" to "Our first date", "Ein ganz normaler Alltagstag" to "An ordinary day together",
    "Eine gemeinsame Reise" to "A trip together", "Ein schwerer Moment, den wir geschafft haben" to "A difficult moment we overcame together",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "What would you most like to do on a day together?",
    "Ausschlafen und faulenzen" to "Sleep in and relax", "Etwas Neues ausprobieren" to "Try something new",
    "Rausgehen in die Natur" to "Get out into nature", "Freunde treffen" to "Meet up with friends",
    "Wie fühlst du dich am meisten geliebt?" to "What makes you feel most loved?",
    "Durch Worte" to "Words", "Durch Zeit zu zweit" to "Quality time together", "Durch Berührung" to "Physical touch", "Durch kleine Gesten" to "Small gestures",
    "Worauf freust du dich bei uns am meisten?" to "What are you most excited about for us?",
    "Unsere nächste Reise" to "Our next trip", "Zusammenziehen" to "Moving in together", "Einfach mehr Alltag" to "Simply sharing more everyday life", "Alles, was noch kommt" to "Everything still to come",
    "Wer würde eher zu spät kommen?" to "Who's more likely to arrive late?",
    "Ich" to "Me", "Mein Partner" to "My partner", "Beide gleich" to "Both equally", "Keiner von uns" to "Neither of us",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Who's more likely to make peace first after an argument?",
    "Kommt drauf an" to "It depends", "Wir treffen uns in der Mitte" to "We meet halfway",
    "Wer würde eher spontan eine Reise buchen?" to "Who's more likely to book a spontaneous trip?",
    "Beide zusammen" to "Both of us", "Niemand ohne Plan" to "Neither without a plan",
    "Wer vergisst eher einen Jahrestag?" to "Who's more likely to forget an anniversary?",
    "Keiner" to "Neither", "Beide, aber wir tun so als ob nicht" to "Both, but we pretend we didn't",

    // Never have I ever
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Never have I ever canceled a date to stay home.",
    "Stimmt, noch nie" to "True, never", "Doch, schon mal" to "Yes, I have", "Öfter als ich zugebe" to "More often than I'd admit",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Never have I ever secretly looked through my partner's phone.",
    "Einmal" to "Once", "Ich würde es nie tun" to "I would never do that",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Never have I ever rewritten a message ten times.",
    "Ständig" to "All the time", "Nur bei wichtigen Themen" to "Only for important topics",

    // Deep conversations, money and intimacy
    "Was bedeutet Vertrauen für dich konkret?" to "What does trust mean to you in practical terms?",
    "Dass ich alles erzählen kann" to "Being able to share everything", "Dass ich mich nicht sorgen muss" to "Not having to worry",
    "Dass Zusagen gehalten werden" to "Keeping promises", "Alles davon" to "All of the above",
    "Was ist für dich ein absoluter Dealbreaker?" to "What is an absolute dealbreaker for you?",
    "Lügen" to "Lying", "Respektlosigkeit" to "Disrespect", "Gleichgültigkeit" to "Indifference", "Untreue" to "Cheating",
    "Wann fühlst du dich mir am nächsten?" to "When do you feel closest to me?",
    "Beim Reden" to "While talking", "In Stille nebeneinander" to "Sitting quietly beside each other",
    "Wenn wir zusammen lachen" to "When we laugh together", "Wenn es schwierig ist" to "When things are difficult",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "What are you most afraid of in our relationship?",
    "Uns auseinanderzuleben" to "Growing apart", "Missverständnisse" to "Misunderstandings", "Die Distanz" to "The distance", "Vor nichts" to "Nothing",
    "Führen wir getrennte oder gemeinsame Konten?" to "Should we keep separate or joint accounts?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "How should we handle different income levels?",
    "Wofür sparen wir gemeinsam?" to "What are we saving for together?",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "Above what amount should we talk before making a purchase?",
    "Nähe & Intimität" to "Closeness & Intimacy",
    "Wann fühlst du dich mir körperlich am nächsten?" to "When do you feel physically closest to me?",
    "Beim Einschlafen nebeneinander" to "Falling asleep beside each other", "Wenn wir uns lange umarmen" to "When we hug for a long time",
    "Bei einer spontanen Berührung" to "A spontaneous touch", "Was fehlt dir über die Distanz am meisten?" to "What do you miss most while we're apart?",
    "Körperliche Nähe" to "Physical closeness", "Einfach nebeneinander sein" to "Simply being beside each other",
    "Gemeinsame Nächte" to "Nights together", "Alltägliche Berührungen" to "Everyday touches",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "How easy is it for you to talk about your desires?",
    "Sehr leicht" to "Very easy", "Geht so" to "So-so", "Eher schwer" to "Quite difficult", "Ich übe noch" to "I'm still practicing",
    "Was macht einen Moment für dich romantisch?" to "What makes a moment romantic for you?",
    "Aufmerksamkeit" to "Thoughtfulness", "Überraschung" to "Surprise", "Vertrautheit" to "Familiarity", "Dass wir ungestört sind" to "Having privacy",

    // Drawing and agree/disagree
    "Zeichne für mich" to "Draw for Me",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Draw our first date — what absolutely belongs in the picture?",
    "Der Ort" to "The place", "Was wir gegessen haben" to "What we ate", "Unsere Gesichter" to "Our faces", "Das Wetter an dem Tag" to "The weather that day",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Draw our dream home in one line. What stands out most?",
    "Große Fenster" to "Large windows", "Der Garten" to "The garden", "Ein Herz an der Tür" to "A heart on the door", "Zwei Stühle davor" to "Two chairs outside",
    "Zeichne mich als Tier — welches wäre ich?" to "Draw me as an animal — which one would I be?",
    "Katze" to "Cat", "Hund" to "Dog", "Pinguin" to "Penguin", "Etwas ganz anderes" to "Something completely different",
    "Zeichne unser Gefühl zueinander als Symbol." to "Draw our feelings for each other as a symbol.",
    "Ein Herz" to "A heart", "Zwei Kreise, die sich überschneiden" to "Two overlapping circles", "Eine Brücke" to "A bridge", "Ein Anker" to "An anchor",
    "In einer Beziehung sollte man alles voneinander wissen." to "Partners in a relationship should know everything about each other.",
    "Stimme voll zu" to "Strongly agree", "Eher zu" to "Somewhat agree", "Eher nicht" to "Somewhat disagree", "Lehne ab" to "Disagree",
    "Man sollte nie streitend einschlafen." to "You should never go to sleep while still arguing.",
    "Getrennte Urlaube tun einer Beziehung gut." to "Separate vacations can be good for a relationship.",
    "Eifersucht ist ein Zeichen von Liebe." to "Jealousy is a sign of love.",
    "Freundschaften mit Ex-Partnern sind okay." to "Friendships with ex-partners are okay.",

    // Daily, lifestyle and intimacy packs
    "Tägliche Aktivität" to "Daily Activity",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "How could your partner be an even better partner for you?",
    "Kennst du die Essensvorlieben deines Partners?" to "Do you know your partner's food preferences?",
    "Das tägliche Leben" to "Everyday Life",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Never have I ever fallen asleep in a cinema.",
    "Ich habe noch nie!" to "Never have I ever!", "Ich habe!" to "I have!",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Never have I ever canceled plans to stay home and watch a TV show.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Never have I ever played on a university sports team.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Never have I ever left wet clothes in the washing machine for several days.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Never have I ever driven an electric car.",
    "Ich habe noch nie einen Nachtzug genommen." to "Never have I ever taken an overnight train.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Never have I ever had to run to catch a connecting flight.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Never have I ever driven a car in a foreign country.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "Never have I ever had a friend move to another country.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Never have I ever made a friend who speaks a different native language.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Never have I ever deleted a social media post because it didn't get enough likes.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Never have I ever cried over a TV series finale.",
    "Unser Intimleben" to "Our Intimate Life",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "What is the best way for your partner to initiate sex with you?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "How do you feel about dirty talk during sex?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "What matters most to you in a sexual encounter?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "How do you feel about watching erotic content together?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "How do you most like to show affection outside of sex?",
    "Beschreibe unser Sexleben mit einem Emoji." to "Describe our sex life with one emoji.",

    // Opinions and married life
    "Unbeliebte Meinungen" to "Unpopular Opinions",
    "Ananas auf der Pizza schmeckt köstlich." to "Pineapple on pizza tastes delicious.",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Famous tourist attractions are always disappointing.",
    "Geister existieren wirklich." to "Ghosts really exist.",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "TV commercials can sometimes be interesting to watch.",
    "Eine neue Sprache zu lernen ist einfach." to "Learning a new language is easy.",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Watching the same movie twice is a waste of time.",
    "Ehepaar Leben" to "Married Life",
    "Wer ist romantischer?" to "Who is more romantic?",
    "Wer ist der beste Tänzer?" to "Who is the better dancer?",
    "Wer gibt mehr Herzlichkeit?" to "Who is more affectionate?",
    "Wer hat den besseren Musikgeschmack?" to "Who has better taste in music?",
    "Wer findet die besten Restaurants?" to "Who finds the best restaurants?",
    "Wer hängt mehr an seinen Eltern?" to "Who is more attached to their parents?",
    "Wer ist besser organisiert?" to "Who is better organized?",
    "Wer ist der Beste bei der Filmauswahl?" to "Who is better at choosing movies?",
    "Wer kocht besser?" to "Who is the better cook?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Who is better at planning romantic dates?",
    "Gesprächsanreger" to "Conversation Starters",
    "Was möchtest du, dass dein Partner öfter tut?" to "What would you like your partner to do more often?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "What is your favorite photo of us? 📸",
    "Welches Lied macht dich an? 🥵" to "Which song turns you on? 🥵",
    "Was magst du an deinem Partner am liebsten?" to "What do you love most about your partner?",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "What is your biggest fear about living together?",
    "Was hast du von deinem Partner gelernt?" to "What have you learned from your partner?",

    // Love balance
    "Liebe im Gleichgewicht" to "Love in Balance",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Be inspired by your partner to become your best self",
    "Werde so akzeptiert, wie du bist" to "Be accepted exactly as you are",
    "Ein Jahr lang eine Fernbeziehung führen" to "Have a long-distance relationship for one year",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Not speak to each other at all for one month",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Only have intimate moments when your partner initiates them",
    "Alle intimen Momente selbst initiieren" to "Initiate every intimate moment yourself",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Share your deepest secrets with your partner",
    "Einige Dinge für dich behalten" to "Keep some things to yourself",
    "Eine Million Dollar gewinnen" to "Win one million dollars", "Eine Million Dollar verdienen" to "Earn one million dollars",
    "Einen sehr emotionalen Partner haben" to "Have a very emotional partner", "Einen sehr logischen Partner haben" to "Have a very logical partner",
    "Deine Beziehung stabil und sicher machen" to "Make your relationship stable and secure",
    "Deine Beziehung abenteuerlich und spontan machen" to "Make your relationship adventurous and spontaneous",
    "Deinen besten Freund verlieren" to "Lose your best friend", "Alle deine Freunde verlieren, außer deinem besten Freund" to "Lose all your friends except your best friend",
    "Teile alle deine Hobbys mit deinem Partner" to "Share all your hobbies with your partner",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Be introduced to new hobbies by your partner",
    "Derjenige sein, der umarmt wird" to "Be the one who gets hugged", "Diejenige sein, die umarmt" to "Be the one giving the hug",
    "Verbringe die Feiertage mit deiner Familie" to "Spend the holidays with your family",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Spend the holidays with your partner's family",

    // New love
    "Neue Liebe, neue Erfahrungen" to "New Love, New Experiences",
    "Ich lache viel mit meinem Partner." to "I laugh a lot with my partner.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "I enjoy discovering new hobbies or activities with my partner.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "I enjoy sharing memes and jokes with my partner.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "I make spending time with my partner a priority, even when I'm busy.",
    "Ich schreibe meinem Partner jeden Tag." to "I message my partner every day.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "I enjoy sharing all the details of my day with my partner.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "I enjoy learning about my partner's hobbies and interests.",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "It bothers me when my partner takes too long to reply to messages.",
    "Ich plane gerne Dates mit meinem Partner." to "I enjoy planning dates with my partner.",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "I love watching movies with my partner that neither of us has seen before.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "I love sharing my favorite music with my partner.",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Romantic gestures such as messages, notes, or gifts make me happy.",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "I prefer romantic walks in the park to going to the movies.",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "I enjoy trying new restaurants with my partner instead of always going to the same places.",

    // Which do you prefer
    "Ein Filmabend" to "Movie Night", "Ein Spieleabend" to "Game Night",
    "Ein aktives Abenteuer" to "An Active Adventure", "Ein entspannender Spa-Tag" to "A Relaxing Spa Day",
    "Ein gemütliches Date drinnen" to "A Cozy Indoor Date", "Eine Autoreise" to "A Road Trip",
    "Einen Film anschauen" to "Watch a Movie", "Gemeinsam ein Lego bauen" to "Build a Lego Set Together",
    "Eine Weinverkostung" to "Wine Tasting", "Eine Schokoladenverkostung" to "Chocolate Tasting",
    "Eine gemütliche Nacht zu Hause" to "A Cozy Night at Home", "Ein Abenteuer in einer neuen Stadt" to "An Adventure in a New City",
    "Zu einem Picknick gehen" to "Go on a Picnic", "Zu einem ausgefallenen Abendessen gehen" to "Go Out for a Fancy Dinner",
    "Ein romantischer Abend" to "A Romantic Evening", "Eine Nacht in einem Club" to "A Night at a Club",
    "Eine Date-Nacht unter den Sternen" to "A Date Night Under the Stars", "Ein romantisches Abendessen bei Kerzenlicht" to "A Romantic Candlelit Dinner",
    "In einen Coffeeshop gehen" to "Go to a Coffee Shop", "In eine Bar gehen" to "Go to a Bar",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "A Cozy Evening at Home During a Thunderstorm",
    "Ein tolles Date im Freien unter dem Mondlicht" to "An Amazing Outdoor Date in the Moonlight",
    "Einen Vergnügungspark erkunden" to "Explore an Amusement Park", "Ein Museum besuchen" to "Visit a Museum",
    "Ein Spieleabend mit Freunden" to "A Game Night with Friends", "Ein romantisches Picknick an einem schönen Ort" to "A Romantic Picnic Somewhere Beautiful",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Try a New Recipe Together", "In einem feinen Restaurant essen gehen" to "Dine at a Fine Restaurant",
    "Zelten gehen" to "Go Camping", "Einen Wellness-Tag" to "Have a Spa Day",
    "Einen Tanzkurs besuchen" to "Take a Dance Class", "Eine Wanderung mit Panoramablick machen" to "Go on a Scenic Hike",
    "Spiele spielen und Spaß haben" to "Play Games and Have Fun", "Tiefgründige Gespräche führen" to "Have Deep Conversations",
    "Ein Live-Musik-Konzert besuchen" to "Go to a Live Music Concert", "Auf eine Bootsparty gehen" to "Go to a Boat Party",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Get Up Early to Watch the Sunrise",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Go to a Beach Bar to Watch the Sunset",

    // Generated gourmet ice-cream pack
    "Gourmet Eis-Sorten" to "Gourmet Ice Cream Flavors",
    "Vanille" to "Vanilla", "Schokolade" to "Chocolate", "Erdbeere" to "Strawberry", "Zitrone" to "Lemon",
    "Stracciatella" to "Stracciatella", "Pistazie" to "Pistachio", "Mango Sorbet" to "Mango Sorbet",
    "Himbeere" to "Raspberry", "Salted Caramel" to "Salted Caramel", "Cookie Dough" to "Cookie Dough",
    "Hazelnut" to "Hazelnut", "White Chocolate" to "White Chocolate", "Walnuss" to "Walnut", "Banane" to "Banana",
    "6 Monate im Altbau mit Charme" to "6 Months in a Charming Period Home",

    // Dev Studio and every supporting mini-feature
    "📂 Ordner" to "📂 Folder", "📝 Spiele" to "📝 Games", "🔗 Ketten" to "🔗 Chains",
    "🖼️ Bilder" to "🖼️ Images", "⚡ Test" to "⚡ Test", "📤 Export" to "📤 Export",
    "Entwickler Studio" to "Developer Studio",
    "Ordner rein · Paare raus · Export für AI Studio" to "Import a folder · Create pairs · Export for AI Studio",
    "Ordner wird gelesen…" to "Reading folder…", "Keine Bilder in diesem Ordner gefunden." to "No images found in this folder.",
    "Bilder werden gelesen…" to "Reading images…", "Bilder-Ordner einlesen" to "Import Image Folder",
    "Je zwei Bilder werden ein Paar. Die Reihenfolge unten ist die Reihenfolge im Spiel — " to "Every two images form a pair. The order below is the order used in the game — ",
    "verschiebe Zeilen mit den Pfeilen, wenn ein Paar nicht passt." to "move rows with the arrows if a pair does not match.",
    "Ordner" to "Folder", "Bilder" to "Images", "Kategorie (z.B. Eis)" to "Category (e.g. ice cream)",
    "Name" to "Name", "Emoji" to "Emoji", "Titel des Spiels" to "Game Title", "Spiel-Emoji" to "Game Emoji",
    "Ein Bild bleibt übrig und wird ignoriert." to "One image is left over and will be ignored.",
    "Leeren" to "Clear", "Paket erstellen & freischalten" to "Create & Unlock Pack",
    "Dateinamen wie 01a_vanille.jpg / 01b_schoko.jpg werden automatisch als Paar erkannt. " to "File names such as 01a_vanilla.jpg / 01b_chocolate.jpg are automatically recognized as a pair. ",
    "Sonst zählt die alphabetische Reihenfolge." to "Otherwise, alphabetical order is used.",
    "Name (optional - leer lassen für kein Text)" to "Name (optional — leave blank for no text)",
    "Nach oben" to "Move Up", "Nach unten" to "Move Down", "Entfernen" to "Remove", "Senden" to "Send",
    "GFK Brücke" to "NVC Bridge", "Spiel suchen…" to "Search Games…",
    "Kategorien & Farben" to "Categories & Colors", "Neues Spiel" to "New Game", "Alle" to "All",
    "⚖️ Das oder Das" to "⚖️ This or That", "🧠 Quiz" to "🧠 Quiz", "🗣️ Diskussion" to "🗣️ Discussion",
    "Das oder Das" to "This or That", "Quiz" to "Quiz", "Diskussion" to "Discussion",
    "Bearbeiten" to "Edit", "Löschen" to "Delete", "Schließen" to "Close", "Spiel bearbeiten" to "Edit Game",
    "Speichern" to "Save", "Titel" to "Title", "Kategorie" to "Category",
    "🎨 Farben & Kategorien verwalten" to "🎨 Manage Colors & Categories", "Spieltyp" to "Game Type",
    "Paare — tippe auf ein Bild, um es zu tauschen" to "Pairs — tap an image to replace it",
    "Paar" to "Pair", "Galerie" to "Gallery", "Paare mischen" to "Shuffle Pairs", "Fragen" to "Questions",
    "Frage hinzufügen" to "Add Question", "Paar löschen" to "Delete Pair", "Bild ändern" to "Change Image",
    "Name (optional)" to "Name (optional)", "Fragetext" to "Question Text", "Frage löschen" to "Delete Question",
    "Antworten, getrennt mit |" to "Answers, separated by |",
    "Bilder & Städte" to "Images & Cities",
    "Jede Option aus allen Spielen. Tippen und ein eigenes Bild aus der Galerie wählen." to "Every option from every game. Tap one to choose a custom image from the gallery.",
    "Option suchen…" to "Search Options…", "Nur Optionen ohne eigenes Bild" to "Only options without a custom image",
    "Eigenes Bild" to "Custom Image", "Zurücksetzen" to "Reset", "Schnelltest" to "Quick Test",
    "Mindestens zwei Bilder auswählen." to "Select at least two images.",
    "Dem Spiel fehlt noch ein Titel." to "The game still needs a title.",
    "Bilder werden gespeichert…" to "Saving images…", "Bild wird übernommen…" to "Importing image…",
    "Bilder werden eingelesen…" to "Reading images…", "Bild konnte nicht gelesen werden." to "The image could not be read.",
    "Keine Pakete zum Exportieren." to "No packs available to export.", "Export wird gebaut…" to "Building export…",
    "Über 3 MB — nimm eine kleinere Bildgröße oder exportiere die Pakete einzeln." to "Over 3 MB — choose a smaller image size or export the packs individually.",
    "Keine eigenen Bilder vorhanden." to "No custom images available.",
    "Startet ein Spiel im echten Runner — genau so, wie ihr es später spielt." to "Starts a game in the real runner — exactly as it will be played later.",
    "Testen" to "Test", "Export für Google AI Studio" to "Export for Google AI Studio",
    "Eine einzige Textdatei mit Paketen und Bildern. AI Studio nimmt keine ZIPs — " to "One text file containing packs and images. AI Studio does not accept ZIP files — ",
    "deshalb stecken die Bilder als Base64 direkt im Kotlin-Code." to "so the images are embedded directly in the Kotlin code as Base64.",
    "Noch nichts zum Exportieren. Leg im Tab \"Ordner\" ein erstes Paket an." to "Nothing to export yet. Create your first pack in the Folder tab.",
    "Pakete (nichts ausgewählt = alle)" to "Packs (nothing selected = all)",
    "Bilder mitschicken" to "Include Images", "Aus: nur Texte, Datei bleibt winzig" to "Off: text only, keeping the file tiny",
    "Bildgröße im Export" to "Export Image Size", "Klein · 480px" to "Small · 480px", "Mittel · 720px" to "Medium · 720px",
    "Groß · 960px" to "Large · 960px", "Für AI Studio exportieren" to "Export for AI Studio",
    "Bilder einzeln teilen" to "Share Images Separately", "Vollständiges Projekt-Backup (JSON)" to "Complete Project Backup (JSON)",
    "Enthält alle Spiele, Ketten, Kategorien UND alle eingebetteten Bilder als Base64. Ideal zur Sicherung, Übertragung & Wiederherstellung." to "Contains every game, chain, category, and all embedded images as Base64. Ideal for backup, transfer, and recovery.",
    "Kopieren" to "Copy", "JSON teilen" to "Share JSON", "Einspielen" to "Import",
    "JSON oder Export-Inhalt (mit Base64) hier einfügen" to "Paste JSON or export content, including Base64, here",
    "Inhalt & Bilder jetzt einspielen" to "Import Content & Images Now",
    "🔗 Ketten-Spiele" to "🔗 Chain Games",
    "Pakete mit dynamischen Bauanleitungen, die sich aus bisherigen Antworten zusammensetzen." to "Packs with dynamic templates assembled from previous answers.",
    "Neue Kette" to "New Chain", "Kette bauen" to "Build Chain", "1 Jahr lang in {}" to "1 Year in {}",
    "6 Monate im {}" to "6 Months in {}", "Weil du {A} gewählt hast …" to "Because You Chose {A}…",
    "Noch keine Ketten angelegt" to "No Chains Yet",
    "Erstelle ein Ketten-Paket, um Fragen dynamisch mit bisherigen Antworten zu verknüpfen." to "Create a chain pack to connect questions dynamically with previous answers.",
    "Spielen" to "Play", "Kette bearbeiten" to "Edit Chain", "Neue Kette erstellen" to "Create New Chain",
    "Kopfzeile (z.B. Weil du {A} gewählt hast …)" to "Caption (e.g. Because you chose {A}…)",
    "Satzmuster (z.B. 6 Monate im {})" to "Sentence Pattern (e.g. 6 months in {})",
    "Neuen Schritt hinzufügen" to "Add New Step", "Abbrechen" to "Cancel", "Speichern & testen" to "Save & Test",
    "Quelle wählen:" to "Choose Source:", "Gewählt" to "Selected", "Nicht gewählt" to "Not Selected",
    "Feste Option" to "Fixed Option", "Fester Text" to "Fixed Text", "Quell-Paket:" to "Source Pack:",
    "Türkis" to "Turquoise", "Limetten grün" to "Lime Green", "Kategorie-Farbe wählen" to "Choose Category Color",
    "Neue Kategorie erstellen" to "Create New Category", "Kategorie bearbeiten" to "Edit Category", "Neue Kategorie" to "New Category",
    "leer" to "empty", "Kein Paket gewählt" to "No Pack Selected", "Gewählte Antwort" to "Selected Answer",
    "Verworfene Antwort" to "Rejected Answer", "beliebiges Paar" to "Any Pair", "Paris oder Rom" to "Paris or Rome",
    "JSON Backup wird vorbereitet…" to "Preparing JSON Backup…",
    "🎉 JSON inkl. Bildern & Ketten kopiert!" to "🎉 JSON including images and chains copied!",
    "JSON Backup Datei wird erstellt…" to "Creating JSON Backup File…",
    "Daten werden eingespielt…" to "Importing Data…",
    "Kette gestartet" to "Chain Started", "🔗 Ketten-Bauer" to "🔗 Chain Builder",
    "Linke Karte (Seite A)" to "Left Card (Side A)", "Rechte Karte (Seite B)" to "Right Card (Side B)",
    "Vorschau:" to "Preview:", "Paar / Option:" to "Pair / Option:",
    "Beliebiges / letztes Paar" to "Any / Last Pair", "Seite:" to "Side:",
    "Linke Option (0)" to "Left Option (0)", "Rechte Option (1)" to "Right Option (1)",
    "🏷️ Kategorien & Farben" to "🏷️ Categories & Colors",
    "Titel des Ketten-Spiels" to "Chain Game Title", "Unbenannte Kette" to "Untitled Chain",
    "Verworfen" to "Rejected", "Freier Text" to "Free Text",
    "Satzmuster (z.B. 1 Jahr lang in {})" to "Sentence Pattern (e.g. 1 year in {})",
    "Standardbild" to "Default Image", "eigen" to "custom",
    "Eis" to "Ice Cream", "Eissorten" to "Ice Cream Flavors",
    "Gold" to "Gold", "Rosa" to "Pink", "Lila" to "Purple", "Blau" to "Blue",
    "Koralle" to "Coral", "Smaragd" to "Emerald", "Rubinrot" to "Ruby Red",
    "Lavendel" to "Lavender", "Magenta" to "Magenta", "Orange" to "Orange",
    "Neubau mit Technik" to "Tech-Enabled New Build", "Offene Küche" to "Open-Plan Kitchen",
    "Gemüsebeet" to "Vegetable Garden", "Hängematte" to "Hammock", "Blumenwiese" to "Flower Meadow",
    "Dachterrasse" to "Rooftop Terrace", "Grillplatz" to "Barbecue Area", "Kamin" to "Fireplace",
    "Belgische Schokolade" to "Belgian Chocolate",
    "In AI Studio hochladen und schreiben: \"Ersetze GeneratedHarmonyContent.kt komplett durch den Inhalt dieser Datei.\"" to
        "Upload to AI Studio and write: \"Replace GeneratedHarmonyContent.kt completely with the contents of this file.\"",

    // Shared UI copy that can also arrive through dynamic messages
    "Fragen & Spiele" to "Questions & Games", "Kategorien" to "Categories", "Themen" to "Topics",
    "Für dich empfohlen" to "Recommended for You", "Paar-Statistiken" to "Couple Statistics",
    "Gemeinsame Tage" to "Days Together", "Beantwortete Fragen" to "Questions Answered",
    "Besuchte Städte" to "Cities Visited", "Besuchte Länder" to "Countries Visited",
    "Widgets" to "Widgets", "Du fehlst mir" to "I Miss You", "Denke an dich" to "Thinking of You",
    "Ich denke an dich" to "I'm Thinking of You", "Kuss senden" to "Send a Kiss", "Kuss" to "Kiss",
    "ERGEBNISSE" to "RESULTS", "BEANTWORTE" to "ANSWER", "Alle Pakete" to "All Packs",
    "Profil" to "Profile", "Dein Name" to "Your Name", "Partnerin" to "Partner",
    "Zusammen seit" to "Together Since", "Partner-Simulator" to "Partner Simulator",
    "Sprache" to "Language", "Deutsch" to "German", "Englisch" to "English",
    "Entwickler-Modus" to "Developer Mode", "Entwickler Studio Öffnen" to "Open Developer Studio",
    "Profil bearbeiten" to "Edit Profile", "Name Partnerin" to "Partner's Name",
    "Hinzufügen" to "Add", "Momente" to "Moments",
    "Was ist passiert?" to "What Happened?", "oder" to "or", "Zurück" to "Back",
    "Deine eigene Antwort" to "Your Own Answer", "Deine Antwort..." to "Your Answer...", "Übernehmen" to "Save",
    "Antwortähnlichkeit" to "Answer Similarity", "Diskutiert eure Antworten" to "Discuss Your Answers",
    "Fertig!" to "Done!", "✎ Tippe, um zu antworten" to "✎ Tap to Answer",
    "Schreibe deine eigene Antwort" to "Write Your Own Answer",
    "Quiz verlassen?" to "Leave Quiz?",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to
        "Are you sure you want to leave the quiz? Your progress will remain saved.",
    "Schreib frei, was dir wirklich dazu einfällt." to "Write freely about what truly comes to mind.",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to
        "Did you discover any surprising differences? Talk about why you each prefer certain options!",
    "✕ Schließen" to "✕ Close",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to
        "There is nothing here right now.\nChange the filter or choose another topic.",
    "✨ GFK-Brücke" to "✨ NVC Bridge",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to
        "Rewrite your draft using nonviolent communication: observation, feeling, need, request.",
    "Was möchtest du eigentlich sagen?" to "What would you really like to say?",
    "In Chat einfügen" to "Insert into Chat",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to
        "Analyzes your answers and chats using the Gottman method and NVC.",
    "Wünsche? z.B. günstig, draußen" to "Preferences? e.g. affordable, outdoors",
    "Spiele & Städte bearbeiten, Ordner reinladen, Bilder anpassen" to
        "Edit games and cities, import folders, and customize images",
    "🔥 Tägliche Aktivität" to "🔥 Daily Activity", "+ Hinzufügen" to "+ Add",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to
        "No moments yet.\nCapture your first memory together 💞",
    "Ein Harmony-Meilenstein eurer Liebe." to "A Harmony Milestone in Your Love Story.",
    "Was wollt ihr nie vergessen?" to "What Do You Never Want to Forget?",
    "🟠 Du bist dran" to "🟠 Your Turn",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to
        "Answer questions at the same time — answers become visible only after you have both finished.",
    "Wir" to "Profile",
    // Seeded chat, moments and API/service errors
    "Hey du 💕 wie war dein Tag?" to "Hey you 💕 how was your day?",
    "Stressig — aber jetzt wird’s besser ☺️" to "Stressful — but it's getting better now ☺️",
    "Ich hab schon an unser Wiedersehen gedacht 🥹" to "I've already been thinking about seeing you again 🥹",
    "Unser erstes Videodate" to "Our First Video Date",
    "Vier Stunden geredet und die Zeit vergessen." to "We talked for four hours and completely lost track of time.",
    "Überraschungspaket" to "Surprise Package",
    "Kekse und ein Brief — ich musste weinen vor Freude." to "Cookies and a letter — I cried happy tears.",
    "Das klingt schön 🥰" to "That sounds lovely 🥰",
    "Ich vermiss dich gerade richtig" to "I really miss you right now",
    "Erzähl mir mehr davon 💕" to "Tell me more about it 💕",
    "Haha du bringst mich immer zum Lachen 😄" to "Haha, you always make me laugh 😄",
    "Können wir heute Abend telefonieren?" to "Can we call tonight?",
    "Ich denk so oft an dich ❤️" to "I think about you so often ❤️",
    "Gemini API Key ist nicht konfiguriert. Bitte füge deinen GEMINI_API_KEY im AI Studio Secrets Panel ein." to "The Gemini API key is not configured. Add your GEMINI_API_KEY in the AI Studio Secrets panel.",
    "Keine Antwort erhalten." to "No response received.",
    "Du bist dran" to "Your Turn", "Beantwortet" to "Answered", "Überspringen" to "Skip", "Weiter" to "Next",
    "KI-Beziehungscoach" to "AI Relationship Coach", "KI-Date-Ideen" to "AI Date Ideas",
    "Analyse starten" to "Start Analysis", "Ideen generieren" to "Generate Ideas",
    "Namen und Startdatum eurer Beziehung." to "Your names and relationship start date.",
    "Fertig" to "Done", "Weiter spielen" to "Keep Playing",
    "Export teilen" to "Share export",
    "Bilder teilen" to "Share images"
)
