package com.example.ui

/**
 * Reviewed Italian copy for every built-in Harmony content item.
 *
 * The values deliberately follow the source order in [EXACT_ENGLISH_CONTENT].
 * The English source map is a LinkedHashMap (Kotlin's mapOf), so the zip preserves
 * every stable German source key while keeping this locale package easy to audit.
 */
internal val EXACT_ITALIAN_CONTENT: Map<String, String> =
    EXACT_ENGLISH_CONTENT.keys.zip(ITALIAN_TRANSLATIONS).toMap()

private val ITALIAN_TRANSLATIONS: List<String> = listOf(
    "Chi sarebbe più propenso?",
    "Disegnare",
    "Questo o quello?",
    "Questo o quello",
    "D'accordo o in disaccordo",
    "Non ho mai",
    "Cosa preferisci?",
    "Rispondi con una foto",
    "Conversazioni profonde",
    "Parlane prima di...",
    "Riscaldamento",
    "Relazione",
    "Sesso e amore",
    "Valori morali",
    "Denaro e finanze",
    "Conoscersi meglio",
    "Viaggi",
    "Famiglia",
    "Hobby",
    "Intrattenimento",
    "Questo o quello",
    "Matrimonio",
    "Figli",
    "Discussione",
    "Viaggi",
    "Famiglia",
    "Casa e vita quotidiana",
    "Cosa ti piace di più della tua casa?",
    "L'atmosfera accogliente e tranquilla",
    "Che tutto rispecchi il mio stile",
    "Le persone che ci vivono",
    "La vista fuori",
    "Quale stanza dice di più su di te?",
    "Cucina",
    "Camera da letto",
    "Soggiorno",
    "Il mio spazio di lavoro",
    "Cosa cambieresti subito se il denaro non fosse un problema?",
    "Una cucina più grande",
    "Un balcone o un giardino",
    "Una posizione migliore",
    "Niente — va benissimo così",
    "Com'è la tua domenica perfetta a casa?",
    "Dormire fino a tardi e non fare nulla",
    "Cucinare e invitare amici",
    "Maratona di serie sul divano",
    "Riordinare e affrontare i progetti",
    "La proposta perfetta",
    "Quale ambiente desidereresti per una proposta?",
    "A casa, intimo e privato",
    "All'aperto, con la natura come sfondo",
    "Un ristorante o hotel elegante",
    "Preferiresti una proposta pubblica o privata?",
    "Solo noi due",
    "Con la famiglia e gli amici più stretti",
    "In un luogo pubblico con tanti spettatori",
    "La proposta dovrebbe essere una sorpresa?",
    "Sì, completamente a sorpresa",
    "Meglio parlarne prima in generale",
    "Decidiamolo insieme",
    "Quanto è importante per te immortalare il momento?",
    "Molto importante — foto e video",
    "Bastano alcune foto col telefono",
    "Per niente, il momento è nostro",
    "Preferenze per la proposta",
    "Preferisci una proposta stravagante o qualcosa di discreto?",
    "Esagerata e spettacolare",
    "Una via di mezzo con dettagli speciali",
    "Semplice e intima",
    "Cosa pensi degli accessori (ad es. cartelli, palloncini ecc.)?",
    "Li adoro, rendono tutto più divertente",
    "Forse uno o due",
    "No, distraggono troppo",
    "Vorresti condividere subito il momento sui social?",
    "Sì, condividiamolo subito",
    "No, teniamolo privato all'inizio",
    "Prima solo con amici stretti e famiglia",
    "Quanto è importante che la proposta rispecchi i tuoi hobby o interessi?",
    "Molto importante, dovrebbe essere personale",
    "Un po', un piccolo tocco personale sarebbe bello",
    "Non è necessario, meglio rimanere classici",
    "Preferiresti una proposta in vacanza (con un viaggio)?",
    "Sì, in una città emozionante o presso un luogo famoso",
    "Forse, se è fattibile",
    "No, meglio vicino a casa",
    "Quanto tempo dopo la proposta vorresti festeggiare con gli altri?",
    "Lo stesso giorno con amici e famiglia",
    "Circa una settimana dopo, prima solo noi due",
    "Niente festa necessaria, teniamola privata",
    "Vorresti una lettera scritta come parte della proposta?",
    "Sì, qualcosa da leggere e conservare",
    "Forse, ma bastano le parole dette",
    "No, manteniamola semplice",
    "La proposta dovrebbe includere elementi culturali o tradizionali?",
    "Sì, includiamo le tradizioni",
    "Qualche richiamo culturale va bene",
    "No, manteniamola moderna",
    "Qual è la cosa più importante in una proposta?",
    "L'ambientazione e l'atmosfera",
    "Le parole e le emozioni",
    "L'anello e il gesto",
    "Vorresti che gli animali domestici facessero parte della proposta?",
    "Sì, fanno parte della famiglia!",
    "Forse, se ci sta bene",
    "No, solo noi",
    "Parlatene prima di avere figli",
    "Siamo in grado di coprire tutti i costi di uno o più figli? 💰",
    "Potremmo dover risparmiare",
    "Avremo abbastanza tempo per nostro figlio o i nostri figli? ⏳",
    "Sì, faremo in modo che il tempo in famiglia venga prima.",
    "Come troveremo tempo per la nostra relazione quando arriverà il bambino?",
    "Programmare appuntamenti regolari o tempo di qualità insieme",
    "Come vorresti che fosse il nostro futuro?",
    "Viaggiare insieme per il mondo ed esplorare nuove culture e cucine",
    "Come la/lo chiameresti?",
    "Preferiresti una bambina o un bambino? 👶",
    "Cosa speriamo che diventi nostro figlio da adulto?",
    "Parlatene prima di prendere un animale domestico",
    "Chi si occuperà delle cure quotidiane?",
    "Cosa succede all'animale quando viaggiamo?",
    "Quale budget prevediamo per cibo e veterinario?",
    "Un animale si adatta davvero alla nostra vita quotidiana?",
    "Parlatene prima del viaggio insieme",
    "Quanto vogliamo spendere in totale?",
    "Meglio tutto pianificato o spontaneo?",
    "Quanto tempo vogliamo trascorrere separati?",
    "Qual è il momento clou assoluto per ciascuno di noi?",
    "Parlatene prima di comprare casa",
    "Quanto mutuo possiamo realisticamente sostenere?",
    "Città o campagna — cosa è più importante per noi?",
    "Quanto tempo vogliamo restare lì almeno?",
    "Chi si occupa di ristrutturazione e manutenzione?",
    "Destinazioni di viaggio",
    "La nostra casa dei sogni",
    "Esterno della casa dei sogni",
    "Attività",
    "Preferenze alimentari",
    "Anelli di fidanzamento",
    "Bouquet di nozze",
    "Domande per ogni occasione",
    "Cosa preferisci: alzarti presto o restare sveglio fino a tardi?",
    "Preferisci una serata tranquilla in due o in compagnia?",
    "Scatti della nostra storia d'amore",
    "Quale momento ha segnato per te l'inizio di “noi”?",
    "Qual è la tua foto preferita di noi?",
    "Cosa ricordi più vividamente?",
    "Riscaldamento: conoscersi meglio",
    "Qual è stato finora il tuo momento più bello con me?",
    "Cosa ti piacerebbe fare di più in una giornata insieme?",
    "Quando ti senti più amata/o?",
    "Cosa ti entusiasma di più di noi?",
    "Chi sarebbe più propenso ad arrivare tardi?",
    "Chi sarebbe più propenso a cedere per primo durante un litigio?",
    "Chi sarebbe più propenso a prenotare spontaneamente un viaggio?",
    "Chi dimenticherebbe più facilmente un anniversario?",
    "Non ho mai… annullato un appuntamento per restare a casa.",
    "Non ho mai… guardato di nascosto il telefono del mio partner.",
    "Non ho mai… riscritto un messaggio 10 volte.",
    "Cosa significa concretamente per te la fiducia?",
    "Qual è per te un limite invalicabile?",
    "Quando ti senti più vicina/o a me?",
    "Di cosa hai più paura nella nostra relazione?",
    "Abbiamo conti separati o comuni?",
    "Come gestiamo redditi diversi?",
    "Per cosa risparmiamo insieme?",
    "Da quale importo ne parliamo prima di un acquisto?",
    "Vicinanza e intimità",
    "Quando ti senti più vicina/o a me fisicamente?",
    "Quanto ti riesce facile parlare dei desideri?",
    "Cosa rende un momento romantico per te?",
    "Disegna per me",
    "Disegna il nostro primo appuntamento — cosa non può mancare?",
    "Disegna la nostra casa dei sogni con una sola linea. Qual è l'elemento più evidente?",
    "Disegnami come un animale — quale sarei?",
    "Disegna ciò che proviamo l'uno per l'altra/o come un simbolo.",
    "In una relazione bisognerebbe sapere tutto dell'altra persona.",
    "Non si dovrebbe mai andare a dormire arrabbiati.",
    "Le vacanze separate fanno bene a una relazione.",
    "La gelosia è un segno d'amore.",
    "Le amicizie con gli ex partner vanno bene.",
    "Attività quotidiana",
    "Come può il tuo partner essere un partner ancora migliore per te?",
    "Conosci le preferenze alimentari del tuo partner?",
    "La vita quotidiana",
    "Non mi sono mai addormentata/o al cinema.",
    "Non ho mai annullato dei programmi per restare a casa a guardare una serie TV.",
    "Non ho mai giocato in una squadra sportiva universitaria.",
    "Non ho mai dimenticato i vestiti bagnati in lavatrice per alcuni giorni.",
    "Non ho mai guidato un'auto elettrica.",
    "Non ho mai preso un treno notturno.",
    "Non ho mai dovuto correre per prendere una coincidenza aerea.",
    "Non ho mai guidato un'auto in un Paese straniero.",
    "Non ho mai avuto un amico che si è trasferito in un altro Paese.",
    "Non ho mai conosciuto un amico che parla un'altra lingua madre.",
    "Non ho mai cancellato un post sui social perché non aveva abbastanza like.",
    "Non ho mai pianto per il finale di una serie TV.",
    "La nostra vita intima",
    "Come può il tuo partner iniziare al meglio un rapporto sessuale con te?",
    "Cosa pensi del linguaggio esplicito durante il sesso?",
    "Qual è la cosa più importante che cerchi in un incontro sessuale?",
    "Cosa pensi di guardare insieme contenuti erotici?",
    "Come preferisci mostrare affetto al di fuori del sesso?",
    "Descrivi la nostra vita sessuale con un'emoji.",
    "Opinioni impopolari",
    "L'ananas sulla pizza è deliziosa.",
    "Le famose mete turistiche sono sempre una delusione.",
    "I fantasmi esistono davvero.",
    "La pubblicità in TV a volte è interessante da guardare.",
    "Imparare una nuova lingua è facile.",
    "Guardare lo stesso film due volte è una perdita di tempo.",
    "Vita di coppia",
    "Chi è più romantica/o?",
    "Chi è la/il ballerina/o migliore?",
    "Chi dà più affetto?",
    "Chi ha gusti musicali migliori?",
    "Chi trova i ristoranti migliori?",
    "Chi è più legata/o ai propri genitori?",
    "Chi è più organizzata/o?",
    "Chi è la/il migliore a scegliere i film?",
    "Chi cucina meglio?",
    "Chi è la/il migliore nel pianificare appuntamenti romantici?",
    "Spunti di conversazione",
    "Cosa vorresti che il tuo partner facesse più spesso?",
    "Qual è la tua foto preferita di noi? 📸",
    "Quale canzone ti eccita? 🥵",
    "Cosa ti piace di più del tuo partner?",
    "Qual è la tua più grande paura di convivere?",
    "Cosa hai imparato dal tuo partner?",
    "Amore in equilibrio",
    "Lasciati ispirare dal tuo partner per diventare la versione migliore di te",
    "Essere accettata/o per come sei",
    "Avere una relazione a distanza per un anno",
    "Non parlare affatto per un mese",
    "Vivere momenti intimi solo quando li inizia il tuo partner",
    "Iniziare tu tutti i momenti intimi",
    "Condividere i tuoi segreti più profondi con il partner",
    "Tenere alcune cose per te",
    "Rendere la vostra relazione stabile e sicura",
    "Rendere la vostra relazione avventurosa e spontanea",
    "Condividere tutti i tuoi hobby con il partner",
    "Essere introdotta/o dal partner a nuovi hobby",
    "Trascorrere le feste con la tua famiglia",
    "Trascorrere le feste con la famiglia del tuo partner",
    "Amore nuovo, nuove esperienze",
    "Rido molto con il mio partner.",
    "Mi piace scoprire nuovi hobby o attività con il mio partner.",
    "Mi piace condividere meme e battute con il mio partner.",
    "Do priorità al tempo con il mio partner, anche quando sono impegnata/o.",
    "Scrivo al mio partner ogni giorno.",
    "Mi piace condividere tutti i dettagli della mia giornata con il mio partner.",
    "Mi piace conoscere gli hobby e gli interessi del mio partner.",
    "Mi infastidisce quando il mio partner impiega troppo tempo a rispondere ai messaggi.",
    "Mi piace organizzare appuntamenti con il mio partner.",
    "Adoro guardare con il mio partner film che nessuno dei due ha mai visto.",
    "Adoro condividere la mia musica preferita con il mio partner.",
    "I gesti romantici, come messaggi, bigliettini o regali, mi rendono felice.",
    "Preferisco le passeggiate romantiche al parco a una serata al cinema.",
    "Mi piace provare nuovi ristoranti con il mio partner invece di andare sempre negli stessi posti.",
    "Una serata accogliente in casa durante un temporale",
    "Un appuntamento all'aperto sotto la luce della luna",
    "Andare presto al mattino a vedere l'alba",
    "Andare in un bar sulla spiaggia per vedere il tramonto",
    "Gelati gourmet",
    "6 mesi in un edificio d'epoca pieno di fascino",
    "Studio sviluppatore",
    "Cartella dentro · coppie fuori · esportazione per AI Studio",
    "Ogni due immagini formano una coppia. L'ordine qui sotto è l'ordine nel gioco —",
    "sposta le righe con le frecce se una coppia non funziona.",
    "Rimane una foto che viene ignorata.",
    "I nomi file come 01a_vanille.jpg / 01b_schoko.jpg vengono riconosciuti automaticamente come coppia.",
    "Altrimenti conta l'ordine alfabetico.",
    "Nome (facoltativo - lascia vuoto per nessun testo)",
    "Coppie — tocca un'immagine per scambiarla",
    "Risposte, separate da |",
    "Immagini e città",
    "Ogni opzione di tutti i giochi. Tocca e scegli un'immagine personalizzata dalla galleria.",
    "Seleziona almeno due immagini.",
    "Al gioco manca ancora un titolo.",
    "Oltre 3 MB — usa immagini più piccole o esporta i pacchetti separatamente.",
    "Non ci sono immagini personali.",
    "Avvia un gioco nel runner reale — esattamente come lo giocherete più tardi.",
    "Un unico file di testo con pacchetti e immagini. AI Studio non accetta ZIP —",
    "perciò le immagini sono direttamente nel codice Kotlin come Base64.",
    "Non c'è ancora nulla da esportare. Crea un primo pacchetto nella scheda “Cartella”.",
    "Pacchetti (nessuna selezione = tutti)",
    "Contiene tutti i giochi, le catene, le categorie E tutte le immagini incorporate come Base64. Ideale per salvataggio, trasferimento e ripristino.",
    "Incolla qui JSON o contenuto esportato (con Base64)",
    "Importa ora contenuti e immagini",
    "🔗 Giochi a catena",
    "Pacchetti con istruzioni dinamiche che si compongono dalle risposte precedenti.",
    "Non sono ancora state create catene",
    "Crea un pacchetto a catena per collegare dinamicamente le domande alle risposte precedenti.",
    "Intestazione (ad es. Poiché hai scelto {A}…)",
    "Schema di frase (ad es. 6 mesi in {})",
    "Si sta preparando il backup JSON…",
    "🎉 JSON con immagini e catene copiato!",
    "Creazione del file di backup JSON…",
    "Importazione dati in corso…",
    "🏷️ Categorie e colori",
    "Schema di frase (ad es. 1 anno in {})",
    "Cioccolato belga",
    "Carica in AI Studio e scrivi: \"Sostituisci completamente GeneratedHarmonyContent.kt con il contenuto di questo file.\"",
    "Scrivi la tua risposta",
    "Uscire dal quiz?",
    "Vuoi davvero uscire dal quiz? I tuoi progressi finora resteranno salvati.",
    "Scrivi liberamente ciò che ti viene davvero in mente.",
    "Avete scoperto differenze sorprendenti? Parlatene: perché alcune opzioni vi piacciono di più!",
    "✕ Chiudi",
    "Qui non c'è nulla al momento.\nCambia il filtro o scegli un altro argomento.",
    "✨ Ponte CNV",
    "Riformulate il vostro testo in modo non violento: osservazione, sentimento, bisogno, richiesta.",
    "Cosa vorresti davvero dire?",
    "Inserisci nella chat",
    "Analizza le vostre risposte e chat secondo Gottman e CNV.",
    "Desideri? Ad es. economico, all'aperto",
    "Modifica giochi e città, carica cartelle, adatta le immagini",
    "Non ci sono ancora momenti.\nConservate la vostra prima esperienza 💞",
    "Una pietra miliare dell'amore in Harmony.",
    "Cosa non volete mai dimenticare?",
    "🟠 Tocca a te",
    "Rispondete alle domande contemporaneamente — le risposte diventano visibili solo quando avete finito entrambi.",
    "Noi",
    "Ehi amore 💕 com'è andata la tua giornata?",
    "Stressante — ma ora va meglio ☺️",
    "Ho già pensato al nostro prossimo incontro 🥹",
    "Il nostro primo appuntamento in video",
    "Abbiamo parlato per quattro ore e perso completamente la cognizione del tempo.",
    "Pacchetto sorpresa",
    "Biscotti e una lettera — ho pianto di gioia.",
    "Che bello 🥰",
    "Mi manchi davvero tanto adesso",
    "Raccontami di più 💕",
    "Ahah, mi fai sempre ridere 😄",
    "Possiamo sentirci stasera?",
    "Penso così spesso a te ❤️",
    "La chiave API Gemini non è configurata. Aggiungi GEMINI_API_KEY nel pannello Secrets di AI Studio.",
    "Nessuna risposta ricevuta.",
    "I vostri nomi e la data d'inizio della relazione."
)
