package com.example.ui

/**
 * Reviewed Italian copy for every built-in Harmony content item.
 *
 * Each stable German source key is explicit. This prevents a future reordering of
 * another locale from changing Italian labels or question text.
 */
internal val EXACT_ITALIAN_CONTENT: Map<String, String> = mapOf(
    "Wer würde eher?" to "Chi sarebbe più propenso?",
    "Zeichnen" to "Disegnare",
    "Das oder das?" to "Questo o quello?",
    "Das oder das" to "Questo o quello",
    "Zustimmen oder Ablehnen" to "D'accordo o in disaccordo",
    "Ich habe noch nie" to "Non ho mai",
    "Was magst du lieber?" to "Cosa preferisci?",
    "Antwort mit einem Foto" to "Rispondi con una foto",
    "Tiefe Gespräche" to "Conversazioni profonde",
    "Reden vor ..." to "Parlane prima di...",
    "Aufwärmen" to "Riscaldamento",
    "Beziehung" to "Relazione",
    "Sex & Liebe" to "Sesso e amore",
    "Moralische Werte" to "Valori morali",
    "Geld & Finanzen" to "Denaro e finanze",
    "Einander kennenlernen" to "Conoscersi meglio",
    "Reisen" to "Viaggi",
    "Familie" to "Famiglia",
    "Hobbys" to "Hobby",
    "unterhaltung" to "Intrattenimento",
    "dasoderdas" to "Questo o quello",
    "hochzeit" to "Matrimonio",
    "kinder" to "Figli",
    "reden" to "Discussione",
    "reisen" to "Viaggi",
    "familie" to "Famiglia",
    "Zuhause & Alltag" to "Casa e vita quotidiana",
    "Was gefällt dir an deinem Zuhause am besten?" to "Cosa ti piace di più della tua casa?",
    "Die Gemütlichkeit und Ruhe" to "L'atmosfera accogliente e tranquilla",
    "Dass alles meinen Stil hat" to "Che tutto rispecchi il mio stile",
    "Die Menschen, die darin wohnen" to "Le persone che ci vivono",
    "Der Blick nach draußen" to "La vista fuori",
    "Welcher Raum sagt am meisten über dich aus?" to "Quale stanza dice di più su di te?",
    "Küche" to "Cucina",
    "Schlafzimmer" to "Camera da letto",
    "Wohnzimmer" to "Soggiorno",
    "Mein Arbeitsplatz" to "Il mio spazio di lavoro",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "Cosa cambieresti subito se il denaro non fosse un problema?",
    "Größere Küche" to "Una cucina più grande",
    "Ein Balkon oder Garten" to "Un balcone o un giardino",
    "Bessere Lage" to "Una posizione migliore",
    "Nichts — es passt so" to "Niente — va benissimo così",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "Com'è la tua domenica perfetta a casa?",
    "Ausschlafen und nichts tun" to "Dormire fino a tardi e non fare nulla",
    "Kochen und Freunde einladen" to "Cucinare e invitare amici",
    "Serienmarathon auf dem Sofa" to "Maratona di serie sul divano",
    "Aufräumen und Projekte angehen" to "Riordinare e affrontare i progetti",
    "Der perfekte Heiratsantrag" to "La proposta perfetta",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "Quale ambiente desidereresti per una proposta?",
    "Zu Hause, gemütlich und privat" to "A casa, intimo e privato",
    "Draußen mit der Natur als Kulisse" to "All'aperto, con la natura come sfondo",
    "Schickes Restaurant oder Hotel" to "Un ristorante o hotel elegante",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Preferiresti una proposta pubblica o privata?",
    "Nur wir beide" to "Solo noi due",
    "Mit Familie und engen Freunden" to "Con la famiglia e gli amici più stretti",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "In un luogo pubblico con tanti spettatori",
    "Soll der Antrag eine Überraschung sein?" to "La proposta dovrebbe essere una sorpresa?",
    "Ja, komplett überraschend" to "Sì, completamente a sorpresa",
    "Lieber vorher grob absprechen" to "Meglio parlarne prima in generale",
    "Wir entscheiden es gemeinsam" to "Decidiamolo insieme",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "Quanto è importante per te immortalare il momento?",
    "Sehr wichtig — Fotos und Video" to "Molto importante — foto e video",
    "Ein paar Handyfotos reichen" to "Bastano alcune foto col telefono",
    "Gar nicht, der Moment gehört uns" to "Per niente, il momento è nostro",
    "Vorlieben für den Antrag" to "Preferenze per la proposta",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Preferisci una proposta stravagante o qualcosa di discreto?",
    "Übertrieben und großartig" to "Esagerata e spettacolare",
    "Mittelweg mit besonderen Details" to "Una via di mezzo con dettagli speciali",
    "Einfach und intim" to "Semplice e intima",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "Cosa pensi degli accessori (ad es. cartelli, palloncini ecc.)?",
    "Liebe sie, macht mehr Spaß" to "Li adoro, rendono tutto più divertente",
    "Vielleicht ein oder zwei" to "Forse uno o due",
    "Nein, zu ablenkend" to "No, distraggono troppo",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Vorresti condividere subito il momento sui social?",
    "Ja, sofort teilen" to "Sì, condividiamolo subito",
    "Nein, erstmal privat halten" to "No, teniamolo privato all'inizio",
    "Erst nur enge Freunde/Familie" to "Prima solo con amici stretti e famiglia",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Quanto è importante che la proposta rispecchi i tuoi hobby o interessi?",
    "Sehr wichtig, es sollte persönlich sein" to "Molto importante, dovrebbe essere personale",
    "Etwas, eine kleine Note wäre schön" to "Un po', un piccolo tocco personale sarebbe bello",
    "Nicht nötig, lieber klassisch bleiben" to "Non è necessario, meglio rimanere classici",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Preferiresti una proposta in vacanza (con un viaggio)?",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Sì, in una città emozionante o presso un luogo famoso",
    "Vielleicht, wenn es machbar ist" to "Forse, se è fattibile",
    "Nein, lieber vor Ort" to "No, meglio vicino a casa",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "Quanto tempo dopo la proposta vorresti festeggiare con gli altri?",
    "Am selben Tag mit Freunden/Familie" to "Lo stesso giorno con amici e famiglia",
    "Etwa eine Woche später, erst mal nur wir" to "Circa una settimana dopo, prima solo noi due",
    "Keine Party nötig, privat halten" to "Niente festa necessaria, teniamola privata",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Vorresti una lettera scritta come parte della proposta?",
    "Ja, etwas zum Lesen und Aufbewahren" to "Sì, qualcosa da leggere e conservare",
    "Vielleicht, aber mündlich reicht" to "Forse, ma bastano le parole dette",
    "Nein, einfach halten" to "No, manteniamola semplice",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "La proposta dovrebbe includere elementi culturali o tradizionali?",
    "Ja, Traditionen einbinden" to "Sì, includiamo le tradizioni",
    "Ein paar kulturelle Anklänge sind okay" to "Qualche richiamo culturale va bene",
    "Nein, modern halten" to "No, manteniamola moderna",
    "Was ist das Wichtigste beim Antrag?" to "Qual è la cosa più importante in una proposta?",
    "Die Umgebung und Atmosphäre" to "L'ambientazione e l'atmosfera",
    "Die Worte und Emotionen" to "Le parole e le emozioni",
    "Der Ring und die Geste" to "L'anello e il gesto",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Vorresti che gli animali domestici facessero parte della proposta?",
    "Ja, sie gehören zur Familie!" to "Sì, fanno parte della famiglia!",
    "Vielleicht, wenn es passt" to "Forse, se ci sta bene",
    "Nein, nur wir" to "No, solo noi",
    "Diskutiere vor dem Kinderkriegen" to "Parlatene prima di avere figli",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Siamo in grado di coprire tutti i costi di uno o più figli? 💰",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "Potremmo dover risparmiare",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Avremo abbastanza tempo per nostro figlio o i nostri figli? ⏳",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Sì, faremo in modo che il tempo in famiglia venga prima.",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "Come troveremo tempo per la nostra relazione quando arriverà il bambino?",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Programmare appuntamenti regolari o tempo di qualità insieme",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "Come vorresti che fosse il nostro futuro?",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Viaggiare insieme per il mondo ed esplorare nuove culture e cucine",
    "Wie würdest du sie/ihn nennen?" to "Come la/lo chiameresti?",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Preferiresti una bambina o un bambino? 👶",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "Cosa speriamo che diventi nostro figlio da adulto?",
    "Vor der Anschaffung eines Haustiers besprechen" to "Parlatene prima di prendere un animale domestico",
    "Wer übernimmt die tägliche Versorgung?" to "Chi si occuperà delle cure quotidiane?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "Cosa succede all'animale quando viaggiamo?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "Quale budget prevediamo per cibo e veterinario?",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Un animale si adatta davvero alla nostra vita quotidiana?",
    "Vor der gemeinsamen Reise besprechen" to "Parlatene prima del viaggio insieme",
    "Wie viel wollen wir insgesamt ausgeben?" to "Quanto vogliamo spendere in totale?",
    "Lieber durchgeplant oder spontan?" to "Meglio tutto pianificato o spontaneo?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "Quanto tempo vogliamo trascorrere separati?",
    "Was ist für jeden von uns das absolute Highlight?" to "Qual è il momento clou assoluto per ciascuno di noi?",
    "Vor dem Kauf eines Hauses besprechen" to "Parlatene prima di comprare casa",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "Quanto mutuo possiamo realisticamente sostenere?",
    "Stadt oder Land — was ist uns wichtiger?" to "Città o campagna — cosa è più importante per noi?",
    "Wie lange wollen wir dort mindestens bleiben?" to "Quanto tempo vogliamo restare lì almeno?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Chi si occupa di ristrutturazione e manutenzione?",
    "Reiseziele" to "Destinazioni di viaggio",
    "Unser Traumhaus" to "La nostra casa dei sogni",
    "Traumhaus Außenbereich" to "Esterno della casa dei sogni",
    "Aktivitäten" to "Attività",
    "Essensvorlieben" to "Preferenze alimentari",
    "Verlobungsringe" to "Anelli di fidanzamento",
    "Hochzeitssträuße" to "Bouquet di nozze",
    "Fragen für jede Gelegenheit" to "Domande per ogni occasione",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Cosa preferisci: alzarti presto o restare sveglio fino a tardi?",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Preferisci una serata tranquilla in due o in compagnia?",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Scatti della nostra storia d'amore",
    "Welcher Moment war für dich der Anfang von „uns\"?" to "Quale momento ha segnato per te l'inizio di “noi”?",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Qual è la tua foto preferita di noi?",
    "Woran erinnerst du dich am lebhaftesten?" to "Cosa ricordi più vividamente?",
    "Aufwärmen: Einander kennenlernen" to "Riscaldamento: conoscersi meglio",
    "Was war dein schönster Moment mit mir bisher?" to "Qual è stato finora il tuo momento più bello con me?",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Cosa ti piacerebbe fare di più in una giornata insieme?",
    "Wie fühlst du dich am meisten geliebt?" to "Quando ti senti più amata/o?",
    "Worauf freust du dich bei uns am meisten?" to "Cosa ti entusiasma di più di noi?",
    "Wer würde eher zu spät kommen?" to "Chi sarebbe più propenso ad arrivare tardi?",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Chi sarebbe più propenso a cedere per primo durante un litigio?",
    "Wer würde eher spontan eine Reise buchen?" to "Chi sarebbe più propenso a prenotare spontaneamente un viaggio?",
    "Wer vergisst eher einen Jahrestag?" to "Chi dimenticherebbe più facilmente un anniversario?",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Non ho mai… annullato un appuntamento per restare a casa.",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Non ho mai… guardato di nascosto il telefono del mio partner.",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Non ho mai… riscritto un messaggio 10 volte.",
    "Was bedeutet Vertrauen für dich konkret?" to "Cosa significa concretamente per te la fiducia?",
    "Was ist für dich ein absoluter Dealbreaker?" to "Qual è per te un limite invalicabile?",
    "Wann fühlst du dich mir am nächsten?" to "Quando ti senti più vicina/o a me?",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "Di cosa hai più paura nella nostra relazione?",
    "Führen wir getrennte oder gemeinsame Konten?" to "Abbiamo conti separati o comuni?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Come gestiamo redditi diversi?",
    "Wofür sparen wir gemeinsam?" to "Per cosa risparmiamo insieme?",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "Da quale importo ne parliamo prima di un acquisto?",
    "Nähe & Intimität" to "Vicinanza e intimità",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Quando ti senti più vicina/o a me fisicamente?",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Quanto ti riesce facile parlare dei desideri?",
    "Was macht einen Moment für dich romantisch?" to "Cosa rende un momento romantico per te?",
    "Zeichne für mich" to "Disegna per me",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Disegna il nostro primo appuntamento — cosa non può mancare?",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Disegna la nostra casa dei sogni con una sola linea. Qual è l'elemento più evidente?",
    "Zeichne mich als Tier — welches wäre ich?" to "Disegnami come un animale — quale sarei?",
    "Zeichne unser Gefühl zueinander als Symbol." to "Disegna ciò che proviamo l'uno per l'altra/o come un simbolo.",
    "In einer Beziehung sollte man alles voneinander wissen." to "In una relazione bisognerebbe sapere tutto dell'altra persona.",
    "Man sollte nie streitend einschlafen." to "Non si dovrebbe mai andare a dormire arrabbiati.",
    "Getrennte Urlaube tun einer Beziehung gut." to "Le vacanze separate fanno bene a una relazione.",
    "Eifersucht ist ein Zeichen von Liebe." to "La gelosia è un segno d'amore.",
    "Freundschaften mit Ex-Partnern sind okay." to "Le amicizie con gli ex partner vanno bene.",
    "Tägliche Aktivität" to "Attività quotidiana",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Come può il tuo partner essere un partner ancora migliore per te?",
    "Kennst du die Essensvorlieben deines Partners?" to "Conosci le preferenze alimentari del tuo partner?",
    "Das tägliche Leben" to "La vita quotidiana",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Non mi sono mai addormentata/o al cinema.",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Non ho mai annullato dei programmi per restare a casa a guardare una serie TV.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Non ho mai giocato in una squadra sportiva universitaria.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Non ho mai dimenticato i vestiti bagnati in lavatrice per alcuni giorni.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Non ho mai guidato un'auto elettrica.",
    "Ich habe noch nie einen Nachtzug genommen." to "Non ho mai preso un treno notturno.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Non ho mai dovuto correre per prendere una coincidenza aerea.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Non ho mai guidato un'auto in un Paese straniero.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "Non ho mai avuto un amico che si è trasferito in un altro Paese.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Non ho mai conosciuto un amico che parla un'altra lingua madre.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Non ho mai cancellato un post sui social perché non aveva abbastanza like.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Non ho mai pianto per il finale di una serie TV.",
    "Unser Intimleben" to "La nostra vita intima",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Come può il tuo partner iniziare al meglio un rapporto sessuale con te?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Cosa pensi del linguaggio esplicito durante il sesso?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Qual è la cosa più importante che cerchi in un incontro sessuale?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Cosa pensi di guardare insieme contenuti erotici?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Come preferisci mostrare affetto al di fuori del sesso?",
    "Beschreibe unser Sexleben mit einem Emoji." to "Descrivi la nostra vita sessuale con un'emoji.",
    "Unbeliebte Meinungen" to "Opinioni impopolari",
    "Ananas auf der Pizza schmeckt köstlich." to "L'ananas sulla pizza è deliziosa.",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "Le famose mete turistiche sono sempre una delusione.",
    "Geister existieren wirklich." to "I fantasmi esistono davvero.",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "La pubblicità in TV a volte è interessante da guardare.",
    "Eine neue Sprache zu lernen ist einfach." to "Imparare una nuova lingua è facile.",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Guardare lo stesso film due volte è una perdita di tempo.",
    "Ehepaar Leben" to "Vita di coppia",
    "Wer ist romantischer?" to "Chi è più romantica/o?",
    "Wer ist der beste Tänzer?" to "Chi è la/il ballerina/o migliore?",
    "Wer gibt mehr Herzlichkeit?" to "Chi dà più affetto?",
    "Wer hat den besseren Musikgeschmack?" to "Chi ha gusti musicali migliori?",
    "Wer findet die besten Restaurants?" to "Chi trova i ristoranti migliori?",
    "Wer hängt mehr an seinen Eltern?" to "Chi è più legata/o ai propri genitori?",
    "Wer ist besser organisiert?" to "Chi è più organizzata/o?",
    "Wer ist der Beste bei der Filmauswahl?" to "Chi è la/il migliore a scegliere i film?",
    "Wer kocht besser?" to "Chi cucina meglio?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Chi è la/il migliore nel pianificare appuntamenti romantici?",
    "Gesprächsanreger" to "Spunti di conversazione",
    "Was möchtest du, dass dein Partner öfter tut?" to "Cosa vorresti che il tuo partner facesse più spesso?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Qual è la tua foto preferita di noi? 📸",
    "Welches Lied macht dich an? 🥵" to "Quale canzone ti eccita? 🥵",
    "Was magst du an deinem Partner am liebsten?" to "Cosa ti piace di più del tuo partner?",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Qual è la tua più grande paura di convivere?",
    "Was hast du von deinem Partner gelernt?" to "Cosa hai imparato dal tuo partner?",
    "Liebe im Gleichgewicht" to "Amore in equilibrio",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Lasciati ispirare dal tuo partner per diventare la versione migliore di te",
    "Werde so akzeptiert, wie du bist" to "Essere accettata/o per come sei",
    "Ein Jahr lang eine Fernbeziehung führen" to "Avere una relazione a distanza per un anno",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Non parlare affatto per un mese",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Vivere momenti intimi solo quando li inizia il tuo partner",
    "Alle intimen Momente selbst initiieren" to "Iniziare tu tutti i momenti intimi",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Condividere i tuoi segreti più profondi con il partner",
    "Einige Dinge für dich behalten" to "Tenere alcune cose per te",
    "Deine Beziehung stabil und sicher machen" to "Rendere la vostra relazione stabile e sicura",
    "Deine Beziehung abenteuerlich und spontan machen" to "Rendere la vostra relazione avventurosa e spontanea",
    "Teile alle deine Hobbys mit deinem Partner" to "Condividere tutti i tuoi hobby con il partner",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Essere introdotta/o dal partner a nuovi hobby",
    "Verbringe die Feiertage mit deiner Familie" to "Trascorrere le feste con la tua famiglia",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Trascorrere le feste con la famiglia del tuo partner",
    "Neue Liebe, neue Erfahrungen" to "Amore nuovo, nuove esperienze",
    "Ich lache viel mit meinem Partner." to "Rido molto con il mio partner.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Mi piace scoprire nuovi hobby o attività con il mio partner.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Mi piace condividere meme e battute con il mio partner.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Do priorità al tempo con il mio partner, anche quando sono impegnata/o.",
    "Ich schreibe meinem Partner jeden Tag." to "Scrivo al mio partner ogni giorno.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Mi piace condividere tutti i dettagli della mia giornata con il mio partner.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Mi piace conoscere gli hobby e gli interessi del mio partner.",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Mi infastidisce quando il mio partner impiega troppo tempo a rispondere ai messaggi.",
    "Ich plane gerne Dates mit meinem Partner." to "Mi piace organizzare appuntamenti con il mio partner.",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Adoro guardare con il mio partner film che nessuno dei due ha mai visto.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "Adoro condividere la mia musica preferita con il mio partner.",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "I gesti romantici, come messaggi, bigliettini o regali, mi rendono felice.",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Preferisco le passeggiate romantiche al parco a una serata al cinema.",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Mi piace provare nuovi ristoranti con il mio partner invece di andare sempre negli stessi posti.",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "Una serata accogliente in casa durante un temporale",
    "Ein tolles Date im Freien unter dem Mondlicht" to "Un appuntamento all'aperto sotto la luce della luna",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Andare presto al mattino a vedere l'alba",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Andare in un bar sulla spiaggia per vedere il tramonto",
    "Gourmet Eis-Sorten" to "Gelati gourmet",
    "6 Monate im Altbau mit Charme" to "6 mesi in un edificio d'epoca pieno di fascino",
    "Entwickler Studio" to "Studio sviluppatore",
    "Ordner rein · Paare raus · Export für AI Studio" to "Cartella dentro · coppie fuori · esportazione per AI Studio",
    "Je zwei Bilder werden ein Paar. Die Reihenfolge unten ist die Reihenfolge im Spiel — " to "Ogni due immagini formano una coppia. L'ordine qui sotto è l'ordine nel gioco —",
    "verschiebe Zeilen mit den Pfeilen, wenn ein Paar nicht passt." to "sposta le righe con le frecce se una coppia non funziona.",
    "Ein Bild bleibt übrig und wird ignoriert." to "Rimane una foto che viene ignorata.",
    "Dateinamen wie 01a_vanille.jpg / 01b_schoko.jpg werden automatisch als Paar erkannt. " to "I nomi file come 01a_vanille.jpg / 01b_schoko.jpg vengono riconosciuti automaticamente come coppia.",
    "Sonst zählt die alphabetische Reihenfolge." to "Altrimenti conta l'ordine alfabetico.",
    "Name (optional - leer lassen für kein Text)" to "Nome (facoltativo - lascia vuoto per nessun testo)",
    "Paare — tippe auf ein Bild, um es zu tauschen" to "Coppie — tocca un'immagine per scambiarla",
    "Antworten, getrennt mit |" to "Risposte, separate da |",
    "Bilder & Städte" to "Immagini e città",
    "Jede Option aus allen Spielen. Tippen und ein eigenes Bild aus der Galerie wählen." to "Ogni opzione di tutti i giochi. Tocca e scegli un'immagine personalizzata dalla galleria.",
    "Mindestens zwei Bilder auswählen." to "Seleziona almeno due immagini.",
    "Dem Spiel fehlt noch ein Titel." to "Al gioco manca ancora un titolo.",
    "Über 3 MB — nimm eine kleinere Bildgröße oder exportiere die Pakete einzeln." to "Oltre 3 MB — usa immagini più piccole o esporta i pacchetti separatamente.",
    "Keine eigenen Bilder vorhanden." to "Non ci sono immagini personali.",
    "Startet ein Spiel im echten Runner — genau so, wie ihr es später spielt." to "Avvia un gioco nel runner reale — esattamente come lo giocherete più tardi.",
    "Eine einzige Textdatei mit Paketen und Bildern. AI Studio nimmt keine ZIPs — " to "Un unico file di testo con pacchetti e immagini. AI Studio non accetta ZIP —",
    "deshalb stecken die Bilder als Base64 direkt im Kotlin-Code." to "perciò le immagini sono direttamente nel codice Kotlin come Base64.",
    "Noch nichts zum Exportieren. Leg im Tab \"Ordner\" ein erstes Paket an." to "Non c'è ancora nulla da esportare. Crea un primo pacchetto nella scheda “Cartella”.",
    "Pakete (nichts ausgewählt = alle)" to "Pacchetti (nessuna selezione = tutti)",
    "Enthält alle Spiele, Ketten, Kategorien UND alle eingebetteten Bilder als Base64. Ideal zur Sicherung, Übertragung & Wiederherstellung." to "Contiene tutti i giochi, le catene, le categorie E tutte le immagini incorporate come Base64. Ideale per salvataggio, trasferimento e ripristino.",
    "JSON oder Export-Inhalt (mit Base64) hier einfügen" to "Incolla qui JSON o contenuto esportato (con Base64)",
    "Inhalt & Bilder jetzt einspielen" to "Importa ora contenuti e immagini",
    "🔗 Ketten-Spiele" to "🔗 Giochi a catena",
    "Pakete mit dynamischen Bauanleitungen, die sich aus bisherigen Antworten zusammensetzen." to "Pacchetti con istruzioni dinamiche che si compongono dalle risposte precedenti.",
    "Noch keine Ketten angelegt" to "Non sono ancora state create catene",
    "Erstelle ein Ketten-Paket, um Fragen dynamisch mit bisherigen Antworten zu verknüpfen." to "Crea un pacchetto a catena per collegare dinamicamente le domande alle risposte precedenti.",
    "Kopfzeile (z.B. Weil du {A} gewählt hast …)" to "Intestazione (ad es. Poiché hai scelto {A}…)",
    "Satzmuster (z.B. 6 Monate im {})" to "Schema di frase (ad es. 6 mesi in {})",
    "JSON Backup wird vorbereitet…" to "Si sta preparando il backup JSON…",
    "🎉 JSON inkl. Bildern & Ketten kopiert!" to "🎉 JSON con immagini e catene copiato!",
    "JSON Backup Datei wird erstellt…" to "Creazione del file di backup JSON…",
    "Daten werden eingespielt…" to "Importazione dati in corso…",
    "🏷️ Kategorien & Farben" to "🏷️ Categorie e colori",
    "Satzmuster (z.B. 1 Jahr lang in {})" to "Schema di frase (ad es. 1 anno in {})",
    "Belgische Schokolade" to "Cioccolato belga",
    "In AI Studio hochladen und schreiben: \"Ersetze GeneratedHarmonyContent.kt komplett durch den Inhalt dieser Datei.\"" to "Carica in AI Studio e scrivi: \"Sostituisci completamente GeneratedHarmonyContent.kt con il contenuto di questo file.\"",
    "Schreibe deine eigene Antwort" to "Scrivi la tua risposta",
    "Quiz verlassen?" to "Uscire dal quiz?",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Vuoi davvero uscire dal quiz? I tuoi progressi finora resteranno salvati.",
    "Schreib frei, was dir wirklich dazu einfällt." to "Scrivi liberamente ciò che ti viene davvero in mente.",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Avete scoperto differenze sorprendenti? Parlatene: perché alcune opzioni vi piacciono di più!",
    "✕ Schließen" to "✕ Chiudi",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "Qui non c'è nulla al momento.\nCambia il filtro o scegli un altro argomento.",
    "✨ GFK-Brücke" to "✨ Ponte CNV",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "Riformulate il vostro testo in modo non violento: osservazione, sentimento, bisogno, richiesta.",
    "Was möchtest du eigentlich sagen?" to "Cosa vorresti davvero dire?",
    "In Chat einfügen" to "Inserisci nella chat",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Analizza le vostre risposte e chat secondo Gottman e CNV.",
    "Wünsche? z.B. günstig, draußen" to "Desideri? Ad es. economico, all'aperto",
    "Spiele & Städte bearbeiten, Ordner reinladen, Bilder anpassen" to "Modifica giochi e città, carica cartelle, adatta le immagini",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "Non ci sono ancora momenti.\nConservate la vostra prima esperienza 💞",
    "Ein Harmony-Meilenstein eurer Liebe." to "Una pietra miliare dell'amore in Harmony.",
    "Was wollt ihr nie vergessen?" to "Cosa non volete mai dimenticare?",
    "🟠 Du bist dran" to "🟠 Tocca a te",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Rispondete alle domande contemporaneamente — le risposte diventano visibili solo quando avete finito entrambi.",
    "Wir" to "Noi",
    "Hey du 💕 wie war dein Tag?" to "Ehi amore 💕 com'è andata la tua giornata?",
    "Stressig — aber jetzt wird’s besser ☺️" to "Stressante — ma ora va meglio ☺️",
    "Ich hab schon an unser Wiedersehen gedacht 🥹" to "Ho già pensato al nostro prossimo incontro 🥹",
    "Unser erstes Videodate" to "Il nostro primo appuntamento in video",
    "Vier Stunden geredet und die Zeit vergessen." to "Abbiamo parlato per quattro ore e perso completamente la cognizione del tempo.",
    "Überraschungspaket" to "Pacchetto sorpresa",
    "Kekse und ein Brief — ich musste weinen vor Freude." to "Biscotti e una lettera — ho pianto di gioia.",
    "Das klingt schön 🥰" to "Che bello 🥰",
    "Ich vermiss dich gerade richtig" to "Mi manchi davvero tanto adesso",
    "Erzähl mir mehr davon 💕" to "Raccontami di più 💕",
    "Haha du bringst mich immer zum Lachen 😄" to "Ahah, mi fai sempre ridere 😄",
    "Können wir heute Abend telefonieren?" to "Possiamo sentirci stasera?",
    "Ich denk so oft an dich ❤️" to "Penso così spesso a te ❤️",
    "Gemini API Key ist nicht konfiguriert. Bitte füge deinen GEMINI_API_KEY im AI Studio Secrets Panel ein." to "La chiave API Gemini non è configurata. Aggiungi GEMINI_API_KEY nel pannello Secrets di AI Studio.",
    "Keine Antwort erhalten." to "Nessuna risposta ricevuta.",
    "Namen und Startdatum eurer Beziehung." to "I vostri nomi e la data d'inizio della relazione."
)
