package com.example.ui

/**
 * Complete Italian Harmony catalog.
 *
 * The entries preserve the German display source as the lookup key. User-entered
 * names, messages and answers intentionally remain unchanged at runtime.
 */
internal val EXACT_ITALIAN_CONTENT: Map<String, String> = mapOf(
    "Tiere" to "Animali",
    "Wer würde eher?" to "Chi preferirebbe?",
    "Zeichnen" to "Disegno",
    "Das oder das?" to "Questo o quello?",
    "Das oder das" to "Questo o quello",
    "Zustimmen oder Ablehnen" to "D'accordo / Non d'accordo",
    "Ich habe noch nie" to "Non l'ho mai fatto",
    "Was magst du lieber?" to "Cosa ti piace di più?",
    "Antwort mit einem Foto" to "Rispondi con una foto",
    "Tiefe Gespräche" to "Conversazioni profonde",
    "Reden vor ..." to "Discorsi davanti a...",
    "Aufwärmen" to "Riscaldarsi",
    "Beziehung" to "Relazione",
    "Sex & Liebe" to "Sesso e amore",
    "Moralische Werte" to "Valori morali",
    "Geld & Finanzen" to "Denaro e finanza",
    "Einander kennenlernen" to "Conosciamoci",
    "Reisen" to "Viaggio",
    "Familie" to "Famiglia",
    "Hobbys" to "Hobby",
    "unterhaltung" to "Intrattenimento",
    "dasoderdas" to "Questo o quello",
    "hochzeit" to "Matrimonio",
    "kinder" to "Bambini",
    "reden" to "Parlare",
    "reisen" to "Viaggio",
    "familie" to "Famiglia",
    "Zuhause & Alltag" to "Casa e vita quotidiana",
    "Was gefällt dir an deinem Zuhause am besten?" to "Cosa ti piace di più della tua casa?",
    "Die Gemütlichkeit und Ruhe" to "L'intimità e la pace",
    "Dass alles meinen Stil hat" to "Che tutto ha il mio stile",
    "Die Menschen, die darin wohnen" to "Le persone che vivono lì",
    "Der Blick nach draußen" to "La vista fuori",
    "Welcher Raum sagt am meisten über dich aus?" to "Quale stanza dice di più di te?",
    "Küche" to "Cucina",
    "Schlafzimmer" to "Camera da letto",
    "Wohnzimmer" to "Soggiorno",
    "Mein Arbeitsplatz" to "Il mio posto di lavoro",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "Cosa cambieresti immediatamente se il denaro non fosse un problema?",
    "Größere Küche" to "Cucina più grande",
    "Ein Balkon oder Garten" to "Un balcone o un giardino",
    "Bessere Lage" to "Posizione migliore",
    "Nichts — es passt so" to "Niente: va bene così",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "Come sarà la tua domenica perfetta a casa?",
    "Ausschlafen und nichts tun" to "Dormi fino a tardi e non fare nulla",
    "Kochen und Freunde einladen" to "Cucina e invita gli amici",
    "Serienmarathon auf dem Sofa" to "Maratona di serie sul divano",
    "Aufräumen und Projekte angehen" to "Ripulire e affrontare i progetti",
    "Der perfekte Heiratsantrag" to "La proposta di matrimonio perfetta",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "Quale ambiente vorresti per una proposta?",
    "Zu Hause, gemütlich und privat" to "A casa, accogliente e privato",
    "Draußen mit der Natur als Kulisse" to "Fuori con la natura come sfondo",
    "Schickes Restaurant oder Hotel" to "Ristorante o hotel chic",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "Preferisci una proposta pubblica o privata?",
    "Nur wir beide" to "Solo noi due",
    "Mit Familie und engen Freunden" to "Con la famiglia e gli amici più cari",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "In un luogo pubblico con molti spettatori",
    "Soll der Antrag eine Überraschung sein?" to "La proposta dovrebbe essere una sorpresa?",
    "Ja, komplett überraschend" to "Sì, completamente sorprendente",
    "Lieber vorher grob absprechen" to "È meglio discutere approssimativamente in anticipo",
    "Wir entscheiden es gemeinsam" to "Decidiamo insieme",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "Quanto è importante per te che il momento venga catturato?",
    "Sehr wichtig — Fotos und Video" to "Molto importante: foto e video",
    "Ein paar Handyfotos reichen" to "Bastano poche foto scattate con il cellulare",
    "Gar nicht, der Moment gehört uns" to "Niente affatto, il momento è nostro",
    "Vorlieben für den Antrag" to "Preferenze per la proposta",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "Preferisci una proposta stravagante o qualcosa di discreto?",
    "Übertrieben und großartig" to "Esagerato e fantastico",
    "Mittelweg mit besonderen Details" to "Terra di mezzo con dettagli speciali",
    "Einfach und intim" to "Semplice e intimo",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "Cosa ne pensi degli oggetti di scena (ad esempio cartelli, palloncini, ecc.)?",
    "Liebe sie, macht mehr Spaß" to "Li adoro, più divertente",
    "Vielleicht ein oder zwei" to "Forse uno o due",
    "Nein, zu ablenkend" to "No, troppo distraente",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "Vuoi che il momento venga condiviso immediatamente sui social media?",
    "Ja, sofort teilen" to "Sì, condividi immediatamente",
    "Nein, erstmal privat halten" to "No, tienilo privato per ora",
    "Erst nur enge Freunde/Familie" to "All'inizio solo amici intimi/familiari",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "Quanto è importante per te che l'applicazione rifletta i tuoi hobby o interessi?",
    "Sehr wichtig, es sollte persönlich sein" to "Molto importante, dovrebbe essere personale",
    "Etwas, eine kleine Note wäre schön" to "Qualcosa, un piccolo tocco sarebbe carino",
    "Nicht nötig, lieber klassisch bleiben" to "Non è necessario, meglio restare sul classico",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "Preferiresti proporre una vacanza (che coinvolge il viaggio)?",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "Sì, in una città o attrazione emozionante",
    "Vielleicht, wenn es machbar ist" to "Forse, se è fattibile",
    "Nein, lieber vor Ort" to "No, meglio sul posto",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "Quanto tempo dopo la proposta vuoi festeggiare con gli altri?",
    "Am selben Tag mit Freunden/Familie" to "Lo stesso giorno con amici/familiari",
    "Etwa eine Woche später, erst mal nur wir" to "Circa una settimana dopo, all'inizio solo noi",
    "Keine Party nötig, privat halten" to "Non è necessaria alcuna festa, mantienilo privato",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "Desideri una lettera scritta come parte della domanda?",
    "Ja, etwas zum Lesen und Aufbewahren" to "Sì, qualcosa da leggere e conservare",
    "Vielleicht, aber mündlich reicht" to "Forse, ma verbalmente è sufficiente",
    "Nein, einfach halten" to "No, tienilo e basta",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "La domanda deve contenere elementi culturali o tradizionali?",
    "Ja, Traditionen einbinden" to "Sì, incorpora le tradizioni",
    "Ein paar kulturelle Anklänge sind okay" to "Alcuni riferimenti culturali vanno bene",
    "Nein, modern halten" to "No, mantienilo moderno",
    "Was ist das Wichtigste beim Antrag?" to "Qual è la cosa più importante quando si applica?",
    "Die Umgebung und Atmosphäre" to "L'ambiente e l'atmosfera",
    "Die Worte und Emotionen" to "Le parole e le emozioni",
    "Der Ring und die Geste" to "L'anello e il gesto",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "Desideri che gli animali domestici siano inclusi nella domanda?",
    "Ja, sie gehören zur Familie!" to "Sì, sono una famiglia!",
    "Vielleicht, wenn es passt" to "Forse, se va bene",
    "Nein, nur wir" to "No, solo noi",
    "Diskutiere vor dem Kinderkriegen" to "Discutere prima di avere figli",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "Siamo in grado di coprire tutti i costi per uno/più bambini? 💰",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "Potrebbe essere necessario risparmiare",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "Avremo abbastanza tempo per il bambino/i? ⏳",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "Sì, faremo in modo che il tempo trascorso in famiglia sia una priorità.",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "Come troveremo il tempo per la nostra relazione una volta arrivato il bambino?",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "Pianifica date o orari regolari insieme",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "Come vuoi che sia il nostro futuro?",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "Viaggia insieme per il mondo, esplora nuove culture e cucine",
    "Wie würdest du sie/ihn nennen?" to "Come lo chiameresti?",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "Vuoi una ragazza o un ragazzo? 👶",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "Cosa ne sarà di nostro figlio quando sarà grande?",
    "Vor der Anschaffung eines Haustiers besprechen" to "Discutere prima di acquistare un animale domestico",
    "Wer übernimmt die tägliche Versorgung?" to "Chi si occupa della cura quotidiana?",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "Cosa succede all'animale quando viaggiamo?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "Che budget pianifichiamo per cibo e veterinario?",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "Un animale rientra nella nostra vita quotidiana?",
    "Vor der gemeinsamen Reise besprechen" to "Discutere prima di viaggiare insieme",
    "Wie viel wollen wir insgesamt ausgeben?" to "Quanto vogliamo spendere in totale?",
    "Lieber durchgeplant oder spontan?" to "Preferiresti che fosse pianificato o spontaneo?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "Quanto tempo vogliamo trascorrere separati?",
    "Was ist für jeden von uns das absolute Highlight?" to "Qual è il momento clou assoluto per ognuno di noi?",
    "Vor dem Kauf eines Hauses besprechen" to "Discutere prima di acquistare una casa",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "Quanto credito possiamo realisticamente permetterci?",
    "Stadt oder Land — was ist uns wichtiger?" to "Città o paese: cosa è più importante per noi?",
    "Wie lange wollen wir dort mindestens bleiben?" to "Almeno quanto tempo vogliamo restare lì?",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "Chi si occupa della ristrutturazione e della manutenzione?",
    "Reiseziele" to "Destinazioni",
    "Paris, Frankreich" to "Parigi, Francia",
    "Rom, Italien" to "Roma, Italia",
    "Bali, Indonesien" to "Bali, Indonesia",
    "Santorini, Griechenland" to "Santorini, Grecia",
    "London, England" to "Londra, Inghilterra",
    "New York, USA" to "New York, Stati Uniti",
    "Malediven" to "Maldive",
    "Seychellen" to "Seychelles",
    "Tokyo, Japan" to "Tokio, Giappone",
    "Dubai, VAE" to "Dubai, Emirati Arabi Uniti",
    "Venedig, Italien" to "Venezia, Italia",
    "Amsterdam, Niederlande" to "Amsterdam, Paesi Bassi",
    "Lappland, Finnland" to "Lapponia, Finlandia",
    "Island" to "Islanda",
    "Unser Traumhaus" to "La nostra casa dei sogni",
    "Altbau mit Charme" to "Vecchio edificio con fascino",
    "Neubau mit Smart Home" to "Nuovo edificio con casa intelligente",
    "Offene Wohnküche" to "Cucina/soggiorno aperti",
    "Separate Küche" to "Cucina separata",
    "Prasselnder Kamin" to "Camino scoppiettante",
    "Fußbodenheizung" to "Riscaldamento a pavimento",
    "Großer Garten" to "Grande giardino",
    "Sonnige Dachterrasse" to "Terrazza soleggiata sul tetto",
    "Stadtvilla" to "Villa cittadina",
    "Landhaus" to "casa di campagna",
    "Glasfassade" to "Facciata in vetro",
    "Natursteinfassade" to "Facciata in pietra naturale",
    "Penthouse mit Ausblick" to "Attico con vista",
    "Haus am See" to "Casa in riva al lago",
    "Minimalistisches Interieur" to "Interni minimalisti",
    "Landhausstil" to "Stile country",
    "Bibliothek" to "Biblioteca",
    "Heimkino" to "Teatro domestico",
    "Innenpool" to "Piscina coperta",
    "Wellnessbad" to "Bagno benessere",
    "Große Fensterfront" to "Ampia finestra frontale",
    "Privater Innenhof" to "Cortile privato",
    "Tiny House" to "Piccola casa",
    "Mehrgenerationenhaus" to "Casa multigenerazionale",
    "Traumhaus Außenbereich" to "Spazio esterno della casa da sogno",
    "Großer Außenpool" to "Grande piscina all'aperto",
    "Outdoor-Whirlpool" to "Vasca idromassaggio all'aperto",
    "Moderne Grillstation" to "Stazione grill moderna",
    "Gemütliche Feuerstelle" to "Pozzo del fuoco accogliente",
    "Eigenes Gemüsebeet" to "Orto proprio",
    "Bunte Blumenwiese" to "Prato di fiori colorati",
    "Entspannte Hängematte" to "Amaca rilassata",
    "Stilvolles Outdoor-Sofa" to "Elegante divano da esterno",
    "Infinity-Pool" to "Piscina a sfioro",
    "Naturteich" to "Laghetto naturale",
    "Outdoor-Küche" to "Cucina all'aperto",
    "Pizzaofen" to "Forno per pizze",
    "Pergola mit Lounge" to "Pergolato con salotto",
    "Wintergarten" to "Giardino d'inverno",
    "Kräuterbeet" to "Letto alle erbe",
    "Obstgarten" to "frutteto",
    "Dachgarten mit Lounge" to "Giardino pensile con salotto",
    "Mediterraner Innenhof" to "Cortile mediterraneo",
    "Feuerstelle" to "Pozzo del fuoco",
    "Außenkamin" to "Camino esterno",
    "Spielbereich für Kinder" to "Area giochi per bambini",
    "Sportplatz" to "Campo sportivo",
    "Gewächshaus" to "serra",
    "Saunahaus" to "Casa della sauna",
    "Aktivitäten" to "Attività",
    "Wandern" to "Escursionismo",
    "Strandtag" to "Giornata in spiaggia",
    "Konzert" to "Concerto",
    "Kino" to "Cinema",
    "Kochkurs" to "Lezione di cucina",
    "Restaurant" to "Ristorante",
    "Museum" to "Museo",
    "Freizeitpark" to "Parco divertimenti",
    "Essensvorlieben" to "Preferenze alimentari",
    "Pizza" to "Pizza",
    "Pasta" to "Pasta",
    "Sushi" to "Sushi",
    "Burger" to "Hamburger",
    "Süß" to "Dolce",
    "Herzhaft" to "Salato",
    "Selbst kochen" to "Cucinare a casa",
    "Bestellen" to "Ordinare",
    "Verlobungsringe" to "Anelli di fidanzamento",
    "Klassisch Solitär" to "Solitario classico",
    "Vintage verspielt" to "Giocoso d'epoca",
    "Gelbgold" to "Oro giallo",
    "Weißgold" to "Oro bianco",
    "Großer Stein" to "Grande pietra",
    "Filigran & schlicht" to "Filigrana e semplice",
    "Diamant" to "Diamante",
    "Farbedelstein" to "Pietra preziosa colorata",
    "Platin" to "Platino",
    "Roségold" to "Oro rosa",
    "Drei-Stein-Ring" to "Anello con tre pietre",
    "Moderner Solitär" to "Solitario moderno",
    "Ovaler Diamant" to "Diamante ovale",
    "Runder Diamant" to "Diamante rotondo",
    "Schmal & zart" to "Sottile e delicato",
    "Markant & breit" to "Sorprendente e ampio",
    "Moissanit" to "Moissanite",
    "Saphir" to "Zaffiro",
    "Vintage Art déco" to "Art Déco vintage",
    "Modern geometrisch" to "Geometria moderna",
    "Gravur innen" to "Incisione all'interno",
    "Diamanten im Band" to "Diamanti nella fascia",
    "Ohne Stein" to "Senza pietra",
    "Statement-Ring" to "Anello di dichiarazione",
    "Hochzeitssträuße" to "Bouquet da sposa",
    "Weiße Rosen" to "Rose bianche",
    "Pfingstrosen" to "Peonie",
    "Wildblumen" to "Fiori di campo",
    "Klassisch gebunden" to "Rilegatura classica",
    "Groß & üppig" to "Grande e lussureggiante",
    "Klein & zart" to "Piccolo e delicato",
    "Pastell" to "Pastello",
    "Kräftige Farben" to "Colori forti",
    "Traumhochzeit" to "Matrimonio da sogno",
    "Große Feier" to "Grande celebrazione",
    "Kleine Runde" to "Piccolo giro",
    "Am Strand" to "Sulla spiaggia",
    "In den Bergen" to "In montagna",
    "Kirchlich" to "Ecclesiastico",
    "Standesamt & Party" to "Ufficio del registro e partito",
    "Sommerhochzeit" to "Matrimonio estivo",
    "Winterhochzeit" to "Matrimonio invernale",
    "Fragen für jede Gelegenheit" to "Domande per ogni occasione",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "Cosa preferisci: alzarti presto o restare alzato fino a tardi?",
    "Früh aufstehen" to "Alzati presto",
    "Lange wach bleiben" to "Resta sveglio fino a tardi",
    "Kommt auf den Tag an" to "Dipende dal giorno",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "Preferiresti trascorrere una serata tranquilla in due o in compagnia?",
    "Ruhig zu zweit" to "Tranquillo per due",
    "Unter Leuten" to "Tra le persone",
    "Gemischt" to "Misto",
    "Was entspannt dich mehr?" to "Cosa ti rilassa di più?",
    "Musik" to "Musica",
    "Spazieren" to "Cammina",
    "Serie schauen" to "Guarda le serie",
    "Gar nichts tun" to "Non fare assolutamente nulla",
    "Wobei lachst du am meisten?" to "Cosa ti fa ridere di più?",
    "Bei Insider-Witzen" to "Con battute interne",
    "Bei Memes" to "Nei meme",
    "Wenn ich müde bin" to "Quando sono stanco",
    "Über mich selbst" to "Su me stesso",
    "Schnappschüsse aus unserer Liebesgeschichte" to "Istantanee della nostra storia d'amore",
    "Welcher Moment war für dich der Anfang von „uns\"?" to "Quale momento è stato per te l’inizio del “noi”?",
    "Unser erstes Gespräch" to "La nostra prima conversazione",
    "Das erste Treffen" to "Il primo incontro",
    "Der erste Kuss" to "Il primo bacio",
    "Als es einfach klar war" to "Quando era tutto chiaro",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "Quale foto insieme è la vostra preferita?",
    "Das erste Selfie" to "Il primo selfie",
    "Ein Urlaubsfoto" to "Una foto delle vacanze",
    "Ein zufälliger Schnappschuss" to "Un'istantanea casuale",
    "Eins, das nur wir kennen" to "Uno che solo noi conosciamo",
    "Woran erinnerst du dich am lebhaftesten?" to "Cosa ricordi più vividamente?",
    "An einen Geruch" to "Di un odore",
    "An einen Song" to "Di una canzone",
    "An etwas, das ich gesagt habe" to "Riguardo qualcosa che ho detto",
    "An das Gefühl" to "Del sentimento",
    "Aufwärmen: Einander kennenlernen" to "Warm up: conoscersi",
    "Was war dein schönster Moment mit mir bisher?" to "Qual è stato il tuo momento più bello con me finora?",
    "Unser erstes Treffen" to "Il nostro primo incontro",
    "Ein ganz normaler Alltagstag" to "Una giornata di tutti i giorni del tutto normale",
    "Eine gemeinsame Reise" to "Un viaggio insieme",
    "Ein schwerer Moment, den wir geschafft haben" to "Un momento difficile che siamo riusciti a gestire",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "Cosa ti piacerebbe di più fare in una giornata insieme?",
    "Ausschlafen und faulenzen" to "Dormi e ozia",
    "Etwas Neues ausprobieren" to "Prova qualcosa di nuovo",
    "Rausgehen in die Natur" to "Esci nella natura",
    "Freunde treffen" to "Incontra gli amici",
    "Wie fühlst du dich am meisten geliebt?" to "Come ti senti più amato?",
    "Durch Worte" to "Attraverso le parole",
    "Durch Zeit zu zweit" to "Attraverso il tempo insieme",
    "Durch Berührung" to "Al tatto",
    "Durch kleine Gesten" to "Attraverso piccoli gesti",
    "Worauf freust du dich bei uns am meisten?" to "Cosa non vedi l'ora di fare con noi?",
    "Unsere nächste Reise" to "Il nostro prossimo viaggio",
    "Zusammenziehen" to "Andare a convivere",
    "Einfach mehr Alltag" to "Semplicemente più quotidianità",
    "Alles, was noch kommt" to "Tutto ciò che verrà",
    "Wer würde eher zu spät kommen?" to "Chi ha maggiori probabilità di arrivare in ritardo?",
    "Ich" to "Io",
    "Mein Partner" to "Il mio compagno",
    "Beide gleich" to "Entrambi uguali",
    "Keiner von uns" to "Nessuno di noi",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "Chi è più propenso a cedere per primo in una discussione?",
    "Kommt drauf an" to "Dipende",
    "Wir treffen uns in der Mitte" to "Ci incontreremo a metà",
    "Wer würde eher spontan eine Reise buchen?" to "Chi sarebbe più propenso a prenotare un viaggio spontaneamente?",
    "Beide zusammen" to "Entrambi insieme",
    "Niemand ohne Plan" to "Nessuno senza un piano",
    "Wer vergisst eher einen Jahrestag?" to "Chi ha maggiori probabilità di dimenticare un anniversario?",
    "Keiner" to "Nessuno",
    "Beide, aber wir tun so als ob nicht" to "Entrambi, ma facciamo finta di no",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "Non ho mai... cancellato un appuntamento per restare a casa.",
    "Stimmt, noch nie" to "Esatto, mai",
    "Doch, schon mal" to "Sì, già",
    "Öfter als ich zugebe" to "Più spesso di quanto ammetto",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "Non ho mai... guardato di nascosto il telefono del mio partner.",
    "Einmal" to "Una volta",
    "Ich würde es nie tun" to "Non lo farei mai",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "Non ho mai... riformulato un messaggio 10 volte.",
    "Ständig" to "Costantemente",
    "Nur bei wichtigen Themen" to "Solo su argomenti importanti",
    "Was bedeutet Vertrauen für dich konkret?" to "Cosa significa per te nello specifico la fiducia?",
    "Dass ich alles erzählen kann" to "Che posso dire tutto",
    "Dass ich mich nicht sorgen muss" to "Che non devo preoccuparmi",
    "Dass Zusagen gehalten werden" to "Queste promesse vengono mantenute",
    "Alles davon" to "Tutto",
    "Was ist für dich ein absoluter Dealbreaker?" to "Qual è per te un vero e proprio rompicapo?",
    "Lügen" to "Bugie",
    "Respektlosigkeit" to "Mancanza di rispetto",
    "Gleichgültigkeit" to "Indifferenza",
    "Untreue" to "Infedeltà",
    "Wann fühlst du dich mir am nächsten?" to "Quando ti senti più vicino a me?",
    "Beim Reden" to "Mentre parli",
    "In Stille nebeneinander" to "In silenzio uno accanto all'altro",
    "Wenn wir zusammen lachen" to "Quando ridiamo insieme",
    "Wenn es schwierig ist" to "Quando le cose sono difficili",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "Di cosa hai più paura nella nostra relazione?",
    "Uns auseinanderzuleben" to "Per crescere a parte",
    "Missverständnisse" to "Incomprensioni",
    "Die Distanz" to "La distanza",
    "Vor nichts" to "Di niente",
    "Führen wir getrennte oder gemeinsame Konten?" to "Abbiamo conti separati o congiunti?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "Come gestire i diversi redditi?",
    "Wofür sparen wir gemeinsam?" to "Per cosa stiamo risparmiando insieme?",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "Di quanto parliamo prima di effettuare un acquisto?",
    "Nähe & Intimität" to "Vicinanza e intimità",
    "Wann fühlst du dich mir körperlich am nächsten?" to "Quando ti senti fisicamente più vicino a me?",
    "Beim Einschlafen nebeneinander" to "Addormentarsi uno accanto all'altro",
    "Wenn wir uns lange umarmen" to "Quando ci abbracciamo a lungo",
    "Bei einer spontanen Berührung" to "Con un tocco spontaneo",
    "Was fehlt dir über die Distanz am meisten?" to "Cosa ti manca di più della distanza?",
    "Körperliche Nähe" to "Vicinanza fisica",
    "Einfach nebeneinander sein" to "Basta stare uno accanto all'altro",
    "Gemeinsame Nächte" to "Notti insieme",
    "Alltägliche Berührungen" to "Tocchi quotidiani",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "Quanto è facile per te parlare di desideri?",
    "Sehr leicht" to "Molto leggero",
    "Geht so" to "Va così",
    "Eher schwer" to "Piuttosto difficile",
    "Ich übe noch" to "Mi sto ancora esercitando",
    "Was macht einen Moment für dich romantisch?" to "Cosa rende romantico un momento per te?",
    "Aufmerksamkeit" to "attenzione",
    "Überraschung" to "Sorpresa",
    "Vertrautheit" to "Familiarità",
    "Dass wir ungestört sind" to "Che siamo indisturbati",
    "Zeichne für mich" to "Disegna per me",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "Disegna il nostro primo appuntamento: cosa deve assolutamente essere nella foto?",
    "Der Ort" to "Il posto",
    "Was wir gegessen haben" to "Cosa abbiamo mangiato",
    "Unsere Gesichter" to "I nostri volti",
    "Das Wetter an dem Tag" to "Il tempo quel giorno",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "Disegna la casa dei nostri sogni su una riga. Qual è la cosa più sorprendente?",
    "Große Fenster" to "Grandi finestre",
    "Der Garten" to "Il giardino",
    "Ein Herz an der Tür" to "Un cuore alla porta",
    "Zwei Stühle davor" to "Due sedie davanti",
    "Zeichne mich als Tier — welches wäre ich?" to "Disegnami come un animale: cosa sarei?",
    "Katze" to "gatto",
    "Hund" to "Cane",
    "Pinguin" to "Pinguino",
    "Etwas ganz anderes" to "Qualcosa di completamente diverso",
    "Zeichne unser Gefühl zueinander als Symbol." to "Disegna i nostri sentimenti reciproci come un simbolo.",
    "Ein Herz" to "Un cuore",
    "Zwei Kreise, die sich überschneiden" to "Due cerchi che si sovrappongono",
    "Eine Brücke" to "Un ponte",
    "Ein Anker" to "Un'ancora",
    "In einer Beziehung sollte man alles voneinander wissen." to "In una relazione dovreste sapere tutto l'uno dell'altro.",
    "Stimme voll zu" to "Totalmente d'accordo",
    "Eher zu" to "Anche piuttosto",
    "Eher nicht" to "Non proprio",
    "Lehne ab" to "Rifiutare",
    "Man sollte nie streitend einschlafen." to "Non dovresti mai addormentarti litigando.",
    "Getrennte Urlaube tun einer Beziehung gut." to "Le vacanze separate fanno bene a una relazione.",
    "Eifersucht ist ein Zeichen von Liebe." to "La gelosia è un segno d'amore.",
    "Freundschaften mit Ex-Partnern sind okay." to "Le amicizie con gli ex vanno bene.",
    "Tägliche Aktivität" to "Attività quotidiana",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "Come può il tuo partner essere un partner ancora migliore per te?",
    "Kennst du die Essensvorlieben deines Partners?" to "Conosci le preferenze alimentari del tuo partner?",
    "Das tägliche Leben" to "Vita quotidiana",
    "Ich bin noch nie in einem Kino eingeschlafen." to "Non mi sono mai addormentato in un cinema.",
    "Ich habe noch nie!" to "Non l'ho mai fatto!",
    "Ich habe!" to "Ho!",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "Non ho mai cancellato il programma di restare a casa e guardare un programma televisivo.",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "Non ho mai giocato in una squadra sportiva universitaria.",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "Non ho mai dimenticato i vestiti bagnati in lavatrice per qualche giorno.",
    "Ich habe noch nie ein Elektroauto gefahren." to "Non ho mai guidato un'auto elettrica.",
    "Ich habe noch nie einen Nachtzug genommen." to "Non ho mai preso un treno notturno.",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "Non ho mai dovuto correre per prendere un volo in coincidenza.",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "Non ho mai guidato un'auto in un paese straniero.",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "Non ho mai avuto un amico che si è trasferito in un altro paese.",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "Non ho mai trovato un amico che parlasse un'altra lingua madre.",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "Non ho mai cancellato un post sui social media perché non riceveva abbastanza Mi piace.",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "Non ho mai pianto per il finale di uno show televisivo.",
    "Unser Intimleben" to "La nostra vita intima",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "Qual è il modo migliore per il tuo partner di iniziare il sesso con te?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "Cosa pensi delle chiacchiere sporche durante il sesso?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "Qual è la cosa più importante che cerchi in un incontro sessuale?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "Cosa ne pensi del guardare insieme contenuti erotici?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "Qual è il tuo modo preferito per dimostrare affetto al di fuori del sesso?",
    "Beschreibe unser Sexleben mit einem Emoji." to "Descrivi la nostra vita sessuale con un emoji.",
    "Unbeliebte Meinungen" to "Opinioni impopolari",
    "Ananas auf der Pizza schmeckt köstlich." to "L'ananas sulla pizza ha un sapore delizioso.",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "I luoghi turistici famosi sono sempre una delusione.",
    "Geister existieren wirklich." to "I fantasmi esistono davvero.",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "A volte gli spot televisivi sono interessanti da guardare.",
    "Eine neue Sprache zu lernen ist einfach." to "Imparare una nuova lingua è facile.",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "Guardare lo stesso film due volte è una perdita di tempo.",
    "Ehepaar Leben" to "Vita di coppia sposata",
    "Wer ist romantischer?" to "Chi è più romantico?",
    "Wer ist der beste Tänzer?" to "Chi è il miglior ballerino?",
    "Wer gibt mehr Herzlichkeit?" to "Chi dà più calore?",
    "Wer hat den besseren Musikgeschmack?" to "Chi ha gusti migliori in fatto di musica?",
    "Wer findet die besten Restaurants?" to "Chi trova i migliori ristoranti?",
    "Wer hängt mehr an seinen Eltern?" to "Chi è più legato ai propri genitori?",
    "Wer ist besser organisiert?" to "Chi è meglio organizzato?",
    "Wer ist der Beste bei der Filmauswahl?" to "Chi è il migliore nella scelta dei film?",
    "Wer kocht besser?" to "Chi cucina meglio?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "Chi è il migliore nel pianificare appuntamenti romantici?",
    "Gesprächsanreger" to "Avviatori di conversazione",
    "Was möchtest du, dass dein Partner öfter tut?" to "Cosa vorresti che il tuo partner facesse più spesso?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "Qual è la tua foto preferita di noi? 📸",
    "Welches Lied macht dich an? 🥵" to "Quale canzone ti eccita? 🥵",
    "Was magst du an deinem Partner am liebsten?" to "Cosa ti piace di più del tuo partner?",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "Qual è la tua più grande paura nel vivere insieme?",
    "Was hast du von deinem Partner gelernt?" to "Cosa hai imparato dal tuo partner?",
    "Liebe im Gleichgewicht" to "Amore in equilibrio",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "Lascia che il tuo partner ti ispiri a dare il meglio di te",
    "Werde so akzeptiert, wie du bist" to "Fatti accettare per come sei",
    "Ein Jahr lang eine Fernbeziehung führen" to "Avere una relazione a distanza per un anno",
    "Einen Monat lang überhaupt nicht miteinander reden" to "Non ci parliamo affatto da un mese",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "Avere momenti intimi solo quando il tuo partner li avvia",
    "Alle intimen Momente selbst initiieren" to "Inizia tu stesso tutti i momenti intimi",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "Piuttosto condividi i tuoi segreti più profondi con il tuo partner",
    "Einige Dinge für dich behalten" to "Tieni alcune cose per te",
    "Eine Million Dollar gewinnen" to "Vinci un milione di dollari",
    "Eine Million Dollar verdienen" to "Guadagna un milione di dollari",
    "Einen sehr emotionalen Partner haben" to "Avere un partner molto emotivo",
    "Einen sehr logischen Partner haben" to "Avere un partner molto logico",
    "Deine Beziehung stabil und sicher machen" to "Rendi la tua relazione stabile e sicura",
    "Deine Beziehung abenteuerlich und spontan machen" to "Rendi la tua relazione avventurosa e spontanea",
    "Deinen besten Freund verlieren" to "Perdere il tuo migliore amico",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "Perdi tutti i tuoi amici tranne il tuo migliore amico",
    "Teile alle deine Hobbys mit deinem Partner" to "Condividi tutti i tuoi hobby con il tuo partner",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "Essere introdotto a nuovi hobby dal tuo partner",
    "Derjenige sein, der umarmt wird" to "Sii quello che viene abbracciato",
    "Diejenige sein, die umarmt" to "Sii quello che abbraccia",
    "Verbringe die Feiertage mit deiner Familie" to "Trascorri le vacanze con la tua famiglia",
    "Die Feiertage mit der Familie deines Partners verbringen" to "Trascorri le vacanze con la famiglia del tuo partner",
    "Neue Liebe, neue Erfahrungen" to "Nuovo amore, nuove esperienze",
    "Ich lache viel mit meinem Partner." to "Rido molto con il mio partner.",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "Mi piace scoprire nuovi hobby o attività con il mio partner.",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "Mi piace condividere meme e battute con il mio partner.",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "Dò la priorità al tempo trascorso con il mio partner anche quando sono occupato.",
    "Ich schreibe meinem Partner jeden Tag." to "Mando messaggi al mio partner ogni giorno.",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "Mi piace condividere tutti i dettagli della mia giornata con il mio partner.",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "Mi piace conoscere gli hobby e gli interessi del mio partner.",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "Mi dà fastidio quando il mio partner impiega troppo tempo per rispondere ai messaggi.",
    "Ich plane gerne Dates mit meinem Partner." to "Mi piace pianificare gli appuntamenti con il mio partner.",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "Adoro guardare film con il mio partner che nessuno di noi ha mai visto prima.",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "Adoro condividere la mia musica preferita con il mio partner.",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "Gesti romantici come messaggi, appunti o regali mi rendono felice.",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "Preferisco le passeggiate romantiche al parco piuttosto che andare al cinema.",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "Mi piace provare nuovi ristoranti con il mio partner invece di andare sempre negli stessi posti.",
    "Ein Filmabend" to "Una serata al cinema",
    "Ein Spieleabend" to "Una serata di giochi",
    "Ein aktives Abenteuer" to "Un'avventura attiva",
    "Ein entspannender Spa-Tag" to "Una giornata rilassante alle terme",
    "Ein gemütliches Date drinnen" to "Un appuntamento accogliente in casa",
    "Eine Autoreise" to "Un viaggio su strada",
    "Einen Film anschauen" to "Guarda un film",
    "Gemeinsam ein Lego bauen" to "Costruiamo insieme un Lego",
    "Eine Weinverkostung" to "Una degustazione di vini",
    "Eine Schokoladenverkostung" to "Una degustazione di cioccolato",
    "Eine gemütliche Nacht zu Hause" to "Una piacevole serata a casa",
    "Ein Abenteuer in einer neuen Stadt" to "Un'avventura in una nuova città",
    "Zu einem Picknick gehen" to "Andare a un picnic",
    "Zu einem ausgefallenen Abendessen gehen" to "Andare a una cena elegante",
    "Ein romantischer Abend" to "Una serata romantica",
    "Eine Nacht in einem Club" to "Una notte in discoteca",
    "Eine Date-Nacht unter den Sternen" to "Un appuntamento notturno sotto le stelle",
    "Ein romantisches Abendessen bei Kerzenlicht" to "Una cena romantica a lume di candela",
    "In einen Coffeeshop gehen" to "Vai in un bar",
    "In eine Bar gehen" to "Vai in un bar",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "Una serata accogliente in casa durante un temporale",
    "Ein tolles Date im Freien unter dem Mondlicht" to "Un grande appuntamento all'aperto al chiaro di luna",
    "Einen Vergnügungspark erkunden" to "Esplora un parco divertimenti",
    "Ein Museum besuchen" to "Visita un museo",
    "Ein Spieleabend mit Freunden" to "Una serata di gioco tra amici",
    "Ein romantisches Picknick an einem schönen Ort" to "Un picnic romantico in una splendida location",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "Provate insieme una nuova ricetta in cucina",
    "In einem feinen Restaurant essen gehen" to "Mangiare fuori in un bel ristorante",
    "Zelten gehen" to "Vai in campeggio",
    "Einen Wellness-Tag" to "Una giornata di benessere",
    "Einen Tanzkurs besuchen" to "Segui un corso di danza",
    "Eine Wanderung mit Panoramablick machen" to "Fai un'escursione con viste panoramiche",
    "Spiele spielen und Spaß haben" to "Gioca e divertiti",
    "Tiefgründige Gespräche führen" to "Intrattieni conversazioni profonde",
    "Ein Live-Musik-Konzert besuchen" to "Partecipa a un concerto di musica dal vivo",
    "Auf eine Bootsparty gehen" to "Vai a una festa in barca",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "Vai la mattina presto per vedere l'alba",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "Andare in un bar sulla spiaggia per ammirare il tramonto",
    "Gourmet Eis-Sorten" to "Varietà di gelato gourmet",
    "Vanille" to "Vaniglia",
    "Schokolade" to "Cioccolato",
    "Erdbeere" to "Fragola",
    "Zitrone" to "Limone",
    "Stracciatella" to "Stracciatella",
    "Pistazie" to "Pistacchio",
    "Mango Sorbet" to "Sorbetto al mango",
    "Himbeere" to "Lampone",
    "Salted Caramel" to "Caramello salato",
    "Cookie Dough" to "Impasto per biscotti",
    "Hazelnut" to "Nocciola",
    "White Chocolate" to "Cioccolato bianco",
    "Walnuss" to "Noce",
    "Banane" to "Banana",
    "6 Monate im Altbau mit Charme" to "6 mesi in un affascinante edificio antico",
    "📂 Ordner" to "📂 Cartella",
    "📝 Spiele" to "📝 Giochi",
    "🔗 Ketten" to "🔗 Catene",
    "🖼️ Bilder" to "🖼️ Immagini",
    "⚡ Test" to "⚡ Prova",
    "📤 Export" to "📤 Esportazioni",
    "Entwickler Studio" to "Studio per sviluppatori",
    "Ordner rein · Paare raus · Export für AI Studio" to "Cartella in · Accoppia · Esporta per AI Studio",
    "Ordner wird gelesen…" to "La cartella viene letta...",
    "Keine Bilder in diesem Ordner gefunden." to "Nessuna immagine trovata in questa cartella.",
    "Bilder werden gelesen…" to "Le immagini vengono lette...",
    "Bilder-Ordner einlesen" to "Leggi le cartelle di immagini",
    "Je zwei Bilder werden ein Paar. Die Reihenfolge unten ist die Reihenfolge im Spiel —" to "Ogni due immagini diventano una coppia. L'ordine seguente è l'ordine nel gioco:",
    "verschiebe Zeilen mit den Pfeilen, wenn ein Paar nicht passt." to "sposta le righe con le frecce se una coppia non corrisponde.",
    "Ordner" to "cartella",
    "Bilder" to "Immagini",
    "Kategorie (z.B. Eis)" to "Categoria (ad esempio gelato)",
    "Name" to "nome",
    "Emoji" to "Emoji",
    "Titel des Spiels" to "Titolo del gioco",
    "Spiel-Emoji" to "Emoji del gioco",
    "Ein Bild bleibt übrig und wird ignoriert." to "Un'immagine rimane e viene ignorata.",
    "Leeren" to "Vuoto",
    "Paket erstellen & freischalten" to "Crea e attiva il pacchetto",
    "Dateinamen wie 01a_vanille.jpg / 01b_schoko.jpg werden automatisch als Paar erkannt." to "I nomi di file come 01a_vanille.jpg / 01b_schoko.jpg vengono automaticamente riconosciuti come una coppia.",
    "Sonst zählt die alphabetische Reihenfolge." to "Altrimenti conta l'ordine alfabetico.",
    "Name (optional - leer lassen für kein Text)" to "Nome (facoltativo: lascia vuoto se non c'è testo)",
    "Nach oben" to "Su",
    "Nach unten" to "Giù",
    "Entfernen" to "Rimuovi",
    "Senden" to "Invia",
    "GFK Brücke" to "Ponte in vetroresina",
    "Spiel suchen…" to "Cerca gioco...",
    "Kategorien & Farben" to "Categorie e colori",
    "Neues Spiel" to "Nuovo gioco",
    "Alle" to "Tutto",
    "⚖️ Das oder Das" to "⚖️ Questo o quello",
    "🧠 Quiz" to "🧠Quiz",
    "🗣️ Diskussion" to "🗣️ Discussione",
    "Das oder Das" to "Questo o quello",
    "Quiz" to "Quiz",
    "Diskussion" to "Discussione",
    "Bearbeiten" to "Modifica",
    "Löschen" to "Elimina",
    "Schließen" to "Chiudi",
    "Spiel bearbeiten" to "Modifica gioco",
    "Speichern" to "Salva",
    "Titel" to "Titolo",
    "Kategorie" to "Categoria",
    "🎨 Farben & Kategorien verwalten" to "🎨 Gestisci colori e categorie",
    "Spieltyp" to "Tipo di gioco",
    "Paare — tippe auf ein Bild, um es zu tauschen" to "Coppie: tocca un'immagine per scambiarla",
    "Paar" to "Coppia",
    "Galerie" to "Galleria",
    "Paare mischen" to "Mescolare le coppie",
    "Fragen" to "Domande",
    "Frage hinzufügen" to "Aggiungi domanda",
    "Paar löschen" to "Elimina coppia",
    "Bild ändern" to "Cambia immagine",
    "Name (optional)" to "Nome (facoltativo)",
    "Fragetext" to "Testo della domanda",
    "Frage löschen" to "Elimina domanda",
    "Antworten, getrennt mit |" to "Risposte separate da |",
    "Bilder & Städte" to "Immagini e città",
    "Jede Option aus allen Spielen. Tippen und ein eigenes Bild aus der Galerie wählen." to "Ogni opzione da tutti i giochi. Tocca e scegli la tua foto dalla galleria.",
    "Option suchen…" to "Opzione di ricerca…",
    "Nur Optionen ohne eigenes Bild" to "Solo opzioni senza la tua immagine",
    "Eigenes Bild" to "Propria foto",
    "Zurücksetzen" to "Ripristina",
    "Schnelltest" to "Prova rapida",
    "Mindestens zwei Bilder auswählen." to "Seleziona almeno due immagini.",
    "Dem Spiel fehlt noch ein Titel." to "Al gioco manca ancora un titolo.",
    "Bilder werden gespeichert…" to "Le immagini vengono salvate...",
    "Bild wird übernommen…" to "L'immagine è stata scattata...",
    "Bilder werden eingelesen…" to "Le immagini vengono lette in...",
    "Bild konnte nicht gelesen werden." to "Impossibile leggere l'immagine.",
    "Keine Pakete zum Exportieren." to "Nessun pacchetto da esportare.",
    "Export wird gebaut…" to "Si costruisce l’export…",
    "Über 3 MB — nimm eine kleinere Bildgröße oder exportiere die Pakete einzeln." to "Oltre 3 MB: utilizza una dimensione dell'immagine più piccola o esporta i pacchetti singolarmente.",
    "Keine eigenen Bilder vorhanden." to "Nessuna foto disponibile.",
    "Startet ein Spiel im echten Runner — genau so, wie ihr es später spielt." to "Inizia una partita nel vero Runner, esattamente come la giocherai in seguito.",
    "Testen" to "Test",
    "Export für Google AI Studio" to "Esporta per Google AI Studio",
    "Eine einzige Textdatei mit Paketen und Bildern. AI Studio nimmt keine ZIPs —" to "Un singolo file di testo contenente pacchetti e immagini. AI Studio non accetta ZIP —",
    "deshalb stecken die Bilder als Base64 direkt im Kotlin-Code." to "Ecco perché le immagini sono in Base64 direttamente nel codice Kotlin.",
    "Noch nichts zum Exportieren. Leg im Tab \"Ordner\" ein erstes Paket an." to "Niente da esportare ancora. Crea un primo pacchetto nella scheda \"Cartella\".",
    "Pakete (nichts ausgewählt = alle)" to "Pacchetti (niente selezionato = tutto)",
    "Bilder mitschicken" to "Invia insieme le immagini",
    "Aus: nur Texte, Datei bleibt winzig" to "Off: solo testi, il file rimane piccolo",
    "Bildgröße im Export" to "Dimensioni dell'immagine nell'esportazione",
    "Klein · 480px" to "Piccolo · 480px",
    "Mittel · 720px" to "Medio · 720px",
    "Groß · 960px" to "Grande · 960px",
    "Für AI Studio exportieren" to "Esporta per AI Studio",
    "Bilder einzeln teilen" to "Condividi le immagini individualmente",
    "Vollständiges Projekt-Backup (JSON)" to "Backup completo del progetto (JSON)",
    "Enthält alle Spiele, Ketten, Kategorien UND alle eingebetteten Bilder als Base64. Ideal zur Sicherung, Übertragung & Wiederherstellung." to "Include tutti i giochi, le catene, le categorie E tutte le immagini incorporate come Base64. Ideale per backup, trasferimento e ripristino.",
    "Kopieren" to "Copia",
    "JSON teilen" to "Condividi JSON",
    "Einspielen" to "Gioca dentro",
    "JSON oder Export-Inhalt (mit Base64) hier einfügen" to "Incolla JSON o esporta contenuto (con Base64) qui",
    "Inhalt & Bilder jetzt einspielen" to "Importa contenuti e immagini adesso",
    "🔗 Ketten-Spiele" to "🔗Giochi a catena",
    "Pakete mit dynamischen Bauanleitungen, die sich aus bisherigen Antworten zusammensetzen." to "Pacchetti con istruzioni per la costruzione dinamiche costituite da risposte precedenti.",
    "Neue Kette" to "Nuova catena",
    "Kette bauen" to "Costruisci una catena",
    "1 Jahr lang in {}" to "per 1 anno a {}",
    "6 Monate im {}" to "6 mesi a {}",
    "Weil du {A} gewählt hast …" to "Perché hai scelto {A}...",
    "Noch keine Ketten angelegt" to "Nessuna catena è stata ancora messa",
    "Erstelle ein Ketten-Paket, um Fragen dynamisch mit bisherigen Antworten zu verknüpfen." to "Crea un pacchetto a catena per collegare dinamicamente le domande alle risposte precedenti.",
    "Spielen" to "Gioca",
    "Kette bearbeiten" to "Modifica catena",
    "Neue Kette erstellen" to "Crea nuova catena",
    "Kopfzeile (z.B. Weil du {A} gewählt hast …)" to "Intestazione (ad es. Perché hai scelto {A}...)",
    "Satzmuster (z.B. 6 Monate im {})" to "Schema della frase (ad esempio 6 mesi in {})",
    "Neuen Schritt hinzufügen" to "Aggiungi un nuovo passaggio",
    "Abbrechen" to "Annulla",
    "Speichern & testen" to "Salva e prova",
    "Quelle wählen:" to "Seleziona fonte:",
    "Gewählt" to "Eletto",
    "Nicht gewählt" to "Non eletto",
    "Feste Option" to "Opzione fissa",
    "Fester Text" to "Testo fisso",
    "Quell-Paket:" to "Pacchetto sorgente:",
    "Türkis" to "Turchese",
    "Limetten grün" to "Verde lime",
    "Kategorie-Farbe wählen" to "Seleziona il colore della categoria",
    "Neue Kategorie erstellen" to "Crea nuova categoria",
    "Kategorie bearbeiten" to "Modifica categoria",
    "Neue Kategorie" to "Nuova categoria",
    "leer" to "vuoto",
    "Kein Paket gewählt" to "Nessun pacchetto selezionato",
    "Gewählte Antwort" to "Risposta selezionata",
    "Verworfene Antwort" to "Risposta rifiutata",
    "beliebiges Paar" to "qualsiasi coppia",
    "Paris oder Rom" to "Parigi o Roma",
    "JSON Backup wird vorbereitet…" to "Il backup JSON è in preparazione...",
    "🎉 JSON inkl. Bildern & Ketten kopiert!" to "🎉 JSON incluse immagini e catene copiate!",
    "JSON Backup Datei wird erstellt…" to "Il file di backup JSON viene creato...",
    "Daten werden eingespielt…" to "I dati vengono importati...",
    "Kette gestartet" to "La catena è iniziata",
    "🔗 Ketten-Bauer" to "🔗 Creatore di catene",
    "Linke Karte (Seite A)" to "Carta sinistra (lato A)",
    "Rechte Karte (Seite B)" to "Carta destra (lato B)",
    "Vorschau:" to "Anteprima:",
    "Paar / Option:" to "Coppia/Opzione:",
    "Beliebiges / letztes Paar" to "Qualsiasi/ultima coppia",
    "Seite:" to "Pagina:",
    "Linke Option (0)" to "Opzione sinistra (0)",
    "Rechte Option (1)" to "Opzione giusta (1)",
    "🏷️ Kategorien & Farben" to "🏷️ Categorie e colori",
    "Titel des Ketten-Spiels" to "Titolo del gioco a catena",
    "Unbenannte Kette" to "Catena senza nome",
    "Verworfen" to "Scartato",
    "Freier Text" to "Testo libero",
    "Satzmuster (z.B. 1 Jahr lang in {})" to "Schemi di frasi (ad esempio per 1 anno in {})",
    "Standardbild" to "Immagine predefinita",
    "eigen" to "Personalizzato",
    "Eis" to "Gelato",
    "Eissorten" to "Gusti di gelato",
    "Gold" to "Oro",
    "Rosa" to "Rosa",
    "Lila" to "Viola",
    "Blau" to "Blu",
    "Koralle" to "Corallo",
    "Smaragd" to "Smeraldo",
    "Rubinrot" to "Rosso rubino",
    "Lavendel" to "Lavanda",
    "Magenta" to "Magenta",
    "Orange" to "Arancione",
    "Neubau mit Technik" to "Nuovo edificio con tecnologia",
    "Offene Küche" to "Cucina aperta",
    "Gemüsebeet" to "Orto",
    "Hängematte" to "Amaca",
    "Blumenwiese" to "Prato fiorito",
    "Dachterrasse" to "Terrazza sul tetto",
    "Grillplatz" to "Zona barbecue",
    "Kamin" to "Camino",
    "Belgische Schokolade" to "Cioccolato belga",
    "In AI Studio hochladen und schreiben: \"Ersetze GeneratedHarmonyContent.kt komplett durch den Inhalt dieser Datei.\"" to "Carica su AI Studio e scrivi: \"Sostituisci interamente GeneratedHarmonyContent.kt con il contenuto di questo file.\"",
    "Fragen & Spiele" to "Domande e giochi",
    "Kategorien" to "Categorie",
    "Themen" to "Argomenti",
    "Für dich empfohlen" to "Consigliato per te",
    "Paar-Statistiken" to "Statistiche di associazione",
    "Gemeinsame Tage" to "Giornate condivise",
    "Beantwortete Fragen" to "Domande con risposta",
    "Besuchte Städte" to "Città visitate",
    "Besuchte Länder" to "Paesi visitati",
    "Widgets" to "Widget",
    "Du fehlst mir" to "Mi manchi",
    "Denke an dich" to "Pensa a te stesso",
    "Ich denke an dich" to "Sto pensando a te",
    "Kuss senden" to "Manda un bacio",
    "Kuss" to "Bacio",
    "ERGEBNISSE" to "RISULTATI",
    "BEANTWORTE" to "RISPOSTA",
    "Alle Pakete" to "Tutti i pacchetti",
    "Profil" to "Profilo",
    "Dein Name" to "Il tuo nome",
    "Partnerin" to "socio",
    "Zusammen seit" to "Insieme da allora",
    "Partner-Simulator" to "Simulatore di partner",
    "Sprache" to "lingua",
    "Deutsch" to "tedesco",
    "Englisch" to "Inglese",
    "Entwickler-Modus" to "Modalità sviluppatore",
    "Entwickler Studio Öffnen" to "Apri Studio per sviluppatori",
    "Profil bearbeiten" to "Modifica profilo",
    "Name Partnerin" to "Nome del socio",
    "Hinzufügen" to "Aggiungi",
    "Momente" to "momenti",
    "Was ist passiert?" to "Cosa è successo?",
    "oder" to "o",
    "Zurück" to "Indietro",
    "Deine eigene Antwort" to "La tua risposta",
    "Deine Antwort..." to "La tua risposta...",
    "Übernehmen" to "Prendi il controllo",
    "Antwortähnlichkeit" to "Rispondi alla somiglianza",
    "Diskutiert eure Antworten" to "Discuti le tue risposte",
    "Fertig!" to "Fatto!",
    "✎ Tippe, um zu antworten" to "✎ Tocca per rispondere",
    "Schreibe deine eigene Antwort" to "Scrivi la tua risposta",
    "Quiz verlassen?" to "Uscire dal quiz?",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "Vuoi davvero abbandonare il quiz? I tuoi progressi precedenti rimangono salvati.",
    "Schreib frei, was dir wirklich dazu einfällt." to "Scrivi liberamente ciò che ti viene veramente in mente.",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "Hai scoperto differenze sorprendenti? Parla del motivo per cui ti piacciono di più determinate opzioni!",
    "✕ Schließen" to "✕ Chiudi",
    "Hier ist gerade nichts. ↵ Wechsle den Filter oder wähle ein anderes Thema." to "Non c'è niente qui adesso. ↵ Cambia il filtro o scegli un argomento diverso.",
    "✨ GFK-Brücke" to "✨ Ponte in vetroresina",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "Riformula la tua bozza in modo non violento: osservazione, sentimento, bisogno, richiesta.",
    "Was möchtest du eigentlich sagen?" to "Cosa vuoi veramente dire?",
    "In Chat einfügen" to "Aggiungi alla chat",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "Analizza le tue risposte e chat secondo Gottman e GFK.",
    "Wünsche? z.B. günstig, draußen" to "Desideri? per esempio. economico, fuori",
    "Spiele & Städte bearbeiten, Ordner reinladen, Bilder anpassen" to "Modifica giochi e città, carica cartelle, regola immagini",
    "🔥 Tägliche Aktivität" to "🔥 Attività quotidiana",
    "+ Hinzufügen" to "+ Aggiungi",
    "Noch keine Momente. ↵ Haltet euer erstes Erlebnis fest 💞" to "Nessun momento ancora. ↵ Cattura la tua prima esperienza 💞",
    "Ein Harmony-Meilenstein eurer Liebe." to "Una pietra miliare dell'armonia del vostro amore.",
    "Was wollt ihr nie vergessen?" to "Cosa non vuoi mai dimenticare?",
    "🟠 Du bist dran" to "🟠 Tocca a te",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "Rispondi alle domande contemporaneamente: le risposte non saranno visibili finché non avrete finito entrambi.",
    "Wir" to "Noi",
    "Hey du 💕 wie war dein Tag?" to "Ehi tu 💕 com'è andata la giornata?",
    "Stressig — aber jetzt wird’s besser ☺️" to "Stressante, ma ora le cose stanno migliorando ☺️",
    "Ich hab schon an unser Wiedersehen gedacht 🥹" to "Stavo già pensando alla nostra riunione 🥹",
    "Unser erstes Videodate" to "Il nostro primo appuntamento video",
    "Vier Stunden geredet und die Zeit vergessen." to "Ho parlato per quattro ore e ho perso la cognizione del tempo.",
    "Überraschungspaket" to "Pacchetto sorpresa",
    "Kekse und ein Brief — ich musste weinen vor Freude." to "Biscotti e una lettera: ho pianto di gioia.",
    "Das klingt schön 🥰" to "Sembra carino 🥰",
    "Ich vermiss dich gerade richtig" to "Mi manchi davvero in questo momento",
    "Erzähl mir mehr davon 💕" to "Raccontatemi di più 💕",
    "Haha du bringst mich immer zum Lachen 😄" to "Ahah mi fai sempre ridere 😄",
    "Können wir heute Abend telefonieren?" to "Possiamo sentirci al telefono stasera?",
    "Ich denk so oft an dich ❤️" to "Ti penso così spesso ❤️",
    "Gemini API Key ist nicht konfiguriert. Bitte füge deinen GEMINI_API_KEY im AI Studio Secrets Panel ein." to "La chiave API Gemini non è configurata. Incolla la tua GEMINI_API_KEY nel pannello AI Studio Secrets.",
    "Keine Antwort erhalten." to "Nessuna risposta ricevuta.",
    "Du bist dran" to "E' il tuo turno",
    "Beantwortet" to "Risposto",
    "Überspringen" to "Salta",
    "Weiter" to "Avanti",
    "KI-Beziehungscoach" to "Allenatore di relazioni con l'intelligenza artificiale",
    "KI-Date-Ideen" to "Idee per appuntamenti AI",
    "Analyse starten" to "Avvia l'analisi",
    "Ideen generieren" to "Generare idee",
    "Namen und Startdatum eurer Beziehung." to "Nome e data di inizio della vostra relazione.",
    "Fertig" to "Fatto",
    "Weiter spielen" to "Continua a giocare",
    "Formuliere um..." to "Riformulare...",
    "Umformulieren" to "Riformulare",
    "Nachricht an \$partnerName..." to "Messaggio a \$partnerName...",
    "✅ Beantwortet" to "✅ Risposto",
    "Verbinde dich mit \$partnerName" to "Connettiti con \$partnerName",
    "1 Jahr zusammen 🎉" to "1 anno insieme 🎉",
    "2 Jahre zusammen 🎉" to "2 anni insieme 🎉",
    "3 Jahre zusammen 🎉" to "3 anni insieme 🎉",
    "\$d Tage zusammen 💞" to "\$d giorni insieme 💞",
    "Moment festhalten" to "Cattura il momento",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "Codice invito: HRM-8731 · tutto sbloccato",
    "✨ KI-Beziehungscoach" to "✨ Allenatore di relazioni con l'intelligenza artificiale",
    "Analysiere eure Muster..." to "Analizza i tuoi schemi...",
    "💡 KI-Date-Ideen" to "💡 Idee per appuntamenti AI",
    "Sammle Ideen..." to "Raccogli idee...",
    "🛠️ Entwickler-Modus" to "🛠️ Modalità sviluppatore",
    "Zusammen seit (TT.MM.JJJJ)" to "Insieme dal (GG.MM.AAAA)",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Le tue risposte vengono salvate. Una volta che \${profile.partnerName} avrà terminato il pacchetto, entrambe le risposte saranno visibili insieme.",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "Connettiti a \${profile.partnerName} per vedere la risposta",
    "Quiz verlassen" to "Lascia il quiz",
    "Ergebnisse" to "Risultati",
    "Unterhaltung" to "Intrattenimento",
    "Hochzeit" to "Matrimonio",
    "Kinder" to "Bambini",
    "Reden vor..." to "Discorsi davanti a...",
    "{ANZAHL} Bilder geladen — Namen prüfen, dann erstellen." to "{ANZAHL} immagini caricate: controlla i nomi, quindi crea.",
    "{ANZAHL} Bilder geladen." to "{ANZAHL} immagini caricate.",
    "{ANZAHL} Paare aus {ANZAHL} Bildern" to "{ANZAHL} coppie di {ANZAHL} immagini",
    "Bild {NUMMER} von {ANZAHL}…" to "Immagine {NUMMER} di {ANZAHL}…",
    "Speichere Bild {NUMMER} von {ANZAHL}…" to "Salva immagine {NUMMER} da {ANZAHL}…",
    "Paar {NUMMER}" to "Accoppia {NUMMER}",
    "Frage {NUMMER}" to "Domanda {NUMMER}",
    "Schritt {NUMMER}" to "Passaggio {NUMMER}",
    "{ANZAHL} Paare" to "{ANZAHL} paia",
    "{ANZAHL} Fragen" to "{ANZAHL} domande",
    "{ANZAHL} Schritt(e)" to "{ANZAHL} passaggio/i",
    "{ANZAHL} Paare · {ANZAHL} Fragen" to "{ANZAHL} coppie · {ANZAHL} domande",
    "{ANZAHL} Einträge" to "{ANZAHL} voci",
    "Fertig: {PAKETE} Pakete · {BILDER} Bilder · {DETAILS}" to "Fatto: {PAKETE} pacchetti · {BILDER} immagini · {DETAILS}",
    "🎉 {ANZAHL} Pakete/Ketten & Bilder erfolgreich eingespielt!" to "🎉 {ANZAHL} pacchetti/catene e immagini importati con successo!",
    "🎉 '{TITEL}' angelegt · {ANZAHL} Paare spielbereit" to "🎉 '{TITEL}' creato · {ANZAHL} coppie pronte per giocare",
    "• A: {OPTION} (Bild: {BILD})" to "• A: {OPTION} (Immagine: {BILD})",
    "• B: {OPTION} (Bild: {BILD})" to "• B: {OPTION} (Immagine: {BILD})",
    "'{TITEL}' gelöscht." to "\"{TITEL}\" eliminato.",
    "'{TITEL}' gespeichert." to "\"{TITEL}\" salvato.",
    "Kategorie '{TITEL}' gespeichert." to "Categoria \"{TITEL}\" salvata.",
    "Kette '{TITEL}' gespeichert." to "Catena \"{TITEL}\" salvata.",
    "Kette '{TITEL}' gelöscht." to "Catena \"{TITEL}\" eliminata.",
    "Bild für '{OPTION}' gesetzt." to "Immagine impostata per \"{OPTION}\".",
    "Eigenes Bild für '{OPTION}' entfernt." to "Immagine personalizzata rimossa per '{OPTION}'.",
    "{EMOJI} „{WIDGET}“ an {PARTNER} gesendet" to "{EMOJI} \"{WIDGET}\" inviato a {PARTNER}",
    "6 Monate im {ORT}" to "6 mesi a {ORT}",
    "1 Jahr lang in {ORT}" to "1 anno a {ORT}",
    "Weil du {OPTION} gewählt hast …" to "Poiché hai scelto {OPTION}...",
    "Verbinde dich mit {PARTNER}, um die Antwort zu sehen" to "Connettiti a {PARTNER} per vedere la risposta",
    "Verbinde dich mit {PARTNER}" to "Connettiti con {PARTNER}",
    "Deine Antworten sind gespeichert. Sobald {PARTNER} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "Le tue risposte vengono salvate. Non appena {PARTNER} termina il pacchetto, entrambe le risposte saranno visibili insieme.",
    "Fehler bei der Umformulierung: {FEHLER}" to "Errore di riformulazione: {FEHLER}",
    "Fehler bei der Analyse: {FEHLER}" to "Errore di analisi: {FEHLER}",
    "Fehler bei der Ideengenerierung: {FEHLER}" to "Errore nella generazione dell'idea: {FEHLER}",
    "{EMOJI} {INHALT}" to "{EMOJI} {INHALT}",
    "{NUMMER}. {INHALT}" to "{NUMMER}. {INHALT}",
    "Tauche ins Unterbewusstsein" to "Immergiti nel subconscio",
    "HARMONY" to "ARMONIA",
    "Home" to "Casa",
    "Chat" to "Chatta",
    "Dev" to "Dev",
    "Jerome" to "Jerome",
    "Alex" to "Alex",
    "OR" to "O",
    "VS" to "VS"
)
