package com.example.ui

/** Complete Japanese locale pack. Canonical German keys, IDs and placeholders stay unchanged. */
internal val EXACT_JAPANESE_CONTENT: Map<String, String> = mapOf(
    "Tiere" to "動物",
    "Wer würde eher?" to "どちらがやりそう？",
    "Zeichnen" to "お絵描き",
    "Das oder das?" to "これかあれか？",
    "Das oder das" to "これかあれか",
    "Zustimmen oder Ablehnen" to "賛成 / 反対",
    "Ich habe noch nie" to "一度もしたことがない",
    "Was magst du lieber?" to "どちらが好き？",
    "Antwort mit einem Foto" to "写真で答える",
    "Tiefe Gespräche" to "深い会話",
    "Reden vor ..." to "…の前に話す",
    "Aufwärmen" to "ウォームアップ",
    "Beziehung" to "関係",
    "Sex & Liebe" to "セックスと愛",
    "Moralische Werte" to "道徳的な価値観",
    "Geld & Finanzen" to "お金と家計",
    "Einander kennenlernen" to "お互いを知る",
    "Reisen" to "旅行",
    "Familie" to "家族",
    "Hobbys" to "趣味",
    "unterhaltung" to "エンターテインメント",
    "dasoderdas" to "これかあれか",
    "hochzeit" to "結婚式",
    "kinder" to "子ども",
    "reden" to "話す",
    "reisen" to "旅行",
    "familie" to "家族",
    "Zuhause & Alltag" to "家庭と日常生活",
    "Was gefällt dir an deinem Zuhause am besten?" to "あなたの家で一番気に入っていることは何ですか?",
    "Die Gemütlichkeit und Ruhe" to "居心地の良さと平和",
    "Dass alles meinen Stil hat" to "すべてに私のスタイルがあるということ",
    "Die Menschen, die darin wohnen" to "そこに住む人々は、",
    "Der Blick nach draußen" to "外の景色",
    "Welcher Raum sagt am meisten über dich aus?" to "あなたについて最も印象に残る部屋はどれですか?",
    "Küche" to "台所",
    "Schlafzimmer" to "寝室",
    "Wohnzimmer" to "リビングルーム",
    "Mein Arbeitsplatz" to "私の職場",
    "Was würdest du sofort ändern, wenn Geld keine Rolle spielt?" to "お金に問題がなかったら、すぐに何を変えますか?",
    "Größere Küche" to "より大きなキッチン",
    "Ein Balkon oder Garten" to "バルコニーまたは庭園",
    "Bessere Lage" to "より良いロケーション",
    "Nichts — es passt so" to "何もない - それはそのようにフィットします",
    "Wie sieht dein perfekter Sonntag zuhause aus?" to "家で過ごす完璧な日曜日はどんな感じですか?",
    "Ausschlafen und nichts tun" to "何もせずに寝てください",
    "Kochen und Freunde einladen" to "料理をして友達を招待する",
    "Serienmarathon auf dem Sofa" to "ソファーでのシリーズマラソン",
    "Aufräumen und Projekte angehen" to "クリーンアップしてプロジェクトに取り組む",
    "Der perfekte Heiratsantrag" to "理想のプロポーズ",
    "Welche Umgebung würdest du dir für einen Antrag wünschen?" to "どんな場所でプロポーズしたいですか？",
    "Zu Hause, gemütlich und privat" to "自宅で、居心地よく、プライベートに",
    "Draußen mit der Natur als Kulisse" to "自然を背景にした屋外",
    "Schickes Restaurant oder Hotel" to "おしゃれなレストランやホテル",
    "Magst du einen öffentlichen oder privaten Antrag lieber?" to "人前でのプロポーズと、二人きりのプロポーズのどちらが好きですか？",
    "Nur wir beide" to "私たち二人だけで",
    "Mit Familie und engen Freunden" to "家族や親しい友人たちと",
    "An einem öffentlichen Ort mit vielen Zuschauern" to "大勢の観客がいる公共の場で",
    "Soll der Antrag eine Überraschung sein?" to "プロポーズはサプライズであるべきでしょうか？",
    "Ja, komplett überraschend" to "はい、まったく驚きです",
    "Lieber vorher grob absprechen" to "事前に大まかに話し合った方が良い",
    "Wir entscheiden es gemeinsam" to "私たちは一緒に決めます",
    "Wie wichtig ist dir, dass der Moment festgehalten wird?" to "あなたにとって、瞬間を捉えることはどのくらい重要ですか?",
    "Sehr wichtig — Fotos und Video" to "非常に重要 - 写真とビデオ",
    "Ein paar Handyfotos reichen" to "携帯電話の写真数枚で十分です",
    "Gar nicht, der Moment gehört uns" to "そんなことはない、この瞬間は私たちのもの",
    "Vorlieben für den Antrag" to "プロポーズの好み",
    "Bevorzugst du einen extravaganten Antrag oder etwas Dezentes?" to "華やかなプロポーズと控えめなプロポーズ、どちらが好みですか？",
    "Übertrieben und großartig" to "最高で素晴らしい",
    "Mittelweg mit besonderen Details" to "特別なディテールを備えた中間点",
    "Einfach und intim" to "シンプルで親密な雰囲気",
    "Was hältst du von Requisiten (z.B. Schilder, Luftballons, etc.)?" to "小道具 (看板、風船など) についてどう思いますか?",
    "Liebe sie, macht mehr Spaß" to "愛して、もっと楽しく",
    "Vielleicht ein oder zwei" to "たぶん1つか2つ",
    "Nein, zu ablenkend" to "いや、気が散りすぎる",
    "Möchtest du, dass der Moment sofort in den sozialen Medien geteilt wird?" to "その瞬間をソーシャルメディアで即座に共有したいですか?",
    "Ja, sofort teilen" to "はい、すぐに共有します",
    "Nein, erstmal privat halten" to "いいえ、今は非公開にしておいてください",
    "Erst nur enge Freunde/Familie" to "最初は親しい友人/家族だけ",
    "Wie wichtig ist es dir, dass der Antrag deine Hobbys oder Interessen widerspiegelt?" to "プロポーズにあなたの趣味や関心が反映されることは、どれくらい大切ですか？",
    "Sehr wichtig, es sollte persönlich sein" to "非常に重要です。個人的なものでなければなりません",
    "Etwas, eine kleine Note wäre schön" to "何か、ちょっとした触れ合いがいいですね",
    "Nicht nötig, lieber klassisch bleiben" to "必要ありません。クラシックのままの方が良いです",
    "Würdest du einen Antrag im Urlaub bevorzugen (mit Reisen verbunden)?" to "旅行中のプロポーズは好きですか？",
    "Ja, in einer aufregenden Stadt oder Sehenswürdigkeit" to "はい、エキサイティングな街や観光地で",
    "Vielleicht, wenn es machbar ist" to "たぶん、それが実現可能であれば",
    "Nein, lieber vor Ort" to "いいえ、現場での方が良いです",
    "Wie lange nach dem Antrag möchtest du mit anderen feiern?" to "プロポーズからどれくらい経ってから他の人と一緒にお祝いしたいですか？",
    "Am selben Tag mit Freunden/Familie" to "友人/家族と同じ日に",
    "Etwa eine Woche später, erst mal nur wir" to "1週間くらい経って、最初は僕らだけで",
    "Keine Party nötig, privat halten" to "パーティーは必要ありません。プライベートに保ちます",
    "Hättest du gerne einen geschriebenen Brief als Teil des Antrags?" to "プロポーズの一部として、手書きの手紙がほしいですか？",
    "Ja, etwas zum Lesen und Aufbewahren" to "はい、読んで保管しておきたいものがあります",
    "Vielleicht, aber mündlich reicht" to "たぶんだけど口頭で十分だよ",
    "Nein, einfach halten" to "いや、ちょっと待ってください",
    "Sollte der Antrag kulturelle oder traditionelle Elemente enthalten?" to "プロポーズに文化的または伝統的な要素を入れたいですか？",
    "Ja, Traditionen einbinden" to "はい、伝統を取り入れます",
    "Ein paar kulturelle Anklänge sind okay" to "いくつかの文化的参照は問題ありません",
    "Nein, modern halten" to "いいえ、現代的にしてください",
    "Was ist das Wichtigste beim Antrag?" to "プロポーズで最も大切なことは何ですか？",
    "Die Umgebung und Atmosphäre" to "環境と雰囲気",
    "Die Worte und Emotionen" to "言葉も感情も",
    "Der Ring und die Geste" to "指輪とジェスチャー",
    "Möchtest du, dass Haustiere beim Antrag dabei sind?" to "プロポーズにペットも参加してほしいですか？",
    "Ja, sie gehören zur Familie!" to "そう、彼らは家族なのです！",
    "Vielleicht, wenn es passt" to "もしかしたら、それが合えば",
    "Nein, nur wir" to "いいえ、私たちだけです",
    "Diskutiere vor dem Kinderkriegen" to "子どもを産む前に話し合おう",
    "Sind wir in der Lage, alle Kosten für ein Kind/mehrere Kinder zu decken? 💰" to "一人の子供または複数の子供の費用を全額負担することはできますか? 💰",
    "Möglicherweise müssen wir Einsparungen vornehmen" to "節約する必要があるかもしれない",
    "Werden wir genug Zeit für das Kind / die Kinder haben? ⏳" to "子どもたちに十分な時間をとれるでしょうか？ ⏳",
    "Ja, wir werden sicherstellen, dass die Zeit mit der Familie Vorrang hat." to "はい、家族の時間を最優先にいたします。",
    "Wie werden wir Zeit für unsere Beziehung finden, wenn das Baby da ist?" to "赤ちゃんが生まれたら、どうやって二人の関係のための時間を見つけますか？",
    "Regelmäßige Rendezvous oder gemeinsame Zeit einplanen" to "定期的な日付や時間を一緒にスケジュールする",
    "Wie möchtest du, dass unsere Zukunft aussieht?" to "私たちの未来をどのようにしていきたいですか？",
    "Gemeinsam die Welt bereisen, neue Kulturen und Küchen erkunden" to "一緒に世界を旅し、新しい文化や料理を探求しましょう",
    "Wie würdest du sie/ihn nennen?" to "あなたなら彼/彼女を何と呼びますか?",
    "Willst du ein Mädchen oder einen Jungen? 👶" to "女の子が欲しいですか、それとも男の子が欲しいですか？ 👶",
    "Was soll aus unserem Kind werden, wenn es erwachsen ist?" to "うちの子は大きくなったらどうなるのでしょうか？",
    "Vor der Anschaffung eines Haustiers besprechen" to "ペットを購入する前にご相談ください",
    "Wer übernimmt die tägliche Versorgung?" to "毎日の手入れは誰がするのですか？",
    "Was passiert mit dem Tier, wenn wir verreisen?" to "私たちが旅行すると動物はどうなりますか?",
    "Welches Budget planen wir für Futter und Tierarzt ein?" to "食事と獣医のためにどれくらいの予算を計画していますか?",
    "Passt ein Tier überhaupt zu unserem Alltag?" to "動物は私たちの日常生活に溶け込んでいますか？",
    "Vor der gemeinsamen Reise besprechen" to "一緒に旅行する前に話し合う",
    "Wie viel wollen wir insgesamt ausgeben?" to "合計でいくらかかりますか?",
    "Lieber durchgeplant oder spontan?" to "計画的に行うか、自発的に行うか、どちらを好みますか?",
    "Wie viel Zeit wollen wir getrennt verbringen?" to "どれくらいの時間を別々に過ごしたいですか?",
    "Was ist für jeden von uns das absolute Highlight?" to "私たち一人ひとりにとっての絶対的なハイライトは何でしょうか?",
    "Vor dem Kauf eines Hauses besprechen" to "家を買う前に相談しましょう",
    "Wie viel Kredit ist für uns realistisch tragbar?" to "現実的にどれくらいの信用を得ることができるでしょうか?",
    "Stadt oder Land — was ist uns wichtiger?" to "都市と国 – 私たちにとってどちらがより重要ですか?",
    "Wie lange wollen wir dort mindestens bleiben?" to "少なくともどれくらいそこに滞在したいですか？",
    "Wer kümmert sich um Renovierung und Instandhaltung?" to "改修やメンテナンスは誰が行うのですか？",
    "Reiseziele" to "旅行先",
    "Paris, Frankreich" to "パリ、フランス",
    "Rom, Italien" to "ローマ、イタリア",
    "Bali, Indonesien" to "バリ島、インドネシア",
    "Santorini, Griechenland" to "サントリーニ島、ギリシャ",
    "London, England" to "ロンドン、イギリス",
    "New York, USA" to "米国ニューヨーク州",
    "Malediven" to "モルディブ",
    "Seychellen" to "セーシェル",
    "Tokyo, Japan" to "東京、日本",
    "Dubai, VAE" to "ドバイ、アラブ首長国連邦",
    "Venedig, Italien" to "ヴェネツィア、イタリア",
    "Amsterdam, Niederlande" to "アムステルダム、オランダ",
    "Lappland, Finnland" to "ラップランド、フィンランド",
    "Island" to "アイスランド",
    "Unser Traumhaus" to "夢のマイホーム",
    "Altbau mit Charme" to "趣のある古い建物",
    "Neubau mit Smart Home" to "スマートホームを備えた新しい建物",
    "Offene Wohnküche" to "オープンキッチン/リビングルーム",
    "Separate Küche" to "独立したキッチン",
    "Prasselnder Kamin" to "轟音を立てる暖炉",
    "Fußbodenheizung" to "床暖房",
    "Großer Garten" to "広い庭",
    "Sonnige Dachterrasse" to "日当たりのよい屋上テラス",
    "Stadtvilla" to "シティヴィラ",
    "Landhaus" to "カントリーハウス",
    "Glasfassade" to "ガラスのファサード",
    "Natursteinfassade" to "天然石のファサード",
    "Penthouse mit Ausblick" to "眺めの良いペントハウス",
    "Haus am See" to "湖のほとりの家",
    "Minimalistisches Interieur" to "シンプルなインテリア",
    "Landhausstil" to "カントリースタイル",
    "Bibliothek" to "図書館",
    "Heimkino" to "ホームシアター",
    "Innenpool" to "屋内プール",
    "Wellnessbad" to "ウェルネスバス",
    "Große Fensterfront" to "正面に大きな窓",
    "Privater Innenhof" to "専用の中庭",
    "Tiny House" to "小さな家",
    "Mehrgenerationenhaus" to "多世代住宅",
    "Traumhaus Außenbereich" to "ドリームハウスの屋外エリア",
    "Großer Außenpool" to "大きな屋外プール",
    "Outdoor-Whirlpool" to "屋外ホットタブ",
    "Moderne Grillstation" to "モダンなグリルステーション",
    "Gemütliche Feuerstelle" to "居心地の良いファイヤーピット",
    "Eigenes Gemüsebeet" to "独自の野菜畑",
    "Bunte Blumenwiese" to "色とりどりの花の草原",
    "Entspannte Hängematte" to "くつろぎのハンモック",
    "Stilvolles Outdoor-Sofa" to "おしゃれなアウトドアソファ",
    "Infinity-Pool" to "インフィニティプール",
    "Naturteich" to "自然の池",
    "Outdoor-Küche" to "アウトドアキッチン",
    "Pizzaofen" to "ピザ窯",
    "Pergola mit Lounge" to "ラウンジ付きパーゴラ",
    "Wintergarten" to "ウィンターガーデン",
    "Kräuterbeet" to "ハーブベッド",
    "Obstgarten" to "オーチャード",
    "Dachgarten mit Lounge" to "ラウンジ付きの屋上庭園",
    "Mediterraner Innenhof" to "地中海風の中庭",
    "Feuerstelle" to "ファイヤーピット",
    "Außenkamin" to "屋外暖炉",
    "Spielbereich für Kinder" to "子供用の遊び場",
    "Sportplatz" to "スポーツフィールド",
    "Gewächshaus" to "温室",
    "Saunahaus" to "サウナハウス",
    "Aktivitäten" to "活動内容",
    "Wandern" to "ハイキング",
    "Strandtag" to "ビーチの日",
    "Konzert" to "コンサート",
    "Kino" to "シネマ",
    "Kochkurs" to "料理教室",
    "Restaurant" to "レストラン",
    "Museum" to "博物館",
    "Freizeitpark" to "遊園地",
    "Essensvorlieben" to "食べ物の好み",
    "Pizza" to "ピザ",
    "Pasta" to "パスタ",
    "Sushi" to "寿司",
    "Burger" to "国民",
    "Süß" to "甘い",
    "Herzhaft" to "塩味",
    "Selbst kochen" to "家で料理する",
    "Bestellen" to "注文する",
    "Verlobungsringe" to "婚約指輪",
    "Klassisch Solitär" to "クラシックなソリティア",
    "Vintage verspielt" to "ヴィンテージの遊び心",
    "Gelbgold" to "イエローゴールド",
    "Weißgold" to "ホワイトゴールド",
    "Großer Stein" to "大きな石",
    "Filigran & schlicht" to "フィリグリー＆シンプル",
    "Diamant" to "ダイヤモンド",
    "Farbedelstein" to "色の宝石",
    "Platin" to "白金",
    "Roségold" to "ローズゴールド",
    "Drei-Stein-Ring" to "スリーストーンリング",
    "Moderner Solitär" to "モダンなソリティア",
    "Ovaler Diamant" to "オーバルダイヤモンド",
    "Runder Diamant" to "ラウンドダイヤモンド",
    "Schmal & zart" to "スリム＆繊細",
    "Markant & breit" to "印象的でワイド",
    "Moissanit" to "モアサナイト",
    "Saphir" to "サファイア",
    "Vintage Art déco" to "ヴィンテージアールデコ",
    "Modern geometrisch" to "モダンな幾何学模様",
    "Gravur innen" to "内側の彫刻",
    "Diamanten im Band" to "バンド内のダイヤモンド",
    "Ohne Stein" to "石なし",
    "Statement-Ring" to "ステートメントリング",
    "Hochzeitssträuße" to "ウェディングブーケ",
    "Weiße Rosen" to "白いバラ",
    "Pfingstrosen" to "牡丹",
    "Wildblumen" to "野の花",
    "Klassisch gebunden" to "古典的な束縛",
    "Groß & üppig" to "大きくて豊かな",
    "Klein & zart" to "小さくて繊細",
    "Pastell" to "パステル",
    "Kräftige Farben" to "強い色",
    "Traumhochzeit" to "夢のウェディング",
    "Große Feier" to "盛大なお祝い",
    "Kleine Runde" to "小さな丸い",
    "Am Strand" to "ビーチで",
    "In den Bergen" to "山の中で",
    "Kirchlich" to "教会",
    "Standesamt & Party" to "登記所と当事者",
    "Sommerhochzeit" to "夏の結婚式",
    "Winterhochzeit" to "冬の結婚式",
    "Fragen für jede Gelegenheit" to "あらゆる場面での質問",
    "Was magst du lieber: früh aufstehen oder lange wach bleiben?" to "早起きするのと夜更かしするのとどちらが好きですか?",
    "Früh aufstehen" to "早く起きるには",
    "Lange wach bleiben" to "遅くまで起きていてください",
    "Kommt auf den Tag an" to "日によって異なります",
    "Lieber ein ruhiger Abend zu zweit oder unter Leuten?" to "二人で、または複数人で静かな夜を過ごしませんか?",
    "Ruhig zu zweit" to "二人で静かに",
    "Unter Leuten" to "人々の間で",
    "Gemischt" to "混合",
    "Was entspannt dich mehr?" to "もっとリラックスできるものは何ですか？",
    "Musik" to "音楽",
    "Spazieren" to "散歩",
    "Serie schauen" to "時計シリーズ",
    "Gar nichts tun" to "まったく何もしない",
    "Wobei lachst du am meisten?" to "あなたを一番笑わせるのは何ですか?",
    "Bei Insider-Witzen" to "内輪ジョークあり",
    "Bei Memes" to "ミームで",
    "Wenn ich müde bin" to "疲れたとき",
    "Über mich selbst" to "私自身について",
    "Schnappschüsse aus unserer Liebesgeschichte" to "私たちのラブストーリーのスナップショット",
    "Welcher Moment war für dich der Anfang von „uns\"?" to "あなたにとって「私たち」の始まりはどんな瞬間でしたか？",
    "Unser erstes Gespräch" to "私たちの最初の会話",
    "Das erste Treffen" to "最初の会議",
    "Der erste Kuss" to "最初のキス",
    "Als es einfach klar war" to "ちょうどクリアだった頃",
    "Welches gemeinsame Foto ist dein Lieblingsfoto?" to "一緒に撮ったどの写真がお気に入りですか?",
    "Das erste Selfie" to "初めての自撮り",
    "Ein Urlaubsfoto" to "休暇中の写真",
    "Ein zufälliger Schnappschuss" to "ランダムなスナップショット",
    "Eins, das nur wir kennen" to "私たちだけが知っているもの",
    "Woran erinnerst du dich am lebhaftesten?" to "最も鮮明に覚えていることは何ですか?",
    "An einen Geruch" to "匂いの",
    "An einen Song" to "歌の",
    "An etwas, das ich gesagt habe" to "私が言ったことについて",
    "An das Gefühl" to "気持ちの",
    "Aufwärmen: Einander kennenlernen" to "ウォームアップ: お互いを知る",
    "Was war dein schönster Moment mit mir bisher?" to "これまで私と過ごした最高の瞬間は何ですか?",
    "Unser erstes Treffen" to "私たちの最初のミーティング",
    "Ein ganz normaler Alltagstag" to "全く普通の日常",
    "Eine gemeinsame Reise" to "一緒に旅をする",
    "Ein schwerer Moment, den wir geschafft haben" to "私たちが乗り越えた困難な瞬間",
    "Was würdest du an einem gemeinsamen Tag am liebsten machen?" to "一緒に過ごす日に一番やりたいことは何ですか?",
    "Ausschlafen und faulenzen" to "寝てダラダラする",
    "Etwas Neues ausprobieren" to "何か新しいことを試してみる",
    "Rausgehen in die Natur" to "自然の中に出かけましょう",
    "Freunde treffen" to "友達に会う",
    "Wie fühlst du dich am meisten geliebt?" to "あなたはどのようにして最も愛されていると感じますか？",
    "Durch Worte" to "言葉を通して",
    "Durch Zeit zu zweit" to "一緒に時を経て",
    "Durch Berührung" to "タッチで",
    "Durch kleine Gesten" to "小さなジェスチャーを通して",
    "Worauf freust du dich bei uns am meisten?" to "私たちと一番楽しみにしていることは何ですか?",
    "Unsere nächste Reise" to "私たちの次の旅行",
    "Zusammenziehen" to "一緒に住む",
    "Einfach mehr Alltag" to "もっとシンプルに日常生活を",
    "Alles, was noch kommt" to "これから起こるすべてのこと",
    "Wer würde eher zu spät kommen?" to "遅刻する可能性が高いのは誰ですか?",
    "Ich" to "私",
    "Mein Partner" to "私のパートナー",
    "Beide gleich" to "どちらも同じ",
    "Keiner von uns" to "私たちの誰も",
    "Wer würde eher bei einem Streit als Erstes einlenken?" to "議論でどちらが先に譲歩する可能性が高いでしょうか?",
    "Kommt drauf an" to "場合によります",
    "Wir treffen uns in der Mitte" to "真ん中でお会いしましょう",
    "Wer würde eher spontan eine Reise buchen?" to "自発的に旅行を予約する可能性が高いのは誰でしょうか?",
    "Beide zusammen" to "両方一緒に",
    "Niemand ohne Plan" to "計画のない人はいない",
    "Wer vergisst eher einen Jahrestag?" to "記念日を忘れる可能性が高いのは誰ですか?",
    "Keiner" to "なし",
    "Beide, aber wir tun so als ob nicht" to "両方だけど、私たちはそうでないふりをする",
    "Ich habe noch nie … ein Date abgesagt, um zuhause zu bleiben." to "私は家にいるためにデートをキャンセルしたことはありません。",
    "Stimmt, noch nie" to "そうです、決して",
    "Doch, schon mal" to "はい、もう",
    "Öfter als ich zugebe" to "私が認めているよりも頻繁に",
    "Ich habe noch nie … heimlich das Handy meines Partners angeschaut." to "私はパートナーの携帯電話をこっそり見たことはありません。",
    "Einmal" to "一度",
    "Ich würde es nie tun" to "私だったら絶対にそんなことはしないだろう",
    "Ich habe noch nie … eine Nachricht 10x umformuliert." to "私はメッセージを 10 回言い直したことがありません。",
    "Ständig" to "絶え間ない",
    "Nur bei wichtigen Themen" to "重要なトピックのみ",
    "Was bedeutet Vertrauen für dich konkret?" to "あなたにとって信頼とは具体的には何ですか?",
    "Dass ich alles erzählen kann" to "すべてを言えるということ",
    "Dass ich mich nicht sorgen muss" to "心配する必要はないということ",
    "Dass Zusagen gehalten werden" to "約束は守られるということ",
    "Alles davon" to "全部",
    "Was ist für dich ein absoluter Dealbreaker?" to "あなたにとって絶対的な取引の妨げとなるものは何ですか?",
    "Lügen" to "嘘",
    "Respektlosigkeit" to "軽蔑する",
    "Gleichgültigkeit" to "無関心",
    "Untreue" to "不倫",
    "Wann fühlst du dich mir am nächsten?" to "あなたが私を一番近くに感じるのはいつですか？",
    "Beim Reden" to "話しながら",
    "In Stille nebeneinander" to "隣り合って沈黙の中で",
    "Wenn wir zusammen lachen" to "一緒に笑うとき",
    "Wenn es schwierig ist" to "物事が難しいとき",
    "Wovor hast du in unserer Beziehung am meisten Angst?" to "私たちの関係で最も恐れていることは何ですか?",
    "Uns auseinanderzuleben" to "離れていくために",
    "Missverständnisse" to "誤解",
    "Die Distanz" to "距離",
    "Vor nichts" to "何もない",
    "Führen wir getrennte oder gemeinsame Konten?" to "別々のアカウントまたは共同アカウントを持っていますか?",
    "Wie gehen wir mit unterschiedlichen Einkommen um?" to "さまざまな収入にどう対処すればよいでしょうか?",
    "Wofür sparen wir gemeinsam?" to "私たちは何を一緒に節約していますか？",
    "Ab welchem Betrag sprechen wir vor einer Anschaffung?" to "購入前にどれくらいの金額について話しますか?",
    "Nähe & Intimität" to "親密さと親密さ",
    "Wann fühlst du dich mir körperlich am nächsten?" to "物理的に私に最も近いと感じるのはいつですか?",
    "Beim Einschlafen nebeneinander" to "隣り合って眠りにつく",
    "Wenn wir uns lange umarmen" to "長い間抱き合っているとき",
    "Bei einer spontanen Berührung" to "自発的なタッチで",
    "Was fehlt dir über die Distanz am meisten?" to "距離について最も恋しいことは何ですか?",
    "Körperliche Nähe" to "物理的な親密さ",
    "Einfach nebeneinander sein" to "ただ隣にいて",
    "Gemeinsame Nächte" to "一緒に夜を過ごす",
    "Alltägliche Berührungen" to "日常の触れ合い",
    "Wie leicht fällt es dir, über Wünsche zu sprechen?" to "願いについて話すのはどれくらい簡単ですか？",
    "Sehr leicht" to "とても軽い",
    "Geht so" to "順調です",
    "Eher schwer" to "かなり難しい",
    "Ich übe noch" to "まだ練習中です",
    "Was macht einen Moment für dich romantisch?" to "あなたにとってロマンチックな瞬間は何ですか?",
    "Aufmerksamkeit" to "注意",
    "Überraschung" to "驚き",
    "Vertrautheit" to "親しみやすさ",
    "Dass wir ungestört sind" to "私たちが平穏であること",
    "Zeichne für mich" to "私のために描いてください",
    "Zeichne unser erstes Date — was gehört unbedingt aufs Bild?" to "最初のデートの絵を描きます - 写真に必ず含める必要があるものは何ですか?",
    "Der Ort" to "場所",
    "Was wir gegessen haben" to "私たちが食べたもの",
    "Unsere Gesichter" to "私たちの顔",
    "Das Wetter an dem Tag" to "その日の天気は",
    "Zeichne unser Traumhaus in einem Strich. Was ist das Auffälligste?" to "私たちの夢の家を一直線に描きます。最も印象的なことは何ですか?",
    "Große Fenster" to "大きな窓",
    "Der Garten" to "庭園",
    "Ein Herz an der Tür" to "ドアにあるハート",
    "Zwei Stühle davor" to "その前に椅子が２脚",
    "Zeichne mich als Tier — welches wäre ich?" to "私を動物として描いたら、私は何になるでしょうか？",
    "Katze" to "猫",
    "Hund" to "犬",
    "Pinguin" to "ペンギン",
    "Etwas ganz anderes" to "まったく違うもの",
    "Zeichne unser Gefühl zueinander als Symbol." to "お互いへの気持ちをシンボルとして描きます。",
    "Ein Herz" to "心",
    "Zwei Kreise, die sich überschneiden" to "重なる二つの円",
    "Eine Brücke" to "橋",
    "Ein Anker" to "アンカー",
    "In einer Beziehung sollte man alles voneinander wissen." to "恋愛関係では、お互いのことをすべて知っておく必要があります。",
    "Stimme voll zu" to "全く同感",
    "Eher zu" to "むしろあまりにも",
    "Eher nicht" to "むしろそうではない",
    "Lehne ab" to "衰退",
    "Man sollte nie streitend einschlafen." to "議論しながら居眠りしてはいけません。",
    "Getrennte Urlaube tun einer Beziehung gut." to "別々に休暇をとるのは恋愛に良いことです。",
    "Eifersucht ist ein Zeichen von Liebe." to "嫉妬は愛情の表れです。",
    "Freundschaften mit Ex-Partnern sind okay." to "元彼との友情は大丈夫です。",
    "Tägliche Aktivität" to "日々の活動",
    "Wie kann dein Partner ein noch besserer Partner für dich sein?" to "どうすればあなたのパートナーがあなたにとってさらに良いパートナーになれるでしょうか?",
    "Kennst du die Essensvorlieben deines Partners?" to "あなたのパートナーの食べ物の好みを知っていますか？",
    "Das tägliche Leben" to "日常生活",
    "Ich bin noch nie in einem Kino eingeschlafen." to "映画館で眠くなったことは一度もありません。",
    "Ich habe noch nie!" to "やったことがない！",
    "Ich habe!" to "私は持っている！",
    "Ich habe noch nie Pläne abgesagt, um zu Hause zu bleiben und eine Fernsehsendung zu sehen." to "私は家にいてテレビ番組を見る計画をキャンセルしたことはありません。",
    "Ich habe noch nie in einer Universitätssportmannschaft mitgespielt." to "私は大学のスポーツチームでプレーしたことがありません。",
    "Ich habe noch nie die nassen Klamotten für ein paar Tage in der Waschmaschine vergessen." to "濡れた服を数日間洗濯機に入れたことを忘れたことはありません。",
    "Ich habe noch nie ein Elektroauto gefahren." to "私は電気自動車を運転したことがありません。",
    "Ich habe noch nie einen Nachtzug genommen." to "私は夜行列車に乗ったことはありません。",
    "Ich musste noch nie rennen, um einen Anschlussflug zu erwischen." to "乗り継ぎ便に乗るために走らなければならなかったことがありません。",
    "Ich habe noch nie ein Auto in einem fremden Land gefahren." to "私は外国で車を運転したことがありません。",
    "Ich habe noch nie einen Freund gehabt, der in ein anderes Land gezogen ist." to "私には他の国に引っ越した友人が一人もいませんでした。",
    "Ich habe noch nie einen Freund gefunden, der eine andere Muttersprache spricht." to "私は他の母国語を話す友人を見つけたことがありません。",
    "Ich habe noch nie einen Social-Media-Beitrag gelöscht, weil er nicht genug Likes bekommen hat." to "十分な「いいね！」がもらえなかったためにソーシャルメディアの投稿を削除したことはありません。",
    "Ich habe noch nie wegen des Finales einer Fernsehsendung geweint." to "私はテレビ番組の最終回で泣いたことはありません。",
    "Unser Intimleben" to "私たちの親密な生活",
    "Wie kann dein Partner am besten Sex mit dir initiieren?" to "あなたのパートナーがあなたとセックスを始める最善の方法は何ですか?",
    "Wie stehst du zu schmutzigem Gerede beim Sex?" to "セックス中の汚い話についてどう思いますか?",
    "Was ist das Wichtigste, das du bei einer sexuellen Begegnung suchst?" to "性的な出会いにおいてあなたが求める最も重要なことは何ですか?",
    "Was hältst du davon, gemeinsam erotische Inhalte anzuschauen?" to "エロコンテンツを一緒に見ることについてどう思いますか?",
    "Wie zeigst du deine Zuneigung am liebsten außerhalb von Sex?" to "セックス以外で愛情を示すお気に入りの方法は何ですか?",
    "Beschreibe unser Sexleben mit einem Emoji." to "私たちの性生活を絵文字で説明してください。",
    "Unbeliebte Meinungen" to "不人気な意見",
    "Ananas auf der Pizza schmeckt köstlich." to "ピザのパイナップルはおいしいです。",
    "Berühmte Touristenorte sind immer eine Enttäuschung." to "有名な観光地はいつもがっかりします。",
    "Geister existieren wirklich." to "幽霊は本当に存在します。",
    "Fernsehwerbung ist manchmal interessant anzusehen." to "テレビコマーシャルは時々見ると面白いものです。",
    "Eine neue Sprache zu lernen ist einfach." to "新しい言語を学ぶのは簡単です。",
    "Denselben Film zweimal zu schauen, ist Zeitverschwendung." to "同じ映画を二度見るのは時間の無駄です。",
    "Ehepaar Leben" to "夫婦生活",
    "Wer ist romantischer?" to "誰がよりロマンチックですか?",
    "Wer ist der beste Tänzer?" to "最高のダンサーは誰ですか?",
    "Wer gibt mehr Herzlichkeit?" to "誰がより多くの暖かさを与えますか？",
    "Wer hat den besseren Musikgeschmack?" to "音楽のセンスが優れているのは誰ですか?",
    "Wer findet die besten Restaurants?" to "誰が最高のレストランを見つけますか?",
    "Wer hängt mehr an seinen Eltern?" to "どちらの方が両親に愛着を持っていますか?",
    "Wer ist besser organisiert?" to "誰がより組織的に優れていますか?",
    "Wer ist der Beste bei der Filmauswahl?" to "映画を選ぶのが一番上手いのは誰ですか?",
    "Wer kocht besser?" to "誰が料理が上手ですか?",
    "Wer ist der Beste bei der Planung romantischer Dates?" to "ロマンチックなデートを計画するのが得意なのは誰ですか?",
    "Gesprächsanreger" to "会話のきっかけ",
    "Was möchtest du, dass dein Partner öfter tut?" to "パートナーにもっと頻繁にしてもらいたいことは何ですか?",
    "Was ist dein Lieblingsfoto von uns? 📸" to "私たちのお気に入りの写真は何ですか? 📸",
    "Welches Lied macht dich an? 🥵" to "あなたを元気づける曲はどれですか? 🥵",
    "Was magst du an deinem Partner am liebsten?" to "あなたのパートナーの何が一番好きですか?",
    "Was ist deine größte Angst vor dem Zusammenleben?" to "一緒に住むことについて一番怖いことは何ですか?",
    "Was hast du von deinem Partner gelernt?" to "あなたはパートナーから何を学びましたか?",
    "Liebe im Gleichgewicht" to "バランスのとれた愛",
    "Lass dich von deinem Partner inspirieren, dein bestes Selbst zu sein" to "パートナーに最高の自分になるようインスピレーションを与えてもらいましょう",
    "Werde so akzeptiert, wie du bist" to "ありのままに受け入れられる",
    "Ein Jahr lang eine Fernbeziehung führen" to "遠距離恋愛をして1年になります",
    "Einen Monat lang überhaupt nicht miteinander reden" to "一ヶ月全く会話しなかった",
    "Intime Momente nur dann zu haben, wenn dein Partner sie initiiert" to "パートナーが始めたときにのみ親密な瞬間を過ごす",
    "Alle intimen Momente selbst initiieren" to "親密な瞬間はすべて自分で始める",
    "Deine tiefsten Geheimnisse lieber mit deinem Partner teilen" to "むしろ、あなたの最も深い秘密をパートナーと共有してください",
    "Einige Dinge für dich behalten" to "いくつかのことは自分だけのものにしておいてください",
    "Eine Million Dollar gewinnen" to "100万ドルを勝ち取る",
    "Eine Million Dollar verdienen" to "100万ドルを稼ぐ",
    "Einen sehr emotionalen Partner haben" to "非常に感情的なパートナーを持つ",
    "Einen sehr logischen Partner haben" to "非常に論理的なパートナーを持つ",
    "Deine Beziehung stabil und sicher machen" to "あなたの関係を安定させ、安全なものにする",
    "Deine Beziehung abenteuerlich und spontan machen" to "あなたの関係を冒険的で自発的なものにしましょう",
    "Deinen besten Freund verlieren" to "親友を失うこと",
    "Alle deine Freunde verlieren, außer deinem besten Freund" to "親友以外の友達をすべて失う",
    "Teile alle deine Hobbys mit deinem Partner" to "すべての趣味をパートナーと共有する",
    "Von deinem Partner in neue Hobbys eingeführt werden" to "パートナーから新しい趣味を紹介される",
    "Derjenige sein, der umarmt wird" to "抱きしめられる側になってください",
    "Diejenige sein, die umarmt" to "抱きしめる人になってください",
    "Verbringe die Feiertage mit deiner Familie" to "休日は家族と一緒に過ごしましょう",
    "Die Feiertage mit der Familie deines Partners verbringen" to "休日はパートナーの家族と過ごす",
    "Neue Liebe, neue Erfahrungen" to "新しい愛、新しい経験",
    "Ich lache viel mit meinem Partner." to "パートナーと一緒によく笑います。",
    "Ich entdecke gerne neue Hobbys oder Aktivitäten mit meinem Partner." to "パートナーと一緒に新しい趣味や活動を見つけるのが楽しいです。",
    "Ich teile gerne Memes und Witze mit meinem Partner." to "私はパートナーとミームやジョークを共有するのが好きです。",
    "Ich priorisiere es, Zeit mit meinem Partner zu verbringen, auch wenn ich beschäftigt bin." to "たとえ忙しくても、パートナーと過ごす時間を優先します。",
    "Ich schreibe meinem Partner jeden Tag." to "私は毎日パートナーにテキストメッセージを送ります。",
    "Ich teile gerne alle Details meines Tages mit meinem Partner." to "私は、その日のすべての詳細をパートナーと共有するのが好きです。",
    "Ich lerne gerne die Hobbys und Interessen meines Partners kennen." to "私はパートナーの趣味や興味を知るのが好きです。",
    "Es nervt mich, wenn mein Partner zu lange braucht, um auf Nachrichten zu antworten." to "パートナーがメッセージに返信するのに時間がかかりすぎるとイライラします。",
    "Ich plane gerne Dates mit meinem Partner." to "私はパートナーとのデートの計画を立てるのが好きです。",
    "Ich liebe es, Filme mit meinem Partner zu schauen, die keiner von uns zuvor gesehen hat." to "私はパートナーと一緒に、お互いが見たことのない映画を見るのが大好きです。",
    "Ich liebe es, meine Lieblingsmusik mit meinem Partner zu teilen." to "お気に入りの音楽をパートナーと共有するのが大好きです。",
    "Romantische Gesten wie Nachrichten, Zettelchen oder Geschenke machen mich glücklich." to "メッセージ、メモ、プレゼントなどのロマンチックなジェスチャーは私を幸せにします。",
    "Ich bevorzuge romantische Spaziergänge im Park gegenüber einem Kinobesuch." to "私は映画を見に行くよりも、ロマンチックな公園での散歩の方が好きです。",
    "Ich genieße es, mit meinem Partner neue Restaurants auszuprobieren, anstatt immer an die gleichen Orte zu gehen." to "いつも同じ場所に行くのではなく、パートナーと一緒に新しいレストランを試すのが楽しいです。",
    "Ein Filmabend" to "映画の夜",
    "Ein Spieleabend" to "ゲームの夜",
    "Ein aktives Abenteuer" to "アクティブな冒険",
    "Ein entspannender Spa-Tag" to "リラックスしたスパの一日",
    "Ein gemütliches Date drinnen" to "室内での居心地の良いデート",
    "Eine Autoreise" to "ロードトリップ",
    "Einen Film anschauen" to "映画を見る",
    "Gemeinsam ein Lego bauen" to "一緒にレゴを組み立てよう",
    "Eine Weinverkostung" to "ワインの試飲",
    "Eine Schokoladenverkostung" to "チョコレートの試飲",
    "Eine gemütliche Nacht zu Hause" to "自宅で心地よい夜を",
    "Ein Abenteuer in einer neuen Stadt" to "新しい街での冒険",
    "Zu einem Picknick gehen" to "ピクニックに行く",
    "Zu einem ausgefallenen Abendessen gehen" to "豪華なディナーに行く",
    "Ein romantischer Abend" to "ロマンチックな夜",
    "Eine Nacht in einem Club" to "クラブでの一夜",
    "Eine Date-Nacht unter den Sternen" to "星空の下でデートの夜",
    "Ein romantisches Abendessen bei Kerzenlicht" to "キャンドルライトでロマンチックなディナー",
    "In einen Coffeeshop gehen" to "コーヒーショップに行く",
    "In eine Bar gehen" to "バーに行く",
    "Ein gemütlicher Abend im Haus während eines Gewitters" to "雷雨の中、家で過ごす居心地の良い夜",
    "Ein tolles Date im Freien unter dem Mondlicht" to "月明かりの下、屋外で素敵なデート",
    "Einen Vergnügungspark erkunden" to "遊園地を探索する",
    "Ein Museum besuchen" to "美術館を訪ねる",
    "Ein Spieleabend mit Freunden" to "友達とゲームの夜",
    "Ein romantisches Picknick an einem schönen Ort" to "美しいロケーションでロマンチックなピクニック",
    "Gemeinsam in der Küche ein neues Rezept ausprobieren" to "キッチンで一緒に新しいレシピを試してみましょう",
    "In einem feinen Restaurant essen gehen" to "高級レストランでの外食",
    "Zelten gehen" to "キャンプに行く",
    "Einen Wellness-Tag" to "健康の日",
    "Einen Tanzkurs besuchen" to "ダンスのクラスを受ける",
    "Eine Wanderung mit Panoramablick machen" to "パノラマの景色を眺めながらハイキングに出かけましょう",
    "Spiele spielen und Spaß haben" to "ゲームをして楽しんでください",
    "Tiefgründige Gespräche führen" to "深い会話をする",
    "Ein Live-Musik-Konzert besuchen" to "ライブ音楽コンサートに参加する",
    "Auf eine Bootsparty gehen" to "ボートパーティーに行く",
    "Geh früh am Morgen, um den Sonnenaufgang zu sehen" to "日の出を見るために早朝に行きます",
    "In eine Strandbar gehen, um den Sonnenuntergang zu sehen" to "夕日を見にビーチバーに行く",
    "Gourmet Eis-Sorten" to "グルメアイスクリームの種類",
    "Vanille" to "バニラ",
    "Schokolade" to "チョコレート",
    "Erdbeere" to "いちご",
    "Zitrone" to "レモン",
    "Stracciatella" to "ストラッチャテッラ",
    "Pistazie" to "ピスタチオ",
    "Mango Sorbet" to "マンゴーシャーベット",
    "Himbeere" to "ラズベリー",
    "Salted Caramel" to "塩キャラメル",
    "Cookie Dough" to "クッキー生地",
    "Hazelnut" to "ヘーゼルナッツ",
    "White Chocolate" to "ホワイトチョコレート",
    "Walnuss" to "クルミ",
    "Banane" to "バナナ",
    "6 Monate im Altbau mit Charme" to "魅力的な古い建物での6ヶ月間",
    "📂 Ordner" to "📂 フォルダー",
    "📝 Spiele" to "📝 ゲーム",
    "🔗 Ketten" to "🔗 チェーン",
    "🖼️ Bilder" to "🖼️写真",
    "⚡ Test" to "⚡ テスト",
    "📤 Export" to "📤 輸出",
    "Entwickler Studio" to "開発者スタジオ",
    "Ordner rein · Paare raus · Export für AI Studio" to "フォルダーイン · ペアアウト · AI Studio のエクスポート",
    "Ordner wird gelesen…" to "フォルダーを読み取っています...",
    "Keine Bilder in diesem Ordner gefunden." to "このフォルダーには画像が見つかりません。",
    "Bilder werden gelesen…" to "画像が読み込まれます...",
    "Bilder-Ordner einlesen" to "画像フォルダーの読み取り",
    "Je zwei Bilder werden ein Paar. Die Reihenfolge unten ist die Reihenfolge im Spiel —" to "2枚の写真がペアになります。以下の順序はゲーム内での順序です —",
    "verschiebe Zeilen mit den Pfeilen, wenn ein Paar nicht passt." to "ペアが一致しない場合は、矢印を使用して行を移動します。",
    "Ordner" to "フォルダ",
    "Bilder" to "写真",
    "Kategorie (z.B. Eis)" to "カテゴリ (例: アイスクリーム)",
    "Name" to "名前",
    "Emoji" to "絵文字",
    "Titel des Spiels" to "ゲームタイトル",
    "Spiel-Emoji" to "ゲームの絵文字",
    "Ein Bild bleibt übrig und wird ignoriert." to "1 つのイメージが残り、無視されます。",
    "Leeren" to "空の",
    "Paket erstellen & freischalten" to "パッケージの作成とアクティブ化",
    "Dateinamen wie 01a_vanille.jpg / 01b_schoko.jpg werden automatisch als Paar erkannt." to "01a_vanille.jpg / 01b_schoko.jpg のようなファイル名は自動的にペアとして認識されます。",
    "Sonst zählt die alphabetische Reihenfolge." to "それ以外の場合は、アルファベット順が考慮されます。",
    "Name (optional - leer lassen für kein Text)" to "名前 (オプション - テキストを入力しない場合は空白のままにします)",
    "Nach oben" to "上",
    "Nach unten" to "下向き",
    "Entfernen" to "取り除く",
    "Senden" to "送信",
    "GFK Brücke" to "GRPブリッジ",
    "Spiel suchen…" to "検索ゲーム...",
    "Kategorien & Farben" to "カテゴリと色",
    "Neues Spiel" to "新しいゲーム",
    "Alle" to "全て",
    "⚖️ Das oder Das" to "⚖️あれやこれや",
    "🧠 Quiz" to "🧠 クイズ",
    "🗣️ Diskussion" to "🗣️ ディスカッション",
    "Das oder Das" to "あれこれ",
    "Quiz" to "クイズ",
    "Diskussion" to "議論",
    "Bearbeiten" to "編集",
    "Löschen" to "消去",
    "Schließen" to "近い",
    "Spiel bearbeiten" to "ゲームを編集する",
    "Speichern" to "保存",
    "Titel" to "タイトル",
    "Kategorie" to "カテゴリ",
    "🎨 Farben & Kategorien verwalten" to "🎨 色とカテゴリを管理",
    "Spieltyp" to "ゲームの種類",
    "Paare — tippe auf ein Bild, um es zu tauschen" to "ペア — 画像をタップして交換します",
    "Paar" to "カップル",
    "Galerie" to "ギャラリー",
    "Paare mischen" to "ミックスペア",
    "Fragen" to "質問",
    "Frage hinzufügen" to "質問を追加",
    "Paar löschen" to "ペアの削除",
    "Bild ändern" to "イメージを変更する",
    "Name (optional)" to "名前 (オプション)",
    "Fragetext" to "質問文",
    "Frage löschen" to "質問を削除する",
    "Antworten, getrennt mit |" to "| で区切られた回答",
    "Bilder & Städte" to "画像と都市",
    "Jede Option aus allen Spielen. Tippen und ein eigenes Bild aus der Galerie wählen." to "すべてのゲームのすべてのオプション。タップしてギャラリーから自分の写真を選択します。",
    "Option suchen…" to "検索オプション...",
    "Nur Optionen ohne eigenes Bild" to "自分のイメージのないオプションのみ",
    "Eigenes Bild" to "カスタム画像",
    "Zurücksetzen" to "リセット",
    "Schnelltest" to "迅速なテスト",
    "Mindestens zwei Bilder auswählen." to "少なくとも2枚の画像を選んでください。",
    "Dem Spiel fehlt noch ein Titel." to "ゲームにはまだタイトルがありません。",
    "Bilder werden gespeichert…" to "画像が保存されます...",
    "Bild wird übernommen…" to "画像は撮影されています...",
    "Bilder werden eingelesen…" to "画像を読み込んでいます...",
    "Bild konnte nicht gelesen werden." to "画像を読み取れませんでした。",
    "Keine Pakete zum Exportieren." to "エクスポートするパッケージがありません。",
    "Export wird gebaut…" to "エクスポートを構築中です…",
    "Über 3 MB — nimm eine kleinere Bildgröße oder exportiere die Pakete einzeln." to "3MB を超える場合 - より小さい画像サイズを使用するか、パッケージを個別にエクスポートします。",
    "Keine eigenen Bilder vorhanden." to "独自の写真はありません。",
    "Startet ein Spiel im echten Runner — genau so, wie ihr es später spielt." to "後でプレイするのとまったく同じように、実際の Runner でゲームを開始します。",
    "Testen" to "テスト",
    "Export für Google AI Studio" to "Google 用にエクスポート AI Studio",
    "Eine einzige Textdatei mit Paketen und Bildern. AI Studio nimmt keine ZIPs —" to "パッケージとイメージを含む単一のテキスト ファイル。 AI Studio は ZIP を使用しません —",
    "deshalb stecken die Bilder als Base64 direkt im Kotlin-Code." to "画像が Kotlin コード内で直接 Base64 になっているのはそのためです。",
    "Noch nichts zum Exportieren. Leg im Tab \"Ordner\" ein erstes Paket an." to "まだエクスポートするものがありません。\"フォルダー\"タブで最初のパックを作成してください。",
    "Pakete (nichts ausgewählt = alle)" to "パッケージ (何も選択されていない = すべて)",
    "Bilder mitschicken" to "写真も一緒に送る",
    "Aus: nur Texte, Datei bleibt winzig" to "オフ: テキストのみ、ファイルは小さいままです",
    "Bildgröße im Export" to "エクスポート時の画像サイズ",
    "Klein · 480px" to "小・480px",
    "Mittel · 720px" to "中・720px",
    "Groß · 960px" to "大・960px",
    "Für AI Studio exportieren" to "AI Studio のエクスポート",
    "Bilder einzeln teilen" to "画像を個別に共有する",
    "Vollständiges Projekt-Backup (JSON)" to "プロジェクトの完全バックアップ (JSON)",
    "Enthält alle Spiele, Ketten, Kategorien UND alle eingebetteten Bilder als Base64. Ideal zur Sicherung, Übertragung & Wiederherstellung." to "すべてのゲーム、チェーン、カテゴリ、およびすべての埋め込み画像が Base64 として含まれます。バックアップ、転送、復元に最適です。",
    "Kopieren" to "コピー",
    "JSON teilen" to "JSONを共有する",
    "Einspielen" to "プレイイン",
    "JSON oder Export-Inhalt (mit Base64) hier einfügen" to "ここに JSON を貼り付けるか、コンテンツ (Base64 を使用) をエクスポートします",
    "Inhalt & Bilder jetzt einspielen" to "コンテンツと画像を今すぐインポート",
    "🔗 Ketten-Spiele" to "🔗 チェーンゲーム",
    "Pakete mit dynamischen Bauanleitungen, die sich aus bisherigen Antworten zusammensetzen." to "以前の回答から構成される動的な構築手順が含まれたパック。",
    "Neue Kette" to "新しいチェーン",
    "Kette bauen" to "チェーンを構築する",
    "1 Jahr lang in {}" to "{} で 1 年間",
    "6 Monate im {}" to "{} の 6 か月",
    "Weil du {A} gewählt hast …" to "{A} を選択したため...",
    "Noch keine Ketten angelegt" to "まだチェーンはつけていません",
    "Erstelle ein Ketten-Paket, um Fragen dynamisch mit bisherigen Antworten zu verknüpfen." to "これまでの回答と質問を動的につなげるチェーンパックを作成します。",
    "Spielen" to "遊ぶ",
    "Kette bearbeiten" to "チェーンの編集",
    "Neue Kette erstellen" to "新しいチェーンを作成する",
    "Kopfzeile (z.B. Weil du {A} gewählt hast …)" to "ヘッダー (例: {A} を選択したため…)",
    "Satzmuster (z.B. 6 Monate im {})" to "文のパターン (例: {} の 6 か月)",
    "Neuen Schritt hinzufügen" to "新しいステップを追加",
    "Abbrechen" to "キャンセル",
    "Speichern & testen" to "保存してテストする",
    "Quelle wählen:" to "ソースを選択:",
    "Gewählt" to "選ばれた",
    "Nicht gewählt" to "未選出",
    "Feste Option" to "固定オプション",
    "Fester Text" to "固定テキスト",
    "Quell-Paket:" to "ソースパッケージ:",
    "Türkis" to "ターコイズ",
    "Limetten grün" to "ライムグリーン",
    "Kategorie-Farbe wählen" to "カテゴリの色を選択してください",
    "Neue Kategorie erstellen" to "新しいカテゴリを作成する",
    "Kategorie bearbeiten" to "カテゴリを編集する",
    "Neue Kategorie" to "新しいカテゴリ",
    "leer" to "空の",
    "Kein Paket gewählt" to "パッケージが選択されていません",
    "Gewählte Antwort" to "選択された回答",
    "Verworfene Antwort" to "拒否された回答",
    "beliebiges Paar" to "任意のペア",
    "Paris oder Rom" to "パリとかローマとか",
    "JSON Backup wird vorbereitet…" to "JSON バックアップを準備中です…",
    "🎉 JSON inkl. Bildern & Ketten kopiert!" to "🎉 画像とチェーンを含む JSON がコピーされました!",
    "JSON Backup Datei wird erstellt…" to "JSONバックアップファイルが作成されました...",
    "Daten werden eingespielt…" to "データがインポートされています...",
    "Kette gestartet" to "チェーンが開始されました",
    "🔗 Ketten-Bauer" to "🔗 チェーン作成者",
    "Linke Karte (Seite A)" to "左のカード（A面）",
    "Rechte Karte (Seite B)" to "右のカード（B面）",
    "Vorschau:" to "プレビュー:",
    "Paar / Option:" to "ペア/オプション:",
    "Beliebiges / letztes Paar" to "任意の/最後のペア",
    "Seite:" to "ページ：",
    "Linke Option (0)" to "左のオプション (0)",
    "Rechte Option (1)" to "右のオプション (1)",
    "🏷️ Kategorien & Farben" to "🏷️ カテゴリとカラー",
    "Titel des Ketten-Spiels" to "チェーンゲームのタイトル",
    "Unbenannte Kette" to "名前のないチェーン",
    "Verworfen" to "廃棄されました",
    "Freier Text" to "フリーテキスト",
    "Satzmuster (z.B. 1 Jahr lang in {})" to "文パターン (例: {} の 1 年間)",
    "Standardbild" to "デフォルトの画像",
    "eigen" to "自分の",
    "Eis" to "氷",
    "Eissorten" to "アイスクリーム味",
    "Gold" to "金",
    "Rosa" to "ピンク",
    "Lila" to "紫",
    "Blau" to "青",
    "Koralle" to "コーラル",
    "Smaragd" to "エメラルド",
    "Rubinrot" to "ルビーレッド",
    "Lavendel" to "ラベンダー",
    "Magenta" to "マゼンタ",
    "Orange" to "オレンジ",
    "Neubau mit Technik" to "テクノロジーを駆使した新しい建物",
    "Offene Küche" to "オープンキッチン",
    "Gemüsebeet" to "野菜畑",
    "Hängematte" to "ハンモック",
    "Blumenwiese" to "花の草原",
    "Dachterrasse" to "屋上テラス",
    "Grillplatz" to "バーベキューエリア",
    "Kamin" to "煙突",
    "Belgische Schokolade" to "ベルギーチョコレート",
    "In AI Studio hochladen und schreiben: \"Ersetze GeneratedHarmonyContent.kt komplett durch den Inhalt dieser Datei.\"" to "AI Studio にアップロードし、「GeneratedHarmonyContent.kt をこのファイルの内容で完全に置き換えます。」と書き込みます。",
    "Fragen & Spiele" to "質問とゲーム",
    "Kategorien" to "カテゴリー",
    "Themen" to "テーマ",
    "Für dich empfohlen" to "あなたへのおすすめ",
    "Paar-Statistiken" to "カップルの統計",
    "Gemeinsame Tage" to "一緒に過ごした日数",
    "Beantwortete Fragen" to "回答済みの質問",
    "Besuchte Städte" to "訪れた都市",
    "Besuchte Länder" to "訪れた国",
    "Widgets" to "ウィジェット",
    "Du fehlst mir" to "会いたい",
    "Denke an dich" to "あなたのことを考えてる",
    "Ich denke an dich" to "あなたのことを考えてる",
    "Kuss senden" to "キスを送る",
    "Kuss" to "キス",
    "ERGEBNISSE" to "結果",
    "BEANTWORTE" to "回答する",
    "Alle Pakete" to "すべてのパック",
    "Profil" to "プロフィール",
    "Dein Name" to "あなたの名前",
    "Partnerin" to "パートナー",
    "Zusammen seit" to "交際開始日",
    "Partner-Simulator" to "パートナーシミュレーター",
    "Sprache" to "言語",
    "Deutsch" to "ドイツ語",
    "Englisch" to "英語",
    "Entwickler-Modus" to "開発者モード",
    "Entwickler Studio Öffnen" to "開発者スタジオを開く",
    "Profil bearbeiten" to "プロフィールを編集",
    "Name Partnerin" to "パートナーの名前",
    "Hinzufügen" to "追加",
    "Momente" to "思い出",
    "Was ist passiert?" to "何があった？",
    "oder" to "または",
    "Zurück" to "戻る",
    "Deine eigene Antwort" to "あなた自身の回答",
    "Deine Antwort..." to "あなたの回答…",
    "Übernehmen" to "保存",
    "Antwortähnlichkeit" to "回答の一致度",
    "Diskutiert eure Antworten" to "お互いの回答について話そう",
    "Fertig!" to "完了！",
    "✎ Tippe, um zu antworten" to "✎ タップして答える",
    "Schreibe deine eigene Antwort" to "自分の回答を書く",
    "Quiz verlassen?" to "クイズを終了しますか？",
    "Möchtest du das Quiz wirklich verlassen? Dein bisheriger Fortschritt bleibt gespeichert." to "本当にクイズを終了しますか?前回の進行状況は保存されたままになります。",
    "Schreib frei, was dir wirklich dazu einfällt." to "本当に思ったことを自由に書いてください。",
    "Habt ihr überraschende Unterschiede entdeckt? Sprecht darüber, warum euch bestimmte Optionen besser gefallen!" to "驚くべき違いを発見しましたか?特定のオプションがより良いと思う理由について話してください。",
    "✕ Schließen" to "✕ 閉じる",
    "Hier ist gerade nichts.\nWechsle den Filter oder wähle ein anderes Thema." to "ここにはまだ何もありません。\nフィルターを変えるか、別のテーマを選んでください。",
    "✨ GFK-Brücke" to "✨ 非暴力コミュニケーションの橋",
    "Formuliert deinen Entwurf gewaltfrei um: Beobachtung, Gefühl, Bedürfnis, Bitte." to "観察・感情・ニーズ・お願いを使って、あなたの下書きを非暴力的な表現に書き換えます。",
    "Was möchtest du eigentlich sagen?" to "本当は何が言いたいのですか？",
    "In Chat einfügen" to "チャットに追加",
    "Analysiert eure Antworten & Chats nach Gottman und GFK." to "ゴットマン理論と非暴力コミュニケーションに基づいて、二人の回答とチャットを分析します。",
    "Wünsche? z.B. günstig, draußen" to "願い事？例えば安い、屋外",
    "Spiele & Städte bearbeiten, Ordner reinladen, Bilder anpassen" to "ゲームと都市の編集、フォルダーのロード、画像の調整",
    "🔥 Tägliche Aktivität" to "🔥 今日のアクティビティ",
    "+ Hinzufügen" to "+ 追加",
    "Noch keine Momente.\nHaltet euer erstes Erlebnis fest 💞" to "まだ思い出はありません。\n二人の最初の体験を残しましょう 💞",
    "Ein Harmony-Meilenstein eurer Liebe." to "あなたの愛の調和のマイルストーン。",
    "Was wollt ihr nie vergessen?" to "絶対に忘れたくないことは何ですか？",
    "🟠 Du bist dran" to "🟠 あなたの番",
    "Beantwortet Fragen gleichzeitig — Antworten werden erst sichtbar, wenn ihr beide fertig seid." to "質問に同時に回答します。回答は両方が終了するまで表示されません。",
    "Wir" to "私たち",
    "Hey du 💕 wie war dein Tag?" to "こんにちは💕今日はどうでしたか？",
    "Stressig — aber jetzt wird’s besser ☺️" to "ストレスはありますが、今は良くなってきています☺️",
    "Ich hab schon an unser Wiedersehen gedacht 🥹" to "私はすでに再会のことを考えていました 🥹",
    "Unser erstes Videodate" to "初めてのビデオデート",
    "Vier Stunden geredet und die Zeit vergessen." to "4時間も話し続けて、時間を忘れてしまいました。",
    "Überraschungspaket" to "サプライズパッケージ",
    "Kekse und ein Brief — ich musste weinen vor Freude." to "クッキーと手紙 - 嬉しくて泣きました。",
    "Das klingt schön 🥰" to "それはいいですね🥰",
    "Ich vermiss dich gerade richtig" to "今は本当にあなたがいなくて寂しいです",
    "Erzähl mir mehr davon 💕" to "詳しく教えてください💕",
    "Haha du bringst mich immer zum Lachen 😄" to "ハハ、あなたはいつも私を笑わせてくれます 😄",
    "Können wir heute Abend telefonieren?" to "今晩電話で話せませんか？",
    "Ich denk so oft an dich ❤️" to "あなたのことをよく思い出します❤️",
    "Gemini API Key ist nicht konfiguriert. Bitte füge deinen GEMINI_API_KEY im AI Studio Secrets Panel ein." to "Gemini API キーが設定されていません。 GEMINI_API_KEY を AI Studio シークレット パネルに貼り付けてください。",
    "Keine Antwort erhalten." to "回答が届きませんでした。",
    "Du bist dran" to "あなたの番",
    "Beantwortet" to "回答済み",
    "Überspringen" to "スキップ",
    "Weiter" to "次へ",
    "KI-Beziehungscoach" to "AI恋愛コーチ",
    "KI-Date-Ideen" to "AIデートアイデア",
    "Analyse starten" to "分析を開始",
    "Ideen generieren" to "アイデアを生成",
    "Namen und Startdatum eurer Beziehung." to "名前と交際開始日。",
    "Fertig" to "完了",
    "Weiter spielen" to "続けて遊ぶ",
    "Formuliere um..." to "書き換え中…",
    "Umformulieren" to "書き換える",
    "Nachricht an \$partnerName..." to "\$partnerName へのメッセージ...",
    "✅ Beantwortet" to "✅ 回答済み",
    "Verbinde dich mit \$partnerName" to "\$partnerName と接続する",
    "1 Jahr zusammen 🎉" to "一緒に1年🎉",
    "2 Jahre zusammen 🎉" to "一緒に2年🎉",
    "3 Jahre zusammen 🎉" to "一緒に3年🎉",
    "\$d Tage zusammen 💞" to "\$d 日間一緒に過ごしました 💞",
    "Moment festhalten" to "思い出を残す",
    "Invite-Code: HRM-8731 · alles freigeschaltet" to "招待コード: HRM-8731 · すべてのロックが解除されました",
    "✨ KI-Beziehungscoach" to "✨ AIリレーションシップコーチ",
    "Analysiere eure Muster..." to "パターンを分析してください...",
    "💡 KI-Date-Ideen" to "💡 AI デートのアイデア",
    "Sammle Ideen..." to "アイデアを集めて…",
    "🛠️ Entwickler-Modus" to "🛠️ 開発者モード",
    "Zusammen seit (TT.MM.JJJJ)" to "(DD.MM.YYYY) 以来一緒に",
    "Deine Antworten sind gespeichert. Sobald \${profile.partnerName} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "回答は保存されます。 \${profile.partnerName} がパッケージを完了すると、両方の応答が一緒に表示されます。",
    "Verbinde dich mit \${profile.partnerName}, um die Antwort zu sehen" to "回答を見るには \${profile.partnerName} と接続してください",
    "Quiz verlassen" to "クイズを終了",
    "Ergebnisse" to "結果",
    "Unterhaltung" to "エンターテインメント",
    "Hochzeit" to "結婚式",
    "Kinder" to "子ども",
    "Reden vor..." to "…の前に話す",
    "{ANZAHL} Bilder geladen — Namen prüfen, dann erstellen." to "{ANZAHL} 枚の画像を読み込みました。名前を確認してから作成してください。",
    "{ANZAHL} Bilder geladen." to "{ANZAHL} 画像がロードされました。",
    "{ANZAHL} Paare aus {ANZAHL} Bildern" to "{ANZAHL} 個の {ANZAHL} 画像のペア",
    "Bild {NUMMER} von {ANZAHL}…" to "{ANZAHL} からの画像 {NUMMER}…",
    "Speichere Bild {NUMMER} von {ANZAHL}…" to "画像 {NUMMER}/{ANZAHL} を保存中…",
    "Paar {NUMMER}" to "ペア {NUMMER}",
    "Frage {NUMMER}" to "質問 {NUMMER}",
    "Schritt {NUMMER}" to "ステップ {NUMMER}",
    "{ANZAHL} Paare" to "{ANZAHL} ペア",
    "{ANZAHL} Fragen" to "{ANZAHL} 質問",
    "{ANZAHL} Schritt(e)" to "{ANZAHL} ステップ",
    "{ANZAHL} Paare · {ANZAHL} Fragen" to "{ANZAHL} カップル · {ANZAHL} の質問",
    "{ANZAHL} Einträge" to "{ANZAHL} エントリ",
    "Fertig: {PAKETE} Pakete · {BILDER} Bilder · {DETAILS}" to "完了: {PAKETE} パッケージ · {BILDER} イメージ · {DETAILS}",
    "🎉 {ANZAHL} Pakete/Ketten & Bilder erfolgreich eingespielt!" to "🎉 {ANZAHL} パッケージ/チェーンと写真が正常にインポートされました!",
    "🎉 '{TITEL}' angelegt · {ANZAHL} Paare spielbereit" to "🎉 '{TITEL}' が作成されました · {ANZAHL} ペアがプレイ可能になりました",
    "• A: {OPTION} (Bild: {BILD})" to "• A: {OPTION} (画像: {BILD})",
    "• B: {OPTION} (Bild: {BILD})" to "• B: {OPTION} (画像: {BILD})",
    "'{TITEL}' gelöscht." to "「{TITEL}」が削除されました。",
    "'{TITEL}' gespeichert." to "「{TITEL}」が保存されました。",
    "Kategorie '{TITEL}' gespeichert." to "カテゴリ「{TITEL}」が保存されました。",
    "Kette '{TITEL}' gespeichert." to "チェーン「{TITEL}」が保存されました。",
    "Kette '{TITEL}' gelöscht." to "チェーン「{TITEL}」が削除されました。",
    "Bild für '{OPTION}' gesetzt." to "「{OPTION}」に設定された画像。",
    "Eigenes Bild für '{OPTION}' entfernt." to "「{OPTION}」のカスタム画像を削除しました。",
    "{EMOJI} „{WIDGET}“ an {PARTNER} gesendet" to "{EMOJI} 「{WIDGET}」を {PARTNER} に送信しました",
    "6 Monate im {ORT}" to "{ORT} で 6 か月",
    "1 Jahr lang in {ORT}" to "{ORT} で 1 年",
    "Weil du {OPTION} gewählt hast …" to "{OPTION} を選択したため...",
    "Verbinde dich mit {PARTNER}, um die Antwort zu sehen" to "回答を見るには {PARTNER} と接続してください",
    "Verbinde dich mit {PARTNER}" to "{PARTNER} と接続する",
    "Deine Antworten sind gespeichert. Sobald {PARTNER} das Paket beendet, werden beide Antworten gemeinsam sichtbar." to "回答は保存されます。 {PARTNER} がパッケージを完了すると、両方の応答が一緒に表示されます。",
    "Fehler bei der Umformulierung: {FEHLER}" to "言い換えエラー: {FEHLER}",
    "Fehler bei der Analyse: {FEHLER}" to "解析エラー: {FEHLER}",
    "Fehler bei der Ideengenerierung: {FEHLER}" to "アイデア生成エラー: {FEHLER}",
    "{EMOJI} {INHALT}" to "{EMOJI} {INHALT}",
    "{NUMMER}. {INHALT}" to "{NUMMER}。 {INHALT}",
    "HARMONY" to "HARMONY",
    "Home" to "ホーム",
    "Chat" to "チャット",
    "Dev" to "開発",
    "Jerome" to "Jerome",
    "Alex" to "Alex",
    "OR" to "または",
    "VS" to "VS",
    "Export teilen" to "エクスポートを共有",
    "Bilder teilen" to "画像を共有",
)


private fun exactJapanese(text: String): String =
    TranslationCatalog.exact(text, AppLanguage.JAPANESE) ?: text

internal fun localizeJapaneseDynamicContent(text: String): String? {
    Regex("^([\\p{So}\\p{Sk}\\uFE0F\\u200D]+\\s+)(.+)$").matchEntire(text)?.let { TranslationCatalog.exact(it.groupValues[2], AppLanguage.JAPANESE)?.let { translated -> return it.groupValues[1] + translated } }
    Regex("^(\\d+[.)]\\s+)(.+)$").matchEntire(text)?.let { TranslationCatalog.exact(it.groupValues[2], AppLanguage.JAPANESE)?.let { translated -> return it.groupValues[1] + translated } }
    Regex("^(\\d+) Bilder geladen — Namen prüfen, dann erstellen\\.$").matchEntire(text)?.let { return "${it.groupValues[1]} 枚の画像を読み込みました。名前を確認してから作成してください。" }
    Regex("^(\\d+) Bilder geladen\\.$").matchEntire(text)?.let { return "${it.groupValues[1]} 枚の画像を読み込みました。" }
    Regex("^(\\d+) Paare aus (\\d+) Bildern$").matchEntire(text)?.let { return "${it.groupValues[2]} 枚の画像から ${it.groupValues[1]} 組のペア" }
    Regex("^Bild (\\d+) von (\\d+)…$").matchEntire(text)?.let { return "画像 ${it.groupValues[1]}/${it.groupValues[2]}…" }
    Regex("^Speichere Bild (\\d+) von (\\d+)…$").matchEntire(text)?.let { return "画像 ${it.groupValues[1]}/${it.groupValues[2]} を保存中…" }
    Regex("^Paar (\\d+)$").matchEntire(text)?.let { return "ペア ${it.groupValues[1]}" }
    Regex("^Frage (\\d+)$").matchEntire(text)?.let { return "質問 ${it.groupValues[1]}" }
    Regex("^Schritt (\\d+)$").matchEntire(text)?.let { return "ステップ ${it.groupValues[1]}" }
    Regex("^(\\d+) Paare$").matchEntire(text)?.let { return "${it.groupValues[1]} 組のペア" }
    Regex("^(\\d+) Fragen$").matchEntire(text)?.let { return "${it.groupValues[1]} 問" }
    Regex("^(\\d+) Schritt\\(e\\)$").matchEntire(text)?.let { return "${it.groupValues[1]} ステップ" }
    Regex("^(\\d+) Paare · (\\d+) Fragen$").matchEntire(text)?.let { return "${it.groupValues[1]} 組のペア · ${it.groupValues[2]} 問" }
    Regex("^(\\d+) Einträge$").matchEntire(text)?.let { return "${it.groupValues[1]} 件" }
    Regex("^Fertig: (\\d+) Pakete · (\\d+) Bilder · (.+)$").matchEntire(text)?.let { return "完了: ${it.groupValues[1]} パック · ${it.groupValues[2]} 枚の画像 · ${it.groupValues[3]}" }
    Regex("^🎉 (\\d+) Pakete/Ketten & Bilder erfolgreich eingespielt!$").matchEntire(text)?.let { return "🎉 ${it.groupValues[1]} 個のパック/チェーンと画像を正常にインポートしました！" }
    Regex("^🎉 '(.+)' angelegt · (\\d+) Paare spielbereit$").matchEntire(text)?.let { return "🎉 '${exactJapanese(it.groupValues[1])}' を作成 · ${it.groupValues[2]} 組のペアがプレイ可能" }
    Regex("^• ([AB]): (.+) \\(Bild: (.+)\\)$").matchEntire(text)?.let { return "• ${it.groupValues[1]}: ${exactJapanese(it.groupValues[2])}（画像: ${it.groupValues[3]}）" }
    Regex("^([AB]): (.+)$").matchEntire(text)?.let { return "${it.groupValues[1]}: ${exactJapanese(it.groupValues[2])}" }
    Regex("^'(.+)' gelöscht\\.$").matchEntire(text)?.let { return "'${exactJapanese(it.groupValues[1])}' を削除しました。" }
    Regex("^'(.+)' gespeichert\\.$").matchEntire(text)?.let { return "'${exactJapanese(it.groupValues[1])}' を保存しました。" }
    Regex("^Kategorie '(.+)' gespeichert\\.$").matchEntire(text)?.let { return "カテゴリー '${exactJapanese(it.groupValues[1])}' を保存しました。" }
    Regex("^Kette '(.+)' gespeichert\\.$").matchEntire(text)?.let { return "チェーン '${exactJapanese(it.groupValues[1])}' を保存しました。" }
    Regex("^Kette '(.+)' gelöscht\\.$").matchEntire(text)?.let { return "チェーン '${exactJapanese(it.groupValues[1])}' を削除しました。" }
    Regex("^Bild für '(.+)' gesetzt\\.$").matchEntire(text)?.let { return "'${exactJapanese(it.groupValues[1])}' の画像を設定しました。" }
    Regex("^Eigenes Bild für '(.+)' entfernt\\.$").matchEntire(text)?.let { return "'${exactJapanese(it.groupValues[1])}' のカスタム画像を削除しました。" }
    Regex("^(.+) „(.+)\\\" an (.+) gesendet$").matchEntire(text)?.let { return "${it.groupValues[1]} が ${it.groupValues[3]} に「${exactJapanese(it.groupValues[2])}」を送信しました" }
    Regex("^6 Monate im (.+)$").matchEntire(text)?.let { return "${exactJapanese(it.groupValues[1])}で6か月" }
    Regex("^1 Jahr lang in (.+)$").matchEntire(text)?.let { return "${exactJapanese(it.groupValues[1])}で1年間" }
    Regex("^Weil du (.+) gewählt hast …$").matchEntire(text)?.let { return "${exactJapanese(it.groupValues[1])}を選んだから…" }
    Regex("^Verbinde dich mit (.+), um die Antwort zu sehen$").matchEntire(text)?.let { return "回答を見るには ${it.groupValues[1]} と接続してください" }
    Regex("^Verbinde dich mit (.+)$").matchEntire(text)?.let { return "${it.groupValues[1]} と接続する" }
    Regex("^Deine Antworten sind gespeichert\\. Sobald (.+) das Paket beendet, werden beide Antworten gemeinsam sichtbar\\.$").matchEntire(text)?.let { return "あなたの回答は保存されました。${it.groupValues[1]} がパックを完了すると、二人の回答を一緒に見られます。" }
    Regex("^Fehler bei der Umformulierung: (.+)$").matchEntire(text)?.let { return "書き換えエラー: ${it.groupValues[1]}" }
    Regex("^Fehler bei der Analyse: (.+)$").matchEntire(text)?.let { return "分析エラー: ${it.groupValues[1]}" }
    Regex("^Fehler bei der Ideengenerierung: (.+)$").matchEntire(text)?.let { return "アイデア生成エラー: ${it.groupValues[1]}" }
    if (text.contains(" · ")) { val translated=text.split(" · ").joinToString(" · ") { TranslationCatalog.translate(it, AppLanguage.JAPANESE) ?: it }; if (translated != text) return translated }
    return null
}
